/** v054 mechanism tests. Scripted mock choices are not model / intelligence evidence. */
import test from 'node:test';import assert from 'node:assert/strict';
import {AutonomousSession} from '../dist/src/adaptive/session.js';
import {AdaptiveGS} from '../dist/vendor/gs-engine-ts/src/adaptive.js';
import {tiny,program,proposal,generator,backend,chooseDeposit} from './fixtures/adaptive-v05.mjs';
import {subproblem,analysis} from './fixtures/adaptive-v054.mjs';
const make=(g=generator(),b=backend(chooseDeposit),opts={},w=tiny())=>new AutonomousSession(w,{generator:g,backend:b,strategy:'direct',orderSeed:441,maxGCalls:12,...opts});
const all=f=>f.kind==='analysis'?f.options[0]?.id??null:chooseDeposit(f);
const waitProgram=()=>program('暂行条件中的真实等待',['wait','deposit'],{until:[{kind:'delta',field:'turn',atLeast:24}],maxActions:24});

test('054 startup order is G -> install -> action S; no approval calls at any depth limit',async()=>{
 for(const maxDepth of [0,1,2,3]){const order=[],g=generator(()=>{order.push('G');return proposal();}),b=backend(f=>{order.push('S:'+f.kind);return chooseDeposit(f);}),s=make(g,b,{maxDepth});await s.step();assert.deepEqual(order,['G','S:action']);assert.equal(s.lastResult.outcome,'succeeded');assert.equal(s.diagnostics().metaCalls,0);assert.equal(s.events.filter(e=>e.type==='meta_enter').length,0);assert.equal(s.events.find(e=>e.type==='adaptation_committed').data.worldAction,false);}
});
test('054 G cannot directly execute even a singleton; S none returns to same G with exact answer',async()=>{
 const g=generator(i=>proposal(program(i.cause==='selector_abstained'?'新问题':'旧问题',['deposit']))),b=backend(f=>f.question==='新问题'?chooseDeposit(f):null),s=make(g,b);await s.step();assert.equal(s.lastResult.outcome,'succeeded');assert.deepEqual(g.calls.map(x=>x.depth),[0,0]);assert.equal(g.calls[1].answer.choice,null);assert.equal(g.calls[1].frame.question,'旧问题');assert.equal(g.calls[1].previous[0].commitScope,'decision-interface-only');assert.equal(b.calls.length,2);
});
test('054 sustained refusal consumes revisions, not recursion; no forced action or extra budget',async()=>{const g=generator((i,n)=>proposal(program('修订'+n))),s=make(g,backend(()=>null),{maxDepth:0,maxRevisions:3});await s.step();assert.equal(s.world.snapshot().turn,0);assert.equal(s.lastResult.reason,'adaptation_budget_exhausted');assert.equal(g.calls.length,3);assert.equal(s.diagnostics().metaCalls,0);});
test('054 G may replace the original bad plan, not merely reword an approval question',async()=>{const g=generator(i=>i.cause==='selector_abstained'?proposal(program('替换方案',['deposit'])):proposal(program('不采用的原方案',['wait','deposit']))),s=make(g,backend(f=>f.question==='替换方案'?chooseDeposit(f):null));await s.step();assert.equal(s.lastResult.outcome,'succeeded');assert.equal(s.export().program.stages[0].kinds[0],'deposit');assert.ok(g.calls[1].frame.options.some(o=>o.id==='wait'));});
test('054 child answer returns to original G, never writes world or auto-applies parent',async()=>{
 const g=generator(i=>i.frame.kind==='analysis'?analysis():i.cause==='subproblem_completed'?proposal():subproblem()),s=make(g,backend(all));await s.step();assert.equal(s.lastResult.outcome,'succeeded');assert.deepEqual(g.calls.map(i=>i.depth),[0,1,0]);const r=g.calls[2];assert.equal(r.frame.kind,'action');assert.equal(r.evidence.observedWorld.turn,0);assert.equal(r.previous.at(-1).subproblem.status,'answered');assert.equal(r.previous.at(-1).subproblem.epistemicStatus,'model-judgment-not-world-fact');assert.equal(s.events.filter(e=>e.type==='transition').length,1);assert.equal(s.diagnostics().metaCalls,1);
});
test('054 child refusal can be repaired at child same level; parent frame retained',async()=>{let n=0;const g=generator(i=>i.frame.kind==='analysis'?analysis(i.cause==='selector_abstained'?'更窄的问题':'初始问题'):i.cause==='subproblem_completed'?proposal():subproblem()),b=backend(f=>f.kind==='analysis'?(++n===1?null:f.options[0].id):chooseDeposit(f)),s=make(g,b);await s.step();assert.equal(s.lastResult.outcome,'succeeded');assert.deepEqual(g.calls.map(i=>i.depth),[0,1,1,0]);assert.equal(g.calls[2].answer.choice,null);});
test('054 maxDepth=0 declines a child branch and still lets original G produce an update',async()=>{const g=generator(i=>i.cause==='subproblem_unresolved'?proposal():subproblem()),s=make(g,backend(all),{maxDepth:0});await s.step();assert.equal(s.lastResult.outcome,'succeeded');assert.deepEqual(g.calls.map(i=>i.depth),[0,0]);assert.equal(g.calls[1].previous[0].subproblem.reason,'subproblem_depth_exhausted');assert.equal(s.diagnostics().metaCalls,0);});
test('054 nested depth limit returns through child and then parent without resetting shared spending',async()=>{
 const g=generator(i=>{if(i.frame.kind==='analysis')return i.cause==='subproblem_unresolved'?analysis():subproblem('更深的诊断');return i.cause==='subproblem_completed'?proposal():subproblem();});const s=make(g,backend(all),{maxDepth:1});await s.step();assert.equal(s.lastResult.outcome,'succeeded');assert.deepEqual(g.calls.map(i=>i.depth),[0,1,1,0]);assert.ok(g.calls[2].previous.at(-1).subproblem.reason.includes('depth'));assert.equal(s.diagnostics().gCalls,4);assert.equal(s.world.snapshot().turn,1);
});
test('054 unresolved child returns evidence and preserves original S abstention',async()=>{
 let seenRoot=0;const g=generator(i=>{if(i.frame.kind==='analysis')return analysis();if(i.cause==='subproblem_unresolved')return proposal(program('改进后'));if(i.cause==='selector_abstained')return subproblem('诊断原因',{maxRevisions:1,maxGenerations:1});return proposal(program('初始待定'));});const b=backend(f=>f.kind==='analysis'?null:f.question==='改进后'?chooseDeposit(f):(seenRoot++,null));const s=make(g,b);await s.step();assert.equal(s.lastResult.outcome,'succeeded');const r=g.calls.at(-1);assert.equal(r.frame.question,'初始待定');assert.equal(r.answer.choice,null);assert.equal(r.previous.at(-1).subproblem.status,'unresolved');assert.equal(r.previous.at(-1).subproblem.answer.choice,null);assert.ok(r.previous.at(-1).subproblem.attempts.length);assert.equal(seenRoot,1);
});
test('054 child generation cap is local: parent has one remaining generation and resumes',async()=>{const g=generator(i=>i.frame.kind==='analysis'?({bad:true}):i.cause==='subproblem_unresolved'?proposal():subproblem('格式受阻子问题',{maxGenerations:1})),s=make(g,backend(all),{maxGCalls:3,maxFormatRepairs:2});await s.step();assert.equal(s.lastResult.outcome,'succeeded');assert.equal(g.calls.length,3);assert.equal(g.calls[2].previous.at(-1).subproblem.reason,'subproblem_generation_budget_exhausted');});
test('054 global G budget is not reset by child failure',async()=>{const g=generator(i=>i.frame.kind==='analysis'?({bad:true}):subproblem()),s=make(g,backend(all),{maxGCalls:2});await s.step();assert.equal(g.calls.length,2);assert.equal(s.world.snapshot().turn,0);assert.match(s.lastResult.reason,/budget/);});
test('054 repeated identical child request is returned as duplicate, not restarted',async()=>{const g=generator(i=>i.frame.kind==='analysis'?analysis():subproblem('同一子问题',{maxGenerations:1,maxRevisions:1})),s=make(g,backend(()=>null),{maxRevisions:3});await s.step();assert.equal(g.calls.filter(i=>i.frame.kind==='analysis').length,1);assert.ok(s.events.some(e=>e.type==='subproblem_return'&&e.data.result.reason==='duplicate_subproblem_no_change'));assert.equal(s.world.snapshot().turn,0);});
test('054 two explicit child levels can return to root with only action S writing the world',async()=>{const g=generator(i=>i.frame.kind==='action'?(i.cause==='subproblem_completed'?proposal():subproblem('level1')):i.depth===1&&i.cause!=='subproblem_completed'?subproblem('level2'):analysis()),s=make(g,backend(all),{maxDepth:2,maxGCalls:8});await s.step();assert.equal(s.lastResult.outcome,'succeeded');assert.deepEqual(g.calls.map(i=>i.depth),[0,1,2,1,0]);assert.equal(s.diagnostics().metaCalls,2);assert.equal(s.history.length,1);});
test('054 child network error is fatal, not a reason to bypass and act',async()=>{const g=generator(i=>{if(i.frame.kind==='analysis')throw Error('provider-network-failure');return subproblem();}),s=make(g,backend(all));await s.step();assert.equal(s.lastResult.kind,'fault');assert.equal(s.world.snapshot().turn,0);assert.equal(g.calls.length,2);});
test('054 child late answer after world edit is stale and cannot install root update',async()=>{let s;const g=generator(i=>i.frame.kind==='analysis'?analysis():subproblem()),b=backend(f=>{if(f.kind==='analysis'){s.world.edit('wall',{x:0,y:0});return f.options[0].id;}return chooseDeposit(f);});s=make(g,b);await s.step();assert.equal(s.lastResult.kind,'stale');assert.equal(s.world.snapshot().turn,0);assert.equal(s.events.filter(e=>e.type==='adaptation_committed'&&e.data.depth===0).length,0);});
test('054 condition-only updates never refund physical costs or erase failed actual evidence',async()=>{const g=generator(i=>i.cause==='initial_environment_review'?proposal(waitProgram()):proposal(program('后续实际交付'))),b=backend(f=>f.question.includes('暂行')?'wait':chooseDeposit(f)),s=make(g,b);for(let i=0;i<7&&!s.finished;i++)await s.step();assert.equal(s.lastResult.outcome,'succeeded');assert.equal(s.world.snapshot().energy,73);assert.equal(g.calls[1].evidence.measuredHistory.length,6);assert.equal(g.calls[1].evidence.previousIssue.notProofOfError,true);});
test('054 invalid root goal/permission additions never install',async()=>{const p=proposal();p.proposals[0].rootGoal='cheat';const s=make(generator(()=>p),backend(all),{maxFormatRepairs:0});await s.step();assert.equal(s.lastResult.reason,'output_format_repair_exhausted');assert.equal(s.diagnostics().committedRevisions,undefined);assert.equal(s.diagnostics().outputAccounting.committedRevisions,0);});
test('054 multiple interface updates are rejected, never silently pick first',async()=>{const p=proposal();p.proposals.push(p.proposals[0]);const s=make(generator(()=>p),backend(all),{maxFormatRepairs:0});await s.step();assert.equal(s.lastResult.reason,'output_format_repair_exhausted');assert.equal(s.diagnostics().sCalls,0);});
test('054 format errors still use compact repair before direct installation',async()=>{const p=proposal(),g=generator((i,n)=>n===1?{actionFrame:p.proposals[0]}:p),s=make(g,backend(all),{maxRevisions:1,maxFormatRepairs:1});await s.step();assert.equal(s.lastResult.outcome,'succeeded');assert.equal(g.calls[1].schema,'gs/output-repair-request/v1');assert.equal(g.calls[1].evidence,undefined);assert.equal(s.diagnostics().outputAccounting.revisionAttempts,1);assert.equal(s.diagnostics().metaCalls,0);});
test('054 stale stage update is a decision-condition failure, not frozen-intent format repair',async()=>{
 const g=generator((i,n)=>n===1?proposal(program('旧条件')):n===2?{proposals:[{kind:'stage-update',expectedPolicyVersion:999,stageIndex:0,changes:{question:'修正后的条件'}}]}:proposal(program('新条件'))),s=make(g,backend(f=>f.question==='新条件'?chooseDeposit(f):null));await s.step();assert.equal(s.lastResult.outcome,'succeeded');assert.equal(g.calls.length,3);assert.equal(g.calls[2].cause,'inconsistent_decision_conditions');assert.equal(g.calls[2].previous.at(-1).reason,'stale_stage_update');assert.equal(s.diagnostics().outputAccounting.formatRepairs,0);
});
test('054 explicit child cancellation cannot return a result or fall through into world action',async()=>{
 let s;const g=generator(i=>{if(i.frame.kind==='analysis'){s.cancel();return analysis();}return subproblem();});s=make(g,backend(any=>any.options[0]?.id??null));await s.step();assert.equal(s.lastResult.kind,'stopped');assert.equal(s.world.snapshot().turn,0);assert.equal(g.calls.length,2);assert.equal(s.events.filter(e=>e.type==='subproblem_return').length,0);
});
