/** Local transport tests. No request in this file reaches a real provider. */
import test from 'node:test';
import assert from 'node:assert/strict';
import {adaptiveRequest,generatorMessages} from '../server/adaptive.mjs';
import {proposal} from './fixtures/adaptive-v05.mjs';
const env={LLM_URL:'http://127.0.0.1/mock',LLM_MODEL:'local-provider-fixture',LLM_API_KEY:'LOCAL_SECRET_NOT_IN_PROMPT'};
const input=()=>({schema:'gs/adaptation-request/v1',depth:0,cause:'selector_abstained',frame:{kind:'action',revision:'2',question:'任务未完成',context:{observation:{energy:97}},options:[]},answer:{choice:null,detail:{confidence:.39}},previous:[{reason:'prior schema rejected'}],evidence:{schema:'gs/g-evidence/v05',informationPolicy:'no-reference/v05',publicRules:{energy:'one action costs one energy'},measuredHistory:[{delta:{energy:-1}}],selectorHistory:[{choice:null}],previousIssue:{kind:'decision_blocked'}}});
const call=(i=input(),extra={})=>adaptiveRequest(i,{signal:new AbortController().signal,env,charge:()=>{},fetcher:async()=>new Response(JSON.stringify({model:'local-provider-fixture',choices:[{message:{content:JSON.stringify(proposal())},finish_reason:'stop'}],usage:{prompt_tokens:100,completion_tokens:30}})),...extra});
test('v05 G wire supplies structural schema only, not solved skill example',()=>{const m=generatorMessages(input()),u=JSON.parse(m[1].content);assert.ok(u.outputContract);assert.deepEqual(u.request,input());for(const forbidden of ['place-resource','wait-access','skill-1234567890abcdef','exampleSolution','optimalRoute'])assert.ok(!JSON.stringify(m).includes(forbidden));assert.ok(!('example'in u));});
test('v05 exact G transport body is exported without auth headers or key',async()=>{let sent,headers;const r=await call(input(),{fetcher:async(_url,o)=>{sent=JSON.parse(o.body);headers=o.headers;return new Response(JSON.stringify({model:'returned-model',choices:[{message:{content:JSON.stringify(proposal())}}],usage:{prompt_tokens:30,completion_tokens:14}}));}});assert.equal(headers.authorization,'Bearer '+env.LLM_API_KEY);assert.deepEqual(r.transport.request,sent);assert.ok(!JSON.stringify(r).includes(env.LLM_API_KEY));assert.equal(r.usage.inputTokens,30);assert.equal(r.usage.model,'returned-model');});
test('v05 G input carries actual S and feedback without rule success label',()=>{const i=input(),u=JSON.parse(generatorMessages(i)[1].content);assert.deepEqual(u.request.answer,i.answer);assert.deepEqual(u.request.evidence.selectorHistory,i.evidence.selectorHistory);assert.deepEqual(u.request.previous,i.previous);assert.deepEqual(u.request.evidence.previousIssue,i.evidence.previousIssue);});
test('v05 wrong information policy rejected before model charge',async()=>{let n=0;const i=input();i.evidence.informationPolicy='reference';await assert.rejects(call(i,{charge:()=>n++}));assert.equal(n,0);});
test('v05 oversized G context fails before charge',async()=>{let n=0;const i=input();i.evidence.extra='x'.repeat(230000);await assert.rejects(call(i,{charge:()=>n++}),/too large/);assert.equal(n,0);});
test('v05 missing credentials sends nothing',async()=>{let n=0;await assert.rejects(call(input(),{env:{},charge:()=>n++}),e=>e.status===503);assert.equal(n,0);});
test('v05 insecure remote provider address rejected',async()=>{let n=0;await assert.rejects(call(input(),{env:{...env,LLM_URL:'http://untrusted.example/v1'},charge:()=>n++}),/HTTPS or local/);assert.equal(n,0);});
test('v05 already cancelled request does not charge',async()=>{let n=0;const c=new AbortController();c.abort();await assert.rejects(call(input(),{signal:c.signal,charge:()=>n++}));assert.equal(n,0);});
test('v05 provider failure is explicit with no hidden retry',async()=>{let n=0;await assert.rejects(call(input(),{fetcher:async()=>{n++;return new Response('offline',{status:503});}}),/HTTP 503/);assert.equal(n,1);});
test('v05 invalid model program returns structural feedback and preserves billed usage',async()=>{const r=await call(input(),{fetcher:async()=>new Response(JSON.stringify({choices:[{message:{content:'{"proposals":[{"kind":"eval","code":"boom"}]}'}}],usage:{prompt_tokens:51,completion_tokens:13}}))});assert.ok(r.output.invalidProposal);assert.equal(r.usage.inputTokens,51);assert.ok(r.transport.response.content.includes('eval'));});
test('v05 malformed JSON generation is returned for bounded correction, not silently accepted',async()=>{const r=await call(input(),{fetcher:async()=>new Response(JSON.stringify({choices:[{message:{content:'not json'}}]}))});assert.ok(r.output.invalidProposal);assert.equal(r.usage,undefined);});
test('v05 generation cannot modify root target or authority',async()=>{const bad=proposal();bad.proposals[0].target=0;const r=await call(input(),{fetcher:async()=>new Response(JSON.stringify({choices:[{message:{content:JSON.stringify(bad)}}]}))});assert.match(r.output.invalidProposal.reason,/unsupported_field/);});
test('v05 explicit vendor extensions passed, never guessed by default',async()=>{const r=await call(input(),{env:{...env,LLM_THINKING:'enabled',LLM_REASONING_EFFORT:'low'}});assert.deepEqual(r.transport.request.thinking,{type:'enabled'});assert.equal(r.transport.request.reasoning_effort,'low');const plain=await call();assert.ok(!('thinking'in plain.transport.request));assert.ok(!('reasoning_effort'in plain.transport.request));});
test('v05 bad thinking settings fail before requests',async()=>{let n=0;await assert.rejects(call(input(),{env:{...env,LLM_THINKING:'invented'},charge:()=>n++}),/THINKING/);assert.equal(n,0);});

 test('v05 S transport records exact request body without credential headers',async()=>{
 const {judgmentRequest}=await import('../server/judgment.mjs');let sent;
 const q={backend:'jev',state:{evidence:{frame:{kind:'action'}}},questions:{choose:{type:'choice',instructions:'Which option?',criteria:{a:'offered',none:'abstain'}}}};
 const r=await judgmentRequest(q,{signal:new AbortController().signal,env:{TYPESAFE_API_KEY:'LOCAL_S_SECRET',JEV_MODEL:'mock'},charge:()=>{},fetcher:async(u,o)=>{sent=JSON.parse(o.body);return new Response(JSON.stringify({model:'mock',answers:{choose:{type:'choice',choice:'none',confidence:1,probabilities:{a:0,none:1}}}}));}});
 assert.deepEqual(r.transport.request,sent);assert.ok(!JSON.stringify(r).includes('LOCAL_S_SECRET'));assert.equal(r.transport.response.answers.choose.choice,'none');
});
