import test from 'node:test';import assert from 'node:assert/strict';
import {createWorld} from '../dist/src/game/world.js';
import {SkillSession} from '../dist/src/skills/runtime.js';
import {ReactiveCatalogue,synthesizeAccess} from '../dist/src/skills/catalogue.js';
import {ExperienceTable,experienceKey,projectState} from '../dist/src/skills/experience.js';
import {makeSkill,parseSkill,BASE_SKILLS,DEFAULT_WEIGHTS} from '../dist/src/skills/spec.js';
import {simulateSkill,createFrame,candidates,markApplied,advance,localSuccess} from '../dist/src/skills/behavior.js';
import {simulate} from '../dist/src/planning/search.js';
import {RootBudget,ExecutionLease} from '../dist/vendor/gs-engine-ts/src/resources.js';
import {GSEngine} from '../dist/vendor/gs-engine-ts/src/engine.js';
const access=()=>makeSkill('access-open',['place-resource','wait-access'],'grammar-search');
const bind=s=>({targetId:s.guards[0]?.id??'',targetBerryIds:s.berries.filter(b=>Math.abs(b.x-s.guards[0].anchor.x)+Math.abs(b.y-s.guards[0].anchor.y)<=4).map(b=>b.id),amount:0});
async function run(s,n=400){for(let i=0;i<n&&!s.finished;i++)await s.step();return s;}
async function local(s){for(let i=0;i<90&&!s.finished&&!s.summaries.length;i++)await s.step();return s;}
const storage=()=>{const m=new Map();return {getItem:k=>m.get(k)??null,setItem:(k,v)=>m.set(k,v)};};
const judgment=(cs,id)=>({choice:id,confidence:1,probabilities:Object.fromEntries(cs.map(c=>[c.id,c.id===id?1:0])),suitability:Object.fromEntries(cs.map(c=>[c.id,1])),abstainProbability:id?0:1});

test('v03 finite schema rejects custom root verifier, eval and recursive calls',()=>{const s=access();for(const x of [{...s,eval:'attack()'},{...s,success:'root-goal-is-true'},{...s,phases:[{id:'x',rule:'callSkill',until:'local-success',maxSteps:1}]},{...s,maxSteps:Infinity}])assert.throws(()=>parseSkill(x));});
test('v03 capabilities and feature sources are registered',()=>{for(const x of [{...access(),capabilities:['teleport']},{...access(),features:['apiKey']},{...access(),weights:{...DEFAULT_WEIGHTS,progress:100}}])assert.throws(()=>parseSkill(x));});
test('v03 phase local-goal contract not caller-defined',()=>assert.throws(()=>parseSkill({...access(),parameters:'none'})));
test('v03 grammar composes phases and tests failed candidates',async()=>{const s=createWorld('guarded'),attempts=[];let spent=0;const spec=await synthesizeAccess(s,bind(s),n=>spent+=n,new AbortController().signal,x=>attempts.push(x));assert.equal(spec.source,'grammar-search');assert.deepEqual(spec.phases.map(p=>p.rule),['place-resource','wait-access']);assert(attempts.some(x=>!x.success));assert(spent>0);});
test('v03 grammar cancels before spending',async()=>{const a=new AbortController();a.abort();let spent=0;const s=createWorld('guarded');await assert.rejects(synthesizeAccess(s,bind(s),n=>spent+=n,a.signal));assert.equal(spent,0);});
test('v03 local success is not root success',async()=>{const s=await local(new SkillSession(createWorld('guarded'),'reactive',undefined,{initialSkills:[access()]}));assert(s.summaries[0].localSucceeded);assert.equal(s.summaries[0].rootSucceeded,false);assert.equal(s.world.snapshot().delivered,0);assert.equal(s.finished,false);assert.equal(s.active,null);assert.equal(s.lease.activeOwner,null);});
test('v03 child and parent use actual GSEngine instances',async()=>{const s=new SkillSession(createWorld('guarded'),'reactive',undefined,{initialSkills:[access()]});assert(s.rootEngine instanceof GSEngine);await s.step();assert(s.active.engine instanceof GSEngine);assert.equal(s.lease.activeOwner,s.active.runId);assert.equal(s.world.snapshot().turn,1);s.cancel();});
test('v03 parent returns to selection after local end',async()=>{const s=await local(new SkillSession(createWorld('guarded'),'reactive',undefined,{initialSkills:[access()]}));await s.step();assert.equal(s.active.spec.success,'acquired-one');assert.equal(s.summaries.length,1);s.cancel();});
test('v03 same access spec rebinds mirrored world with no coordinate change',()=>{const spec=access();for(const id of ['guarded','remix']){const s=createWorld(id),r=simulateSkill(spec,s,bind(s));assert(r.success,id);assert.equal(r.final.delivered,0);}assert(!JSON.stringify(spec).includes('"x":'));});
test('v03 irrelevant wall does not invalidate entire active skill',async()=>{const s=new SkillSession(createWorld('guarded'),'reactive',undefined,{initialSkills:[access()]});await s.step();const id=s.active.runId;assert(s.edit('wall',{x:0,y:0}).ok);await local(s);assert(s.summaries[0].localSucceeded);assert.equal(s.summaries[0].status,'external_change');assert.equal(s.planning.searchRuns,0);assert.equal(s.summaries[0].runId,id);assert.equal(s.experience.list().length,0);});
test('v03 one-turn guard delay is handled within current skill without regeneration',()=>{
 const initial=createWorld('guarded'),spec=access(),f=createFrame(initial,bind(initial));let w=initial,delayed=false;
 const normal=simulateSkill(spec,initial,bind(initial));
 for(let i=0;i<36&&!localSuccess(spec,f,w);i++){advance(spec,f,w);const c=candidates(spec,f,w)[0];assert(c);const guard=structuredClone(w.guards[0]);w=simulate(w,c.action);markApplied(f,c.action);
  if(!delayed&&w.lures.length&&w.guards[0].eating===0&&(guard.x!==w.guards[0].x||guard.y!==w.guards[0].y)){w.guards[0].x=guard.x;w.guards[0].y=guard.y;delayed=true;}
 }
 assert(delayed);assert(localSuccess(spec,f,w));assert(w.turn>normal.steps);assert.equal(spec.id,access().id);
});
test('v03 local timeout is finite and not promoted',async()=>{const bad={...makeSkill('access-open',['wait-access']),maxSteps:2};const c=new ReactiveCatalogue();c.trial(bad);const s=await local(new SkillSession(createWorld('guarded'),'reactive',undefined,{catalogue:c,initialSkills:[bad]}));assert.equal(s.summaries[0].localSucceeded,false);assert.equal(s.summaries[0].outcome.steps,2);assert.equal(c.list()[0].successes,0);});
test('v03 shared root action budget cannot be duplicated by child',async()=>{const s=await run(new SkillSession(createWorld('guarded'),'reactive',undefined,{initialSkills:[access()],limits:{actions:3}}));assert(s.finished);assert.equal(s.budget.snapshot().used.actions,3);assert.equal(s.world.snapshot().turn,3);assert.equal(s.lease.activeOwner,null);});
test('v03 shared search budget includes parameter binding and verification',async()=>{const s=await run(new SkillSession(createWorld('guarded'),'reactive',undefined,{limits:{searchNodes:10}}));assert(s.finished);assert(s.budget.snapshot().used.searchNodes<=10);assert.equal(s.world.snapshot().turn,0);});
test('v03 provider budget reserved before attempted calls',async()=>{let calls=0;const s=await run(new SkillSession(createWorld('meadow'),'reactive-jev',undefined,{limits:{providerCalls:1},providers:{select:async x=>{calls++;return {output:judgment(x.candidates,x.candidates[0].id)}}}}));assert.equal(calls,1);assert.equal(s.budget.snapshot().used.providerCalls,1);assert(s.finished);});
test('v03 parent cancellation cancels child and releases lease',async()=>{const s=new SkillSession(createWorld('guarded'),'reactive',undefined,{initialSkills:[access()]});await s.step();const turn=s.world.snapshot().turn;s.cancel();await s.step();assert.equal(s.world.snapshot().turn,turn);assert.equal(s.lease.activeOwner,null);assert.equal(s.summaries[0].status,'interrupted');});
test('v03 concurrent stepping rejected',async()=>{const s=new SkillSession(createWorld('guarded'));const p=s.step();await assert.rejects(s.step(),/concurrent/);await p;s.cancel();});
test('v03 lease rejects deeper calls and double writer',()=>{const l=new ExecutionLease();assert.throws(()=>l.acquire('a',2));l.acquire('a',1);assert.throws(()=>l.acquire('b',1));assert.throws(()=>l.assert('b'));l.release('a');assert.equal(l.activeOwner,null);});
test('v03 root budget bounded counters',()=>{const b=new RootBudget({actions:1,cycles:2,providerCalls:1,searchNodes:1,skillCalls:1,durationMs:1000});b.reserve('actions');assert.throws(()=>b.reserve('actions'));assert.equal(b.snapshot().used.actions,1);});
test('v03 infrastructure failures do not silently switch to rules',async()=>{let count=0;const s=await run(new SkillSession(createWorld('meadow'),'reactive-jev',undefined,{providers:{select:async()=>{count++;throw Error('provider offline')}}}));assert.equal(count,1);assert.equal(s.world.snapshot().turn,0);assert(s.finished);assert.equal(s.experience.list().length,0);});
test('v03 unknown child receipt pauses root and earns no positive evidence',async()=>{const s=new SkillSession(createWorld('guarded'),'reactive',undefined,{initialSkills:[access()]});await s.step();s.active.domain.physical.execute=async()=>({status:'unknown',detail:'lost remote receipt'});await s.step();assert(s.finished);assert.equal(s.lease.activeOwner,null);assert.equal(s.experience.list().length,0);assert.equal(s.summaries[0].status,'interrupted');});
test('v03 local generation accepts structured repair feedback and counts providers',async()=>{let n=0;const inputs=[];const s=new SkillSession(createWorld('guarded'),'reactive-live',undefined,{providers:{generate:async i=>{inputs.push(i);n++;return {output:n===1?{...access(),maxSteps:999}:access(),usage:{provider:'mock',model:'fixture',inputTokens:10,outputTokens:10}}}}});await s.step();assert.equal(n,2);assert(inputs[1].feedback);assert.equal(s.budget.snapshot().used.providerCalls,2);assert.equal(s.planning.providerG,2);assert.equal(s.export().hierarchy.providers.length,2);assert.equal(s.export().usage.length,2);assert.equal(s.export().rejectedUsage.length,1);assert.equal(s.rootEngine.currentPolicy.version,2);assert.equal(s.world.snapshot().turn,0);s.cancel();});
test('v03 rejected skill cannot modify root goal',async()=>{const s=new SkillSession(createWorld('guarded'),'reactive-live',undefined,{providers:{generate:async()=>({output:{...access(),success:'root-always-true'}})}});await s.step();assert(s.finished);assert.equal(s.world.snapshot().turn,0);assert.equal(s.planning.providerG,3);});
test('v03 feature selection changes only model projection, not authoritative state',()=>{const s=createWorld('guarded'),p=projectState(s,['resources'],'entry');assert.deepEqual(Object.keys(p),['resources']);assert.equal(s.guards.length,1);assert(!('guards'in p));});
test('v03 registered score weights have a real ranking consumer',()=>{const s=createWorld('meadow'),spec=structuredClone(BASE_SKILLS[0]);const b={targetId:s.berries[0].id,targetBerryIds:[s.berries[0].id],amount:1};const f=createFrame(s,b),a=candidates(spec,f,s);const other={...spec,weights:{...spec.weights,progress:0,safety:0}};const bcs=candidates(other,createFrame(s,b),s);assert(a.length);assert.notDeepEqual(a.map(x=>x.score),bcs.map(x=>x.score));});
test('v03 experience off/record/use changes statistical updates and preference',()=>{const s=createWorld('guarded'),key=experienceKey(s,access()),o={success:true,steps:9,energyDelta:-9,attacks:0,providerCalls:0,searchNodes:20};for(const mode of ['off','record','use']){const t=new ExperienceTable(mode);for(let i=0;i<3;i++)t.observe(key,o);assert.equal(t.list().length,mode==='off'?0:1);assert.equal(t.preference(key,DEFAULT_WEIGHTS)!==0,mode==='use');}});
test('v03 measured outcomes actually alter parent selection, not only logs',async()=>{
 const initial=createWorld('guarded'),bad={...makeSkill('access-open',['wait-access']),id:'a-unproductive',maxSteps:2},good={...access(),id:'z-effective'};
 // Training evidence comes from real child executions on the same start, not manually supplied success labels.
 const training=new ExperienceTable('use');for(let i=0;i<3;i++){await local(new SkillSession(initial,'reactive',undefined,{initialSkills:[bad],experience:training}));await local(new SkillSession(initial,'reactive',undefined,{initialSkills:[good],experience:training}));}
 const choices={};for(const mode of ['off','record','use']){const exp=new ExperienceTable(mode);exp.load(training.export());const s=new SkillSession(initial,'reactive',undefined,{initialSkills:[bad,good],experience:exp});await s.step();choices[mode]=s.active.spec.id;s.cancel();}
 assert.equal(choices.off,'a-unproductive');assert.equal(choices.record,'a-unproductive');assert.equal(choices.use,'z-effective');
});
test('v03 experience version and weight change isolate statistics',()=>{const s=createWorld('guarded'),a=access();assert.notEqual(experienceKey(s,a),experienceKey(s,{...a,version:2}));assert.notEqual(experienceKey(s,a),experienceKey(s,{...a,weights:{...a.weights,progress:3}}));});
test('v03 experience storage validates malformed records',()=>{const st=storage(),t=new ExperienceTable('use',st);t.observe('x',{success:true,steps:2,energyDelta:-2,attacks:0,providerCalls:0,searchNodes:1});const u=new ExperienceTable('use',st);assert.equal(u.list()[0].n,1);assert.throws(()=>u.load({schema:'bad'}));u.load({schema:'gs/experience/v1',records:[{key:'bad',n:-1}]});assert.equal(u.list().length,1);});
test('v03 no fabricated optimistic score for unknown or single sample',()=>{const t=new ExperienceTable('use');assert.equal(t.preference('unknown',DEFAULT_WEIGHTS),0);t.observe('x',{success:true,steps:1,energyDelta:-1,attacks:0,providerCalls:0,searchNodes:0});assert.equal(t.preference('x',DEFAULT_WEIGHTS),0);});
test('v03 catalogue records local actual evidence without full-task requirement',async()=>{const c=new ReactiveCatalogue(),s=await local(new SkillSession(createWorld('guarded'),'reactive',undefined,{catalogue:c}));assert.equal(c.list()[0].status,'measured');assert.equal(c.list()[0].successes,1);assert.equal(s.world.snapshot().delivered,0);});
test('v03 mirror reuses same measured spec without G regeneration',async()=>{const c=new ReactiveCatalogue();const cold=await local(new SkillSession(createWorld('guarded'),'reactive',undefined,{catalogue:c}));const spec=c.list()[0].spec;const warm=await local(new SkillSession(createWorld('remix'),'reactive',undefined,{catalogue:c}));assert(warm.summaries[0].localSucceeded);assert.equal(warm.planning.searchRuns,0);assert.equal(warm.planning.skillHits,1);assert.equal(warm.summaries[0].skillId,spec.id);assert.deepEqual(c.list()[0].contexts,['guarded','remix']);});
test('v03 baseline day-to-day tasks do not artificially invoke G',async()=>{const s=await run(new SkillSession(createWorld('meadow')));assert.deepEqual(s.lastResult,{kind:'done',outcome:'succeeded'});assert.equal(s.planning.searchRuns,0);assert.equal(s.world.snapshot().turn,36);});
test('v03 complete orchard returns root success after several child goals',async()=>{const s=await run(new SkillSession(createWorld('guarded')));assert.deepEqual(s.lastResult,{kind:'done',outcome:'succeeded'});assert.equal(s.world.snapshot().turn,85);assert.equal(s.planning.searchRuns,1);assert.equal(s.summaries.filter(x=>x.rootSucceeded).length,1);assert.equal(s.lease.activeOwner,null);assert(s.summaries.length>1);});
test('v03 physical budget equals actual actions, not parent meta-dispatch count',async()=>{const s=await local(new SkillSession(createWorld('guarded'),'reactive',undefined,{initialSkills:[access()]}));assert.equal(s.budget.snapshot().used.actions,s.world.snapshot().turn);assert(s.budget.snapshot().used.cycles>s.budget.snapshot().used.actions);});
test('v03 export contains both engine streams and distinct local/root evidence',async()=>{const s=await local(new SkillSession(createWorld('guarded'),'reactive',undefined,{initialSkills:[access()]}));const t=s.export();assert.equal(t.format,'tuanzi-gs-trace/v3');assert(t.events.some(e=>e.type==='parent_event'));assert(t.events.some(e=>e.type==='child_event'));assert(t.hierarchy.summaries[0].localSucceeded);assert.equal(t.hierarchy.summaries[0].rootSucceeded,false);assert.equal(t.hierarchy.providers.length,0);});

test('v03 applied receipt with missing physical effect cannot earn skill success',async()=>{const s=new SkillSession(createWorld('guarded'),'reactive',undefined,{initialSkills:[access()]});await s.step();s.active.domain.physical.execute=async()=>({status:'applied',detail:'dishonest fixture'});await s.step();assert(s.finished);assert.equal(s.summaries[0].localSucceeded,false);assert.equal(s.experience.list().length,0);});
test('v03 same skill ID/version cannot silently change behaviour',()=>{const c=new ReactiveCatalogue(),s=access();c.trial(s);assert.throws(()=>c.trial({...s,weights:{...s.weights,cost:2}}),/identity/);});
test('v03 provider observes measured history only when consumption enabled',async()=>{const initial=createWorld('guarded'),spec=access(),key=experienceKey(initial,spec),outcome={success:true,steps:9,energyDelta:-9,attacks:0,providerCalls:0,searchNodes:10};
 for(const mode of ['record','use']){const e=new ExperienceTable(mode);e.observe(key,outcome);e.observe(key,outcome);let input;
 const s=new SkillSession(initial,'reactive-jev',undefined,{initialSkills:[spec],experience:e,providers:{select:async q=>{input??=q;return {output:judgment(q.candidates,q.candidates[0].id)};}}});await s.step();assert.equal(Boolean(input.candidates[0].evidence),mode==='use');s.cancel();}
});
