/** Cold-start lifecycle tests; synthetic G/S callbacks are NOT solver evidence. */
import test from 'node:test';import assert from 'node:assert/strict';
import {AutonomousSession,INITIAL_REVIEW_CAUSE} from '../dist/src/adaptive/session.js';
import {LabRun,ExperimentManager} from '../dist/src/lab/manager.js';
import {parseConfig} from '../dist/src/lab/types.js';
import {generationHistory,generationPurpose} from '../dist/src/lab/generation.js';
import {statusCopy,keyEvents,flowOf,replayStates} from '../dist/src/lab/presentation.js';
import {generatorMessages} from '../server/adaptive.mjs';
import {subproblem,analysis} from './fixtures/adaptive-v054.mjs';
import {tiny,program,proposal,generator,backend,chooseDeposit} from './fixtures/adaptive-v05.mjs';
const waitProgram=()=>program('显式夹具：保持等待以检查启动顺序',['wait'],{until:[{kind:'delta',field:'turn',atLeast:24}],maxActions:24});
const choose=f=>f.kind==='reframe'?f.options[0]?.id??null:f.options.find(o=>o.id==='wait')?.id??chooseDeposit(f);
const make=(g=generator(),b=backend(chooseDeposit),extra={},world=tiny())=>new AutonomousSession(world,{backend:b,generator:g,strategy:'direct',orderSeed:441,...extra});
const actor={id:'agent:init053',kind:'agent',label:'MOCK startup tests only'};
const config=(extra={})=>parseConfig({kind:'game',controller:'adaptive',backend:'jev',generator:'llm',allowLive:true,maxRequests:30,deadlineMs:15000,...extra});
const deferred=()=>{let resolve;const promise=new Promise(r=>resolve=r);return {promise,resolve};};
const command=(r,action,id=crypto.randomUUID())=>r.command({actor,action,commandId:id,expectedControlVersion:r.controlVersion});
const provider=(g,b)=>({ready:()=>true,backend:()=>b,adapt:g.propose.bind(g),adaptSource:{id:'MOCK_G_INIT',kind:'mock'}});

test('053 construction, inspection and export are side-effect free',()=>{const g=generator(),b=backend(chooseDeposit),s=make(g,b);s.inspect();s.export();s.memory();assert.equal(g.calls.length,0);assert.equal(b.calls.length,0);assert.equal(s.diagnostics().initialization.status,'pending');assert.equal(s.world.snapshot().turn,0);});
test('053 first actual model role is G, then physical S without approval',async()=>{const order=[],g=generator(i=>{order.push('G');assert.equal(i.cause,INITIAL_REVIEW_CAUSE);return proposal();}),b=backend(f=>{order.push(f.kind==='reframe'?'metaS':'actionS');return chooseDeposit(f);}),s=make(g,b);await s.step();assert.deepEqual(order,['G','actionS']);assert.equal(s.world.snapshot().turn,1);assert.equal(s.lastResult.outcome,'succeeded');assert.equal(s.diagnostics().initialization.reviewCount,1);assert.equal(s.diagnostics().initialization.status,'ready');});
test('053 startup G sees permitted initial world, not invented past failure',async()=>{const g=generator(),s=make(g);await s.step();const r=g.calls[0];assert.equal(r.answer,null);assert.deepEqual(r.previous,[]);assert.deepEqual(r.evidence.measuredHistory,[]);assert.deepEqual(r.evidence.selectorHistory,[]);assert.equal(r.evidence.previousIssue,null);assert.equal(r.evidence.observedWorld.turn,0);assert.equal(r.evidence.initialization.actionSelectorHasRun,false);assert.equal(r.evidence.initialization.frameRole,'unexecuted-action-frame-draft');assert.ok(!r.frame.context.observation.objects);});
test('053 initial G uses latest world after prestart edits',async()=>{const g=generator(),s=make(g);s.edit('wall',{x:0,y:0});await s.step();assert.equal(g.calls[0].evidence.observedWorld.revision,2);assert.deepEqual(g.calls[0].evidence.observedWorld.walls,[{x:0,y:0}]);assert.equal(g.calls[0].cause,INITIAL_REVIEW_CAUSE);});
test('053 G initial context/subset changes reach action S, which still has none',async()=>{const b=backend(chooseDeposit),g=generator(()=>proposal(program('仅比较当前交付',['deposit'],{groups:['self']}))),s=make(g,b);await s.step();const input=b.calls.find(i=>i.state.evidence.frame.kind==='action');assert.equal(input.state.evidence.frame.question,'仅比较当前交付');assert.deepEqual(input.state.evidence.frame.context.observation.visibleGroups,['self']);assert.equal(input.state.evidence.frame.options.length,1);assert.ok(Object.hasOwn(input.questions.choose.criteria,'none'));});
test('053 multiple steps do not repeat startup G',async()=>{const g=generator(()=>proposal(waitProgram())),s=make(g,backend(choose));for(let n=0;n<3;n++)await s.step();assert.equal(s.world.snapshot().turn,3);assert.equal(g.calls.length,1);assert.equal(s.events.filter(e=>e.type==='initialization_started').length,1);});
test('053 inherited own memory does not bypass initial environment review',async()=>{const g=generator(),memory={schema:'gs/self-memory/v05',informationPolicy:'no-reference/v05',records:[{program:waitProgram(),source:'mock',worldEvidence:'test',status:'trial',actualActions:0,deliveredDelta:0,attacks:0}]},s=make(g,backend(chooseDeposit),{memory,experience:'use'});await s.step();assert.equal(g.calls.length,1);assert.equal(g.calls[0].evidence.selfMemory.length,1);assert.equal(g.calls[0].cause,INITIAL_REVIEW_CAUSE);assert.equal(g.calls[0].evidence.selectorHistory.length,0);});
test('053 malformed initialization does not call any S or move',async()=>{const g=generator(()=>({wrong:1})),b=backend(chooseDeposit),s=make(g,b,{maxFormatRepairs:0});await s.step();assert.equal(s.lastResult.reason,'output_format_repair_exhausted');assert.equal(s.diagnostics().initialization.status,'failed');assert.equal(b.calls.length,0);assert.equal(s.world.snapshot().turn,0);});
test('053 initial output corrections share budgets and carry original startup cause',async()=>{const p=proposal(),g=generator((i,n)=>n===1?{actionFrame:p.proposals[0]}:p),s=make(g,backend(chooseDeposit),{maxFormatRepairs:1,maxGCalls:2,maxRevisions:1});await s.step();assert.equal(s.lastResult.outcome,'succeeded');assert.equal(s.diagnostics().gCalls,2);assert.equal(s.diagnostics().outputAccounting.formatRepairs,1);assert.equal(g.calls[1].originalCause,INITIAL_REVIEW_CAUSE);assert.equal(g.calls[1].evidence,undefined);assert.equal(s.diagnostics().initialization.reviewCount,1);});
test('053 initial physical S refusal does not fall back to a forced action',async()=>{const b=backend(()=>null),s=make(generator(),b,{maxDepth:1});await s.step();assert.equal(s.lastResult.reason,'adaptation_budget_exhausted');assert.ok(b.calls.every(i=>i.state.evidence.frame.kind==='action'));assert.equal(s.world.snapshot().turn,0);assert.equal(s.diagnostics().initialization.status,'ready');});
test('053 initial G failure remains a visible failure and no S fallback',async()=>{const b=backend(chooseDeposit),s=make(generator(()=>{throw Error('mock provider unavailable');}),b);await s.step();assert.equal(s.lastResult.kind,'fault');assert.equal(b.calls.length,0);assert.equal(s.diagnostics().initialization.reason,'mock provider unavailable');});
test('053 root G limit applies before initial provider call',async()=>{const g=generator(),b=backend(chooseDeposit),s=make(g,b,{maxGCalls:0});await s.step();assert.equal(g.calls.length,0);assert.equal(b.calls.length,0);assert.equal(s.lastResult.reason,'root_g_budget_exhausted');});
test('053 cancellation during initial G never marks it ready or writes world',async()=>{const entered=deferred(),gate=deferred(),g=generator(async()=>{entered.resolve();await gate.promise;return proposal();}),s=make(g);const step=s.step();await entered.promise;assert.equal(s.diagnostics().phase,'initializing');assert.equal(s.world.snapshot().turn,0);s.cancel();gate.resolve();await step;assert.equal(s.diagnostics().initialization.status,'failed');assert.equal(s.world.snapshot().turn,0);assert.equal(s.diagnostics().sCalls,0);});
test('053 stale startup G is discarded; new step re-reviews changed environment',async()=>{let s;const g=generator((i,n)=>{if(n===1)s.world.edit('wall',{x:0,y:0});return proposal();});s=make(g);await s.step();assert.equal(s.lastResult.kind,'stale');assert.equal(s.diagnostics().initialization.status,'pending');assert.equal(s.diagnostics().committedRevisions,undefined);assert.equal(s.diagnostics().outputAccounting.committedRevisions,0);await s.step();assert.equal(g.calls.length,2);assert.equal(g.calls[1].frame.revision,'2');assert.equal(g.calls[1].cause,INITIAL_REVIEW_CAUSE);assert.equal(s.world.snapshot().turn,1);assert.equal(s.diagnostics().initialization.reviewCount,2);});
test('053 stale first action judgment invalidates reviewed initial world before acting',async()=>{let s,changed=false;const g=generator(),b=backend(f=>{if(f.kind==='action'&&!changed){s.world.edit('wall',{x:0,y:0});changed=true;}return chooseDeposit(f);});s=make(g,b);await s.step();assert.equal(s.lastResult.kind,'stale');assert.equal(s.world.snapshot().turn,0);assert.equal(s.diagnostics().initialization.status,'pending');await s.step();assert.equal(g.calls.length,2);assert.equal(s.lastResult.outcome,'succeeded');});
for(const state of ['success','dead','limit'])test(`053 terminal starting world ${state} skips unnecessary model calls`,async()=>{const w=tiny();if(state==='success')w.delivered=5;else if(state==='dead')w.energy=0;else w.turn=w.maxTurns;const g=generator(),b=backend(chooseDeposit),s=make(g,b,{},w);await s.step();assert.equal(s.lastResult.kind,'done');assert.equal(s.diagnostics().initialization.status,'skipped-terminal');assert.equal(g.calls.length,0);assert.equal(b.calls.length,0);});
test('053 initial G prompt describes unexecuted draft and retains no-answer boundary',async()=>{const g=generator(),s=make(g);await s.step();const msgs=generatorMessages(g.calls[0]),text=msgs[0].content;assert.match(text,/before any action-level S call/);assert.match(text,/unexecuted draft/);assert.match(text,/No complete route or guaranteed strategy/);assert.ok(!text.includes('place-resource'));assert.ok(!text.includes('wait-access'));});
test('053 startup state allowlist removes poisoned scenario/prose/reference extras',async()=>{const w=tiny();w.scenario='SECRET_START_HINT';w.lastFact='SECRET_START_ANSWER';w.optimalRoute=['SECRET_ROUTE'];const g=generator(),s=make(g,backend(chooseDeposit),{},w);await s.step();assert.ok(!JSON.stringify(g.calls).includes('SECRET_'));assert.equal(g.calls[0].evidence.informationPolicy,'no-reference/v05');});

test('053 hosted create/read/subscribe does not bill, step first charges G with initialization purpose',async()=>{const g=generator(()=>proposal(waitProgram())),b=backend(choose),r=new LabRun(config(),actor,provider(g,b),tiny());try{r.view();r.export();const off=r.subscribe(()=>{});off();assert.equal(r.ledger.requests,0);await command(r,'step');assert.equal(r.ledger.rows[0].purpose,'initialization');assert.equal(r.ledger.rows.length,2);assert.equal(r.view().physicalActions,1);assert.equal(r.view().diagnostics.initialization.status,'ready');const gs=generationHistory(r.events);assert.equal(gs[0].cause,INITIAL_REVIEW_CAUSE);assert.equal(generationPurpose(gs[0]),'开局环境研判');}finally{r.cancel?.();if(!r.terminal)await command(r,'cancel');}});
test('053 pause/resume and command replay do not repeat startup G',async()=>{const g=generator(()=>proposal(waitProgram())),r=new LabRun(config(),actor,provider(g,backend(choose)),tiny());try{const c={actor,action:'step',commandId:'same-start-step',expectedControlVersion:0};await r.command(c);assert.equal(r.status,'paused');await r.command(c);r.view();r.export();await command(r,'step');assert.equal(r.view().physicalActions,2);assert.equal(g.calls.length,1);assert.equal(r.events.filter(e=>e.type==='engine'&&e.data.event.type==='initialization_started').length,1);}finally{if(!r.terminal)await command(r,'cancel');}});
test('053 maxRequests includes initialization and physical selection',async()=>{const g=generator(),b=backend(chooseDeposit),r=new LabRun(config({maxRequests:1}),actor,provider(g,b),tiny());await command(r,'step');assert.equal(r.ledger.requests,1);assert.equal(r.ledger.rows[0].purpose,'initialization');assert.equal(r.view().physicalActions,0);assert.match(r.reason,/budget/);});
test('053 UI shows startup rather than failure, history and replay stay read-only',async()=>{const gate=deferred(),entered=deferred(),g=generator(async()=>{entered.resolve();await gate.promise;return proposal();}),r=new LabRun(config(),actor,provider(g,backend(chooseDeposit)),tiny());const step=command(r,'step');await entered.promise;assert.equal(statusCopy(r.view()).title,'G 正在了解初始环境');assert.equal(r.view().physicalActions,0);assert.ok(keyEvents(r.events).some(e=>e.title==='开始开局环境研判'));assert.equal(g.calls.length,1);gate.resolve();await step;const ex=r.export(),frames=replayStates(ex);const past=frames.find(f=>f.diagnostics?.initialization?.status==='reviewing');assert.ok(past);assert.equal(past.physicalActions,0);assert.equal(generationHistory(ex.events,past.lastSeq).some(x=>x.status==='complete'),false);assert.equal(g.calls.length,1);});
test('053 old generation history with no purpose remains readable',()=>{assert.equal(generationPurpose({cause:'selector_abstained'}),'策略生成');assert.equal(generationPurpose({cause:'output_format_invalid'}),'格式纠错');assert.equal(generationPurpose({cause:INITIAL_REVIEW_CAUSE}),'开局环境研判');});
test('053 new experiment capabilities explicitly describe mandatory initialization',()=>{const m=new ExperimentManager();try{assert.match(m.capabilities().semantics.initialization,/before action-level S/);assert.equal(m.capabilities().version,'0.5.5');}finally{m.close();}});

test('053 G may affirm unchanged initial conditions once, not repeatedly earn new revisions',async()=>{const g=generator(i=>proposal(i.evidence.currentProgram)),s=make(g,backend(chooseDeposit));await s.step();assert.equal(s.lastResult.outcome,'succeeded');assert.equal(g.calls.length,1);assert.equal(s.diagnostics().initialization.status,'ready');});

test('053 a checkpoint fork with inherited own memory performs its own G review',async()=>{const g=generator(()=>proposal(waitProgram())),providers={...provider(g,backend(choose)),backend:()=>backend(choose)},m=new ExperimentManager(providers);try{const parent=new LabRun(config(),actor,providers,tiny());m.runs.set(parent.runId,parent);await command(parent,'step');const cp=await command(parent,'checkpoint');const n=g.calls.length;const childView=await m.fork(parent.runId,{requestId:'init-fork',actor,checkpointId:cp.checkpointId,memory:'inherit',config:{allowLive:true,maxRequests:30}});assert.equal(childView.requests,0);assert.equal(g.calls.length,n);const child=m.get(childView.runId);await command(child,'step');assert.equal(g.calls.length,n+1);assert.equal(g.calls.at(-1).cause,INITIAL_REVIEW_CAUSE);assert.equal(g.calls.at(-1).evidence.observedWorld.turn,1);assert.equal(g.calls.at(-1).evidence.measuredHistory.length,0);assert.equal(g.calls.at(-1).evidence.selectorHistory.length,0);assert.ok(g.calls.at(-1).evidence.selfMemory.length>0);assert.equal(parent.view().physicalActions,1);assert.equal(child.view().physicalActions,1);}finally{m.close();}});
test('053 continuous start initializes once and respects action cap',async()=>{const g=generator(()=>proposal(waitProgram())),r=new LabRun(config({maxActions:1}),actor,provider(g,backend(choose)),tiny());try{await command(r,'start');for(let i=0;i<100&&!r.terminal;i++)await new Promise(resolve=>setTimeout(resolve,5));assert.equal(g.calls.length,1);assert.equal(r.view().physicalActions,1);assert.equal(r.terminal,true);}finally{if(!r.terminal)await command(r,'cancel');}});
test('053 pause while initial G streams stops after one quantum; resume does not bootstrap again',async()=>{const entered=deferred(),gate=deferred(),g=generator(async()=>{entered.resolve();await gate.promise;return proposal(waitProgram());}),r=new LabRun(config(),actor,provider(g,backend(choose)),tiny());try{const step=command(r,'step');await entered.promise;await command(r,'pause');assert.equal(r.status,'pausing');assert.equal(r.view().physicalActions,0);gate.resolve();await step;assert.equal(r.status,'paused');assert.equal(r.view().physicalActions,1);await command(r,'step');assert.equal(g.calls.length,1);assert.equal(r.view().physicalActions,2);}finally{gate.resolve();if(!r.terminal)await command(r,'cancel');}});
test('053 an action-zero configured intervention is applied before G initial observation',async()=>{const g=generator(()=>proposal(waitProgram())),r=new LabRun(config({interventions:[{afterAction:0,tool:'wall',point:{x:0,y:0}}]}),actor,provider(g,backend(choose)),tiny());try{assert.equal(g.calls.length,0);await command(r,'step');assert.ok(g.calls[0].evidence.observedWorld.walls.some(w=>w.x===0&&w.y===0));assert.equal(g.calls[0].frame.revision,'2');assert.equal(g.calls[0].cause,INITIAL_REVIEW_CAUSE);}finally{if(!r.terminal)await command(r,'cancel');}});
test('v054 startup explicit child returns before physical action without approval gates',async()=>{const b=backend(f=>f.kind==='analysis'?f.options[0].id:chooseDeposit(f)),g=generator(i=>i.frame.kind==='analysis'?analysis():i.cause==='subproblem_completed'?proposal():subproblem()),s=make(g,b);await s.step();assert.equal(s.lastResult.outcome,'succeeded');assert.equal(g.calls[0].cause,INITIAL_REVIEW_CAUSE);assert.equal(g.calls[1].depth,1);assert.equal(g.calls[2].depth,0);assert.equal(s.diagnostics().initialization.reviewCount,1);assert.equal(s.events.filter(e=>e.type==='initialization_ready').length,1);assert.equal(s.world.snapshot().turn,1);});
test('053 judging fixtures are not mislabeled as requiring startup G',()=>{const r=new LabRun(parseConfig({kind:'judgment',backend:'rule',task:'energy'}),actor);assert.ok(!statusCopy(r.view()).body.includes('先由 G'));});
