import test from 'node:test';import assert from 'node:assert/strict';
import {judgmentRequest} from '../server/judgment.mjs';import {spawn} from 'node:child_process';import {setTimeout as delay} from 'node:timers/promises';
const env={TYPESAFE_API_KEY:'fixture-secret',JEV_MODEL:'jev-fixture',LLM_API_KEY:'fixture-secret',LLM_MODEL:'llm-fixture',LLM_URL:'http://127.0.0.1:9999/chat'};
const input={backend:'jev',state:{evidence:{facts:1},dependencyAnswers:{}},questions:{suitable:{type:'noul',instructions:'Is it suitable?'},priority:{type:'score',instructions:'Priority?',criteria:['low','high']}}};
const response={model:'wire-fixture',usage:{input_tokens:9,output_tokens:0},answers:{suitable:{type:'noul',noul:.8},priority:{type:'score',score:1}}};
const opts=(fetcher,e=env)=>({env:e,signal:new AbortController().signal,charge:()=>{},fetcher});
test('04 HTTP bridge emits one official Jev request per batch',async()=>{let count=0,sent;const a=await judgmentRequest(input,{...opts(async(u,o)=>{assert.equal(u,'https://api.typesafe.ai/v1/systemone');sent=JSON.parse(o.body);return new Response(JSON.stringify(response));}),charge:()=>count++});assert.equal(count,1);assert.deepEqual(sent.questions,input.questions);assert.deepEqual(sent.state,input.state);assert(!JSON.stringify(sent).includes('fixture-secret'));assert.equal(a.model,'wire-fixture');assert.equal(a.usage.inputTokens,9);});
test('04 configured LLM judges same typed batch without hidden generator calls',async()=>{let sent;const a=await judgmentRequest({...input,backend:'llm'},opts(async(_u,o)=>{sent=JSON.parse(o.body);return new Response(JSON.stringify({model:'llm-wire',usage:{prompt_tokens:12,completion_tokens:8},choices:[{message:{content:JSON.stringify({answers:response.answers})}}]}));}));assert.equal(a.usage.inputTokens,12);assert.equal(JSON.parse(sent.messages[1].content).questions.priority.type,'score');});
test('04 no credentials reports not configured before a paid attempt',async()=>{let n=0;await assert.rejects(judgmentRequest(input,{...opts(async()=>{throw Error('must not request');},{}),charge:()=>n++}),/not configured/);assert.equal(n,0);});
test('04 invalid batch rejected before charge',async()=>{let n=0;await assert.rejects(judgmentRequest({...input,questions:{x:{type:'eval',instructions:'code'}}},{...opts(async()=>{}),charge:()=>n++}),/question/);assert.equal(n,0);});
test('04 provider errors make one attempt and never fall back',async()=>{let n=0;await assert.rejects(judgmentRequest(input,{...opts(async()=>new Response('error',{status:503})),charge:()=>n++}),/503/);assert.equal(n,1);});
test('04 non-HTTPS external LLM URL is disallowed',async()=>{await assert.rejects(judgmentRequest({...input,backend:'llm'},opts(async()=>{throw Error('must not send');},{...env,LLM_URL:'http://example.com/api'})),/HTTPS/);});
test('04 missing or extra answer IDs rejected',async()=>{await assert.rejects(judgmentRequest(input,opts(async()=>new Response(JSON.stringify({...response,answers:{suitable:{type:'noul',noul:1}}})))),/set mismatch/);});
test('04 provider unknown candidate is rejected',async()=>{const q={backend:'jev',state:{facts:1},questions:{c:{type:'choice',instructions:'Select',criteria:{a:'A',none:'Abstain'}}}};await assert.rejects(judgmentRequest(q,opts(async()=>new Response(JSON.stringify({answers:{c:{type:'choice',choice:'evil',confidence:1,probabilities:{a:0,none:1}}}})))),/unknown/);});
test('04 absent usage is left unknown rather than estimated as zero',async()=>{const a=await judgmentRequest(input,opts(async()=>new Response(JSON.stringify({model:'m',answers:response.answers}))));assert.equal(a.usage,undefined);});
test('04 oversized provider content rejected',async()=>{await assert.rejects(judgmentRequest(input,opts(async()=>new Response('x'.repeat(524300)))),/large/);});
test('04 live HTTP endpoint requires same-origin token and dispatches configured mock LLM',async()=>{
 const http=await import('node:http');const mock=http.createServer(async(req,res)=>{const chunks=[];for await(const x of req)chunks.push(x);const b=JSON.parse(Buffer.concat(chunks)),q=JSON.parse(b.messages[1].content).questions;res.writeHead(200,{'content-type':'application/json'});res.end(JSON.stringify({model:'mock-http04',usage:{prompt_tokens:7,completion_tokens:5},choices:[{message:{content:JSON.stringify({answers:Object.fromEntries(Object.entries(q).map(([id,x])=>[id,{type:x.type,noul:.8}]))})}}]}));});await new Promise(r=>mock.listen(0,'127.0.0.1',r));const port=4294;
 const child=spawn(process.execPath,['server.mjs'],{env:{...process.env,PORT:String(port),TYPESAFE_API_KEY:'',LLM_API_KEY:'fixture-secret',LLM_URL:`http://127.0.0.1:${mock.address().port}/chat`,LLM_MODEL:'mock-http04',GS_MAX_MODEL_CALLS:'4'},stdio:'ignore'});
 try{let status;for(let i=0;i<100;i++){try{const r=await fetch(`http://127.0.0.1:${port}/api/status`);status=await r.json();break;}catch{await delay(25);}}assert(status?.token);const base=`http://127.0.0.1:${port}`,query={backend:'llm',state:{evidence:{facts:1}},questions:{fit:{type:'noul',instructions:'Suitable?'}}};
  const no=await fetch(base+'/api/judgment',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(query)});assert.equal(no.status,403);
  const yes=await fetch(base+'/api/judgment',{method:'POST',headers:{'content-type':'application/json',origin:base,'x-gs-token':status.token},body:JSON.stringify(query)});assert.equal(yes.status,200,await yes.clone().text());const result=await yes.json();assert.equal(result.model,'mock-http04');assert.equal(result.answers.fit.noul,.8);assert.equal(result.usage.inputTokens,7);
 }finally{child.kill();await new Promise(r=>mock.close(r));}
});
test('04 bridge validation error preserves actual reported usage',async()=>{await assert.rejects(judgmentRequest(input,opts(async()=>new Response(JSON.stringify({...response,answers:{}})))),e=>e.status===502&&e.usage.inputTokens===9&&e.usage.model==='wire-fixture');});
