import test from 'node:test';import assert from 'node:assert/strict';import http from 'node:http';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {execFile,spawn} from 'node:child_process';import {promisify} from 'node:util';
import {ExperimentManager} from '../dist/src/lab/manager.js';import {createLabHandler} from '../server/lab/http.mjs';
const exec=promisify(execFile),actor={id:'agent:http',kind:'agent',label:'HTTP test'};
async function fixture(t){const manager=new ExperimentManager(),token='test-token-'+crypto.randomUUID(),dir=fs.mkdtempSync(path.join(os.tmpdir(),'gs-lab-'));let handler;
 const server=http.createServer(async(req,res)=>{if(req.url==='/api/status'){res.writeHead(200,{'content-type':'application/json'});res.end(JSON.stringify({token,jevReady:false,llmReady:false}));return;}const used=await handler(req,res,new URL(req.url,'http://127.0.0.1'));if(!used){res.writeHead(404);res.end();}});
 await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${server.address().port}`;handler=createLabHandler({manager,token,baseUrl:base,archiveDir:dir});
 t.after(async()=>{manager.close();server.closeAllConnections();await new Promise(r=>server.close(r));fs.rmSync(dir,{recursive:true,force:true});});
 const api=async(p,body,headers={})=>{const r=await fetch(base+p,{method:body?'POST':'GET',headers:{'x-gs-token':token,...(body?{'content-type':'application/json'}:{}),...headers},...(body?{body:JSON.stringify(body)}:{})});return {status:r.status,data:await r.json()};};
 const create=async(config={})=>(await api('/api/lab/runs',{requestId:crypto.randomUUID(),actor,config})).data;
 const cmd=async(s,action,extra={})=>api(`/api/lab/runs/${s.runId}/commands`,{commandId:crypto.randomUUID(),expectedControlVersion:s.controlVersion,actor,action,...extra});
 return {manager,token,base,dir,api,create,cmd};}
const pause=ms=>new Promise(r=>setTimeout(r,ms));
async function finish(f,s){await f.cmd(s,'start');let v;for(let i=0;i<300;i++){v=(await f.api(`/api/lab/runs/${s.runId}/result`)).data;if(v.complete)return v;await pause(5);}throw Error('run timeout');}
test('041 HTTP capabilities readable with token; secret never returned',async t=>{const f=await fixture(t),r=await f.api('/api/lab/capabilities');assert.equal(r.status,200);assert(!JSON.stringify(r.data).includes(f.token));assert.equal(r.data.backends.jev.ready,false);});
test('041 HTTP auth required on read and write',async t=>{const f=await fixture(t);for(const p of ['/api/lab/capabilities','/api/lab/runs']){const r=await fetch(f.base+p);assert.equal(r.status,401);assert.equal((await r.json()).error.code,'UNAUTHORIZED');}});
test('041 HTTP foreign Origin blocked even with token',async t=>{const f=await fixture(t);const r=await f.api('/api/lab/capabilities',undefined,{origin:'https://evil.example'});assert.equal(r.status,403);});
test('041 HTTP browser cross-site hint rejected',async t=>{const f=await fixture(t);assert.equal((await f.api('/api/lab/capabilities',undefined,{'sec-fetch-site':'cross-site'})).status,403);});
test('041 HTTP JSON content type required',async t=>{const f=await fixture(t),r=await fetch(f.base+'/api/lab/runs',{method:'POST',headers:{'x-gs-token':f.token},body:'{}'});assert.equal(r.status,415);});
test('041 HTTP invalid JSON structured error',async t=>{const f=await fixture(t),r=await fetch(f.base+'/api/lab/runs',{method:'POST',headers:{'x-gs-token':f.token,'content-type':'application/json'},body:'{broken'});assert.equal(r.status,400);assert.equal((await r.json()).error.code,'INVALID_JSON');});
test('041 HTTP oversized control body rejected',async t=>{const f=await fixture(t),r=await fetch(f.base+'/api/lab/runs',{method:'POST',headers:{'x-gs-token':f.token,'content-type':'application/json'},body:JSON.stringify({text:'x'.repeat(70000)})});assert.equal(r.status,413);});
test('041 HTTP create returns common viewer and status identity',async t=>{const f=await fixture(t),s=await f.create(),read=(await f.api('/api/lab/runs/'+s.runId)).data;assert.equal(read.runId,s.runId);assert.equal(s.viewerUrl,f.base+'/lab?run='+s.runId);assert.deepEqual(read.world,s.world);});
test('041 HTTP experiment listing includes complete known runs',async t=>{const f=await fixture(t);await f.create();await f.create();const r=await f.api('/api/lab/runs');assert.equal(r.data.runs.length,2);assert.equal(r.data.complete,true);});
test('041 HTTP version conflict returns 409 without state mutation',async t=>{const f=await fixture(t),s=await f.create();await f.cmd(s,'step');const r=await f.cmd(s,'step');assert.equal(r.status,409);assert.equal(r.data.error.code,'STALE_CONTROL');});
test('041 HTTP idempotent step after response loss does not execute again',async t=>{const f=await fixture(t),s=await f.create(),body={commandId:'retry',expectedControlVersion:0,actor,action:'step'};const p=`/api/lab/runs/${s.runId}/commands`;const a=await f.api(p,body),b=await f.api(p,body);assert.equal(a.data.state.physicalActions,1);assert.equal(b.data.state.physicalActions,1);assert.equal(b.data.replayed,true);});
test('041 HTTP pagination returns no omissions or duplicates',async t=>{const f=await fixture(t),s=await f.create();await finish(f,s);const events=[];let after=0;for(;;){const r=(await f.api(`/api/lab/runs/${s.runId}/events?after=${after}&limit=3`)).data;events.push(...r.events);after=r.nextCursor;if(!r.hasMore)break;}assert.deepEqual(events.map(e=>e.seq),f.manager.get(s.runId).events.map(e=>e.seq));});
test('041 HTTP future SSE cursor rejected before headers',async t=>{const f=await fixture(t),s=await f.create();const r=await fetch(`${f.base}/api/lab/runs/${s.runId}/stream?after=9999`,{headers:{'x-gs-token':f.token}});assert.equal(r.status,409);});
async function readEvents(reader,want){let buf='',result=[];for(let i=0;i<100;i++){const {value,done}=await reader.read();if(done)break;buf+=new TextDecoder().decode(value);let p;while((p=buf.indexOf('\n\n'))>=0){const block=buf.slice(0,p);buf=buf.slice(p+2);const line=block.split('\n').find(l=>l.startsWith('data: '));if(line){result.push(JSON.parse(line.slice(6)));if(want(result))return result;}}}return result;}
test('041 real HTTP SSE streams exact same run while CLI-style commands execute',async t=>{const f=await fixture(t),s=await f.create();const response=await fetch(`${f.base}/api/lab/runs/${s.runId}/stream?after=${s.lastSeq}`,{headers:{'x-gs-token':f.token},signal:AbortSignal.timeout(5000)});assert.match(response.headers.get('content-type'),/text\/event-stream/);const reader=response.body.getReader();const reading=readEvents(reader,es=>es.some(e=>e.type==='state'&&e.data.physicalActions===1));await f.cmd(s,'step');const events=await reading;assert(events.every(e=>e.runId===s.runId&&e.seq>s.lastSeq));const live=events.find(e=>e.type==='state'&&e.data.physicalActions===1).data;const current=(await f.api('/api/lab/runs/'+s.runId)).data;assert.deepEqual(live.world,current.world);await reader.cancel();});
test('041 SSE Last-Event-ID replay honors cursor and disconnect does not cancel',async t=>{const f=await fixture(t),s=await f.create();const done=await finish(f,s),all=f.manager.get(s.runId).events,after=all.at(-3).seq;const res=await fetch(`${f.base}/api/lab/runs/${s.runId}/stream?after=0`,{headers:{'x-gs-token':f.token,'last-event-id':String(after)},signal:AbortSignal.timeout(5000)});const reader=res.body.getReader();const events=await readEvents(reader,es=>es.some(e=>e.seq===all.at(-1).seq));assert.deepEqual(events.map(e=>e.seq),all.filter(e=>e.seq>after).map(e=>e.seq));await reader.cancel();assert.equal(f.manager.get(s.runId).status,'succeeded');});
test('041 completed report archived and export matches API result',async t=>{const f=await fixture(t),s=await f.create();const r=await finish(f,s),e=(await f.api(`/api/lab/runs/${s.runId}/export`)).data;const disk=JSON.parse(fs.readFileSync(path.join(f.dir,s.runId+'.json'),'utf8'));assert.equal(disk.state.status,'succeeded');assert.deepEqual(e.state.world,r.state.world);assert(!JSON.stringify(e).includes(f.token));});
test('041 CLI create/status/step/start/result/export control the HTTP run',async t=>{const f=await fixture(t);const cli=async(...args)=>{const r=await exec(process.execPath,['bin/gs-lab.mjs',...args,'--url',f.base,'--actor',actor.id],{cwd:process.cwd()});return JSON.parse(r.stdout);};const s=await cli('create','--task','energy');assert(f.manager.runs.has(s.runId));const step=await cli('step',s.runId);assert.equal(step.state.physicalActions,1);const r=await cli('start',s.runId,'--wait');assert.equal(r.state.status,'succeeded');const out=path.join(f.dir,'cli-export.json');await cli('export',s.runId,'--out',out);assert.equal(JSON.parse(fs.readFileSync(out,'utf8')).state.runId,s.runId);});
test('041 CLI conflict has nonzero exit and machine-readable error',async t=>{const f=await fixture(t),s=await f.create();await f.cmd(s,'step');try{await exec(process.execPath,['bin/gs-lab.mjs','step',s.runId,'--if-version','0','--actor',actor.id,'--url',f.base]);assert.fail();}catch(e){assert.equal(e.code,2);assert.equal(JSON.parse(e.stderr).error.code,'STALE_CONTROL');}});
test('041 CLI refuses nonlocal destination before token bootstrap',async()=>{try{await exec(process.execPath,['bin/gs-lab.mjs','list','--url','http://example.com']);assert.fail();}catch(e){assert.equal(JSON.parse(e.stderr).error.code,'LOCAL_ONLY');}});
test('041 external Agent example runs four independent experiments on same service',async t=>{const f=await fixture(t);const r=await exec(process.execPath,['examples/agent/compare.mjs'],{env:{...process.env,GS_LAB_URL:f.base},timeout:30000});const v=JSON.parse(r.stdout);assert.equal(v.rows.length,4);assert(v.rows.every(r=>r.status==='succeeded'&&r.external===0));assert.equal(v.rows[1].requests,2);assert.equal(v.rows[2].requests,50);});
test('041 complete server hosts viewer assets and real CLI-to-mock-LLM experiment',async t=>{
 const {ruleBackend}=await import('../dist/src/decision/pipeline.js');const {missionAssessment}=await import('../dist/src/decision/experiment.js');let mockCalls=0;
 const mock=http.createServer(async(req,res)=>{let body='';for await(const c of req)body+=c;const parsed=JSON.parse(body),input=JSON.parse(parsed.messages.at(-1).content);mockCalls++;const a=await ruleBackend(missionAssessment).ask(input,new AbortController().signal);res.writeHead(200,{'content-type':'application/json'});res.end(JSON.stringify({model:'protocol-fixture-only',usage:{prompt_tokens:12,completion_tokens:8},choices:[{message:{content:JSON.stringify({answers:a.answers})}}]}));});
 await new Promise(r=>mock.listen(0,'127.0.0.1',r));
 const reserve=http.createServer();await new Promise(r=>reserve.listen(0,'127.0.0.1',r));const port=reserve.address().port;await new Promise(r=>reserve.close(r));
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'gs-full-server-'));const proc=spawn(process.execPath,['server.mjs'],{env:{...process.env,PORT:String(port),TYPESAFE_API_KEY:'',LLM_API_KEY:'fake-local-test-key',LLM_MODEL:'protocol-fixture-only',LLM_URL:`http://127.0.0.1:${mock.address().port}/chat`,GS_LAB_OUTPUT_DIR:dir,MAX_SERVER_CALLS:'4'},stdio:'ignore'});
 t.after(async()=>{proc.kill('SIGTERM');await new Promise(r=>setTimeout(r,100));mock.closeAllConnections();await new Promise(r=>mock.close(r));fs.rmSync(dir,{recursive:true,force:true});});
 const base=`http://127.0.0.1:${port}`;let status;for(let i=0;i<100;i++){try{const r=await fetch(base+'/api/status');if(r.ok){status=await r.json();break;}}catch{}await pause(20);}assert(status?.token);
 for(const asset of ['/lab','/lab.js','/lab.css','/','/app.js'])assert.equal((await fetch(base+asset)).status,200);
 const cli=async(...args)=>JSON.parse((await exec(process.execPath,['bin/gs-lab.mjs',...args,'--url',base],{timeout:15000})).stdout);
 const s=await cli('--json','create','--task','energy','--backend','llm','--allow-live','--max-requests','4');const r=await cli('start',s.runId,'--wait');assert.equal(r.state.status,'succeeded');assert.equal(r.state.externalRequests,2);assert.equal(mockCalls,2);assert.equal(r.ledger.rows[0].usage.model,'protocol-fixture-only');assert(!JSON.stringify(r).includes('fake-local-test-key'));assert.equal((await (await fetch(base+'/api/status')).json()).providerCalls,2);
 const cross=await fetch(base+'/api/status',{headers:{origin:'https://cross.example'}});assert.equal(cross.status,403);
});
test('041 CLI malformed URL returns structured error before network access',async()=>{try{await exec(process.execPath,['bin/gs-lab.mjs','list','--url',':::invalid']);assert.fail();}catch(e){assert.equal(e.code,2);assert.equal(JSON.parse(e.stderr).error.code,'INVALID_URL');}});
