import test from 'node:test';import assert from 'node:assert/strict';import {spawn} from 'node:child_process';import {once} from 'node:events';
function client(args=[]){const proc=spawn(process.execPath,['bin/gs-lab-mcp.mjs',...args],{cwd:process.cwd(),stdio:['pipe','pipe','pipe']});const waiters=new Map(),unexpected=[],errors=[];let text='',sequence=0,stderr='';proc.stderr.on('data',x=>stderr+=x);proc.stdout.on('data',chunk=>{text+=chunk;for(;;){const i=text.indexOf('\n');if(i<0)break;const line=text.slice(0,i);text=text.slice(i+1);try{const r=JSON.parse(line),w=waiters.get(r.id);if(w){waiters.delete(r.id);clearTimeout(w.timer);w.resolve(r);}else unexpected.push(r);}catch(e){errors.push({line,error:String(e)});}}});return {proc,unexpected,errors,stderr:()=>stderr,write:s=>proc.stdin.write(s),notify:(method,params)=>proc.stdin.write(JSON.stringify({jsonrpc:'2.0',method,params})+'\n'),call:(method,params={})=>{const id=++sequence;return new Promise((resolve,reject)=>{const timer=setTimeout(()=>{waiters.delete(id);reject(Error('MCP response timeout'));},8000);waiters.set(id,{resolve,timer});proc.stdin.write(JSON.stringify({jsonrpc:'2.0',id,method,params})+'\n');});},close:async()=>{proc.stdin.end();await Promise.race([once(proc,'exit'),new Promise(r=>setTimeout(r,1000))]);if(proc.exitCode===null)proc.kill();}};}
async function init(c,version='2025-11-25'){const r=await c.call('initialize',{protocolVersion:version,clientInfo:{name:'gs-wire-test',version:'1'},capabilities:{}});c.notify('notifications/initialized');return r;}
test('055 real stdio lifecycle, tools, resource templates and a project read',async()=>{const c=client();try{const i=await init(c);assert.equal(i.result.protocolVersion,'2025-11-25');assert.equal(i.result.serverInfo.version,'0.5.5');const tools=await c.call('tools/list');assert.ok(tools.result.tools.find(t=>t.name==='lab_read'));assert.ok(!tools.result.tools.find(t=>t.name==='lab_command'));const p=await c.call('tools/call',{name:'project_info'});assert.equal(p.result.structuredContent.version,'0.5.5');assert.equal(p.result.isError,false);const resources=await c.call('resources/list');assert.ok(resources.result.resources.find(r=>r.uri==='gs://project/overview'));const r=await c.call('resources/read',{uri:'gs://project/overview'});assert.equal(JSON.parse(r.result.contents[0].text).profile,'operator');assert.equal((await c.call('resources/templates/list')).result.resourceTemplates.length,3);assert.equal(c.errors.length,0);assert.equal(c.stderr(),'');}finally{await c.close();}});
for(const version of ['2024-11-05','2025-03-26','2025-06-18'])test('055 negotiates supported MCP protocol '+version,async()=>{const c=client();try{assert.equal((await init(c,version)).result.protocolVersion,version);}finally{await c.close();}});
test('055 unsupported protocol offers supported latest version',async()=>{const c=client();try{assert.equal((await init(c,'unknown')).result.protocolVersion,'2025-11-25');}finally{await c.close();}});
test('055 before-initialize requests rejected; notifications produce no response',async()=>{const c=client();try{assert.ok((await c.call('tools/list')).error);await init(c);c.notify('notifications/unknown');assert.deepEqual((await c.call('ping')).result,{});assert.equal(c.unexpected.length,0);}finally{await c.close();}});
test('055 tool failure uses isError; unknown method uses JSON-RPC error',async()=>{const c=client();try{await init(c);const e=await c.call('tools/call',{name:'project_read',arguments:{path:'.env'}});assert.equal(e.result.isError,true);assert.match(e.result.content[0].text,/PATH_FORBIDDEN/);assert.equal((await c.call('not/a/method')).error.code,-32601);assert.equal((await c.call('tools/list',{cursor:'no'})).error.code,-32602);}finally{await c.close();}});
test('055 malformed JSON yields parse error and subsequent requests work',async()=>{const c=client();try{c.write('{not json}\n');await init(c);await c.call('ping');assert.ok(c.unexpected.some(x=>x.error?.code===-32700));assert.equal(c.errors.length,0);}finally{await c.close();}});
test('055 control tools only advertised with explicit launch permission',async()=>{const c=client(['--allow-control']);try{await init(c);assert.ok((await c.call('tools/list')).result.tools.find(t=>t.name==='lab_command'));assert.ok((await c.call('tools/list')).result.tools.every(t=>t.inputSchema.type==='object'));}finally{await c.close();}});
test('055 prompts are discoverable, do not execute an experiment',async()=>{const c=client();try{await init(c);const p=await c.call('prompts/list');assert.equal(p.result.prompts.length,2);const r=await c.call('prompts/get',{name:'inspect-run',arguments:{runId:'run-test'}});assert.match(r.result.messages[0].content.text,/do not modify/);}finally{await c.close();}});
test('055 read project works while lab service is unavailable',async()=>{const c=client(['--url','http://127.0.0.1:1']);try{await init(c);assert.equal((await c.call('tools/call',{name:'project_info'})).result.isError,false);assert.equal((await c.call('tools/call',{name:'lab_capabilities'})).result.isError,true);}finally{await c.close();}});
