import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import path from 'node:path';import os from 'node:os';
import {ProjectAccess,loopback,chunk,pointer,redact} from '../server/mcp/access.mjs';import {McpService,validateArgs} from '../server/mcp/service.mjs';
let root,operator,audit;
test.before(async()=>{root=await fs.mkdtemp(path.join(os.tmpdir(),'gs-mcp-test-'));await fs.mkdir(path.join(root,'docs'));await fs.mkdir(path.join(root,'tests'));await fs.mkdir(path.join(root,'src/adaptive'),{recursive:true});await fs.mkdir(path.join(root,'.gs-lab/exports'),{recursive:true});await fs.writeFile(path.join(root,'AGENTS.md'),'Operator instructions\n'.repeat(30));await fs.writeFile(path.join(root,'src/adaptive/session.ts'),'// autonomous\n');await fs.writeFile(path.join(root,'tests/reference.txt'),'THIS_IS_A_REFERENCE_ANSWER');await fs.writeFile(path.join(root,'.env'),'TYPESAFE_API_KEY=DO_NOT_READ');await fs.symlink(path.join(root,'.env'),path.join(root,'src/adaptive/link.ts'));operator=new ProjectAccess(root);audit=new ProjectAccess(root,'audit');});
test.after(()=>fs.rm(root,{recursive:true,force:true}));
test('055 MCP project index lists operational files, hides reference and secrets',async()=>{const p=await operator.list();assert.ok(p.files.some(f=>f.path==='src/adaptive/session.ts'));assert.ok(!p.files.some(f=>f.path.includes('tests')||f.path.includes('env')||f.path.includes('link')));});
test('055 MCP audit index can inspect reference sources but never keys',async()=>{const p=await audit.list();assert.ok(p.files.some(f=>f.path==='tests/reference.txt'));assert.equal((await audit.read({path:'tests/reference.txt'})).text,'THIS_IS_A_REFERENCE_ANSWER');await assert.rejects(audit.read({path:'.env'}),/profile|sensitive/);});
for(const rel of ['../outside','/etc/passwd','src/../../.env','src\\..\\.env','src/adaptive/link.ts','src//adaptive/session.ts'])test('055 rejects unsafe file '+rel,async()=>{await assert.rejects(audit.read({path:rel}));});
test('055 text paging has digest and no silent truncation',async()=>{const p=await operator.read({path:'AGENTS.md',limit:12});assert.equal(p.nextOffset,12);const next=await operator.read({path:'AGENTS.md',offset:12,limit:12,expectedHash:p.sha256});assert.equal(next.offset,12);await fs.appendFile(path.join(root,'AGENTS.md'),'new');await assert.rejects(operator.read({path:'AGENTS.md',expectedHash:p.sha256}),/changed/);});
test('055 literal search scopes are explicit',async()=>{const r=await operator.search({query:'autonomous',prefix:'src/'});assert.equal(r.matches.length,1);assert.equal(r.matches[0].line,1);assert.equal((await operator.search({query:'THIS_IS_A_REFERENCE'})).matches.length,0);});
test('055 JSON pointer and chunks preserve paging, forbid prototype traversal',()=>{assert.equal(pointer({'a/b':{'~x':7}},'/a~1b/~0x'),7);assert.throws(()=>pointer({},'/__proto__'));assert.throws(()=>pointer({},'/a~2'));const c=chunk({a:'x'.repeat(40)},{pointer:'/a',limit:5});assert.equal(c.nextOffset,5);assert.throws(()=>chunk({a:'changed'},{pointer:'/a',expectedHash:c.sha256}),/changed/);});
test('055 returned data redacts known secret-bearing fields and bearer tokens',()=>{const r=redact({token:'x',LLM_API_KEY:'y',output:'Bearer abc-xyz',usage:{inputTokens:33}});assert.equal(r.token,'[REDACTED]');assert.equal(r.LLM_API_KEY,'[REDACTED]');assert.ok(!r.output.includes('abc'));assert.equal(r.usage.inputTokens,33);});
for(const url of ['https://localhost:4173','http://example.com','http://127.0.0.1.evil.test','http://user:pass@localhost','http://127.0.0.1/foo'])test('055 MCP blocks non-local or credentialed origin '+url,()=>assert.throws(()=>loopback(url)));
test('055 audit cannot enable mutation flags; default operator tools are read-only',()=>{assert.throws(()=>new McpService({root,profile:'audit',allowControl:true}),/read-only/);const m=new McpService({root});assert.ok(m.tools.every(t=>t.annotations.readOnlyHint));assert.ok(!m.tools.some(t=>t.name==='lab_command'));});
test('055 archive is read-only, available without lab, and reference lane filtered',async()=>{const data={schema:'gs/lab-export/v1',version:'0.5.5',state:{runId:'run-one',status:'failed',config:{kind:'game',controller:'adaptive'}}};await fs.writeFile(path.join(root,'.gs-lab/exports/run-one.json'),JSON.stringify(data));await fs.writeFile(path.join(root,'.gs-lab/exports/run-ref.json'),JSON.stringify({...data,state:{...data.state,config:{kind:'game',controller:'rules'}}}));assert.equal((await operator.archives()).total,1);assert.equal((await audit.archives()).total,2);assert.equal((await operator.archive('run-one.json')).state.runId,'run-one');await assert.rejects(operator.archive('run-ref.json'),/audit-only/);});
test('055 MCP validates tool argument types and extra fields',async()=>{const m=new McpService({root});await assert.rejects(m.call('project_read',{path:'AGENTS.md',shell:'cat .env'}),/Unknown field/);await assert.rejects(m.call('project_files',{offset:-1}),/range/);await assert.rejects(m.call('lab_create',{}),/not enabled/);});
test('055 MCP resources and templates read same bounded source',async()=>{const m=new McpService({root});const r=await m.readResource('gs://project/file/AGENTS.md?offset=0&limit=20');assert.equal(JSON.parse(r.contents[0].text).text.length,20);assert.ok(m.templates().length>=3);await assert.rejects(m.readResource('file:///etc/passwd'));await assert.rejects(m.readResource('gs://project/file/src%2F..%2F..%2F.env'));});

test('055 audit search skips oversized reports instead of aborting the entire query',async()=>{const p=path.join(root,'tests/large-report.json');await fs.writeFile(p,'x'.repeat(5*1024*1024));try{const r=await audit.search({query:'THIS_IS_A_REFERENCE',prefix:'tests/'});assert.equal(r.matches.length,1);assert.match(r.scope,/512KiB/);await assert.rejects(audit.read({path:'tests/large-report.json'}),/size cap/);}finally{await fs.rm(p);}});
