import test from 'node:test';import assert from 'node:assert/strict';import http from 'node:http';import fs from 'node:fs/promises';import os from 'node:os';import path from 'node:path';
import {ExperimentManager} from '../dist/src/lab/manager.js';import {createLabHandler} from '../server/lab/http.mjs';import {McpService} from '../server/mcp/service.mjs';
let root,manager,server,base,mcp,handler;
test.before(async()=>{root=await fs.mkdtemp(path.join(os.tmpdir(),'mcp-lab-integration-'));manager=new ExperimentManager();server=http.createServer(async(req,res)=>{if(req.url==='/api/status'){res.end(JSON.stringify({token:'LOCAL_CONTROL_SECRET'}));return;}if(await handler(req,res,new URL(req.url,base)))return;res.statusCode=404;res.end();});await new Promise(r=>server.listen(0,'127.0.0.1',r));base=`http://127.0.0.1:${server.address().port}`;handler=createLabHandler({manager,token:'LOCAL_CONTROL_SECRET',baseUrl:base,archiveDir:path.join(root,'.gs-lab/exports')});mcp=new McpService({root,baseUrl:base,allowControl:true});});
test.after(async()=>{manager.close();server.closeAllConnections();await new Promise(r=>server.close(r));await fs.rm(root,{recursive:true,force:true});});
async function create(requestId,config={}){return mcp.call('lab_create',{requestId,config:{kind:'game',controller:'adaptive',scenario:'meadow',backend:'rule',generator:'local',maxDepth:0,maxGCalls:2,deadlineMs:15000,...config}});}
test('055 MCP creates once, observes exact same run via HTTP, steps once with replay',async()=>{const a=await create('create-one'),b=await create('create-one');assert.equal(a.runId,b.runId);assert.equal(a.requests,0);assert.equal(a.status,'ready');assert.ok(a.viewerUrl.startsWith(base));const c={runId:a.runId,commandId:'one-step',expectedControlVersion:0,action:'step'};const first=await mcp.call('lab_command',c),second=await mcp.call('lab_command',c);assert.equal(first.state.physicalActions,1);assert.equal(second.replayed,true);const state=manager.get(a.runId).view();assert.equal(state.worldRevision,first.state.worldRevision);const snapshot=JSON.parse((await mcp.call('lab_snapshot',{runId:a.runId,pointer:'/world'})).text);assert.deepEqual(snapshot,state.world);assert.equal(JSON.parse((await mcp.call('lab_snapshot',{runId:a.runId,pointer:'/runId'})).text),state.runId);const events=await mcp.call('lab_events',{runId:a.runId});assert.ok(events.events.length);assert.equal(events.events[0].seq,1);const trace=await mcp.call('lab_read',{runId:a.runId,pointer:'/ledger',limit:100});assert.ok(trace.totalChars>=100);});
test('055 control conflict never auto-reclaims owner',async()=>{const a=await create('human-takeover'),r=manager.get(a.runId);await r.command({commandId:'human',expectedControlVersion:0,action:'takeover',actor:{id:'human:one',kind:'human',label:'human'}});await assert.rejects(mcp.call('lab_command',{runId:a.runId,commandId:'bad-step',expectedControlVersion:1,action:'step'}),/control/i);await assert.rejects(mcp.call('lab_command',{runId:a.runId,commandId:'reclaim',expectedControlVersion:1,action:'takeover',confirmTakeover:true}),/allow-takeover/);assert.equal(r.view().physicalActions,0);});
test('055 no live spending without explicit MCP grant',async()=>{await assert.rejects(create('live-forbidden',{backend:'jev',allowLive:true,maxRequests:5}),/allow-live/);});
test('055 terminal evidence archived and readable through MCP',async()=>{const a=await create('cancel-archive');await mcp.call('lab_command',{runId:a.runId,commandId:'cancel',expectedControlVersion:0,action:'cancel'});const index=await mcp.call('lab_archives');assert.ok(index.archives.some(x=>x.runId===a.runId));const result=await mcp.call('lab_archive_read',{name:a.runId+'.json',pointer:'/state/status'});assert.equal(JSON.parse(result.text),'cancelled');assert.equal((await mcp.call('lab_result',{runId:a.runId,pointer:'/complete'})).text,'true');});
test('055 checkpoints and fork preserve lineage, explicit own-memory scope',async()=>{const a=await create('fork-source');const cp=await mcp.call('lab_command',{runId:a.runId,commandId:'cp',expectedControlVersion:0,action:'checkpoint'});const list=await mcp.call('lab_checkpoints',{runId:a.runId});assert.ok(list.checkpoints.some(c=>c.id===cp.checkpointId));const f=await mcp.call('lab_fork',{runId:a.runId,requestId:'fork-one',checkpointId:cp.checkpointId,memory:'none',config:{}});assert.equal(f.lineage.parentRunId,a.runId);assert.equal(f.status,'ready');assert.equal(f.requests,0);});
test('055 audit can read reference run; operator cannot',async()=>{const ref=await manager.create({requestId:'reference',actor:{id:'human:ref',kind:'human',label:'Reference audit'},config:{kind:'game',controller:'rules'}});await assert.rejects(mcp.call('lab_snapshot',{runId:ref.runId}),/audit-only/);const auditor=new McpService({root,baseUrl:base,profile:'audit'});assert.equal(JSON.parse((await auditor.call('lab_snapshot',{runId:ref.runId,pointer:'/runId'})).text),ref.runId);await assert.rejects(auditor.call('lab_command',{runId:ref.runId,action:'start'}),/not enabled/);});
test('055 long poll only observes; cancelled wait leaves run untouched',async()=>{const a=await create('wait-only'),c=new AbortController();const p=mcp.call('lab_wait',{runId:a.runId,after:a.lastSeq,timeoutMs:1000},c.signal);setTimeout(()=>c.abort(Error('client cancelled')),30);await assert.rejects(p);assert.equal(manager.get(a.runId).status,'ready');assert.equal(manager.get(a.runId).view().requests,0);});
