import test from 'node:test';
import assert from 'node:assert/strict';
import {createWorld} from '../dist/src/game/world.js';
import {GOAL,INITIAL_POLICY,CAPABILITIES} from '../dist/src/game/types.js';
import {compileActions,actionKey} from '../dist/src/planning/programs.js';
import {simulate} from '../dist/src/planning/search.js';
import {SkillBook} from '../dist/src/planning/book.js';
import {TrialEvidence,dominates} from '../dist/src/planning/evidence.js';
import {GameSession,runSessionToEnd} from '../dist/src/runtime/session.js';
import {deterministicJudgment,ProgramPlanner,emptyStats} from '../dist/src/planning/controller.js';
import {ProposalRejected} from '../dist/vendor/gs-engine-ts/src/rejection.js';
const signal=()=>new AbortController().signal;
function start(){const s=createWorld('meadow');s.player={...s.home};s.delivered=4;s.bag=3;s.energy=10;return s;}
function plan(s){return compileActions(s,[{kind:'eat'},{kind:'deposit',amount:1}]);}
function proposer(p){return {async propose(ctx){return {output:{baseVersion:ctx.policy.version,basedOnRevision:ctx.snapshot.revision,body:{mode:'program',enabled:[...CAPABILITIES],subgoal:'测试程序',reserveEnergy:24,program:p},explanation:'test fixture, not model'}};}};}
function selector(deviate=false){return {async evaluate(ctx,cs){if(!ctx.policy.body.program)return {output:deterministicJudgment(cs,null)};const expected=ctx.policy.body.program.steps[ctx.snapshot.state.turn].action;const key=deviate&&expected.kind==='deposit'?'deposit:2':actionKey(expected);return {output:deterministicJudgment(cs,cs.find(c=>actionKey(c.action)===key)?.id??null)};}};}
async function session(deviate=false){const s=start(),p=plan(s),book=new SkillBook();return runSessionToEnd(new GameSession(s,'program',undefined,'',INITIAL_POLICY,{book,planner:proposer(p),selector:selector(deviate)}));}
function outcome(p,s){let state=structuredClone(s);const tracker=new TrialEvidence(s,p,2,'measured');for(const step of p.steps){const before=state;state=simulate(state,step.action);tracker.observe({policyVersion:2,before:{state:before},candidate:{action:step.action},receipt:{status:'applied'},after:{state},feedback:{actionSucceeded:true}});}return tracker.finish(state,true,false,0,0);}

test('v021 terminal deviation preserves task success without crediting original plan',async()=>{const s=await session(true);assert.equal(s.lastResult.outcome,'succeeded');assert.equal(s.book.list()[0].successes,0);assert.notEqual(s.book.list()[0].status,'verified');const e=s.events.find(e=>e.type==='execution_evidence').data;assert.equal(e.goalSucceeded,true);assert.equal(e.exactReplay,false);assert.ok(e.deviations.some(x=>x.includes('step:2:action_mismatch')));});
test('v021 exact terminal action promotes plan and stores measured outcome',async()=>{const s=await session();assert.equal(s.book.list()[0].successes,1);const e=s.book.list()[0].executions[0];assert.equal(e.exactReplay,true);assert.equal(e.outcome.energy,40);assert.equal(e.outcome.steps,2);assert.equal(e.actualActions.length,2);});
test('v021 post-state mismatch cannot receive exact execution credit',()=>{const s=start(),p=plan(s),t=new TrialEvidence(s,p,2,'test');const after=simulate(s,p.steps[0].action);after.energy--;t.observe({policyVersion:2,before:{state:s},candidate:{action:p.steps[0].action},receipt:{status:'applied'},after:{state:after},feedback:{actionSucceeded:true}});assert.ok(t.finish(after,false,false,0,0).deviations.some(x=>x.includes('result_mismatch')));});
test('v021 unconfirmed receipt is not evidence of success',()=>{const s=start(),p=plan(s),t=new TrialEvidence(s,p,2,'unknown');t.observe({policyVersion:2,before:{state:s},candidate:{action:p.steps[0].action},receipt:{status:'unknown'},after:{state:s},feedback:{actionSucceeded:false}});const e=t.finish(s,true,false,0,0);assert.equal(e.receiptConfirmed,false);assert.equal(e.exactReplay,false);});
test('v021 explicit cancellation retains interruption evidence exactly once',async()=>{const w=start(),s=new GameSession(w,'program',undefined,'',INITIAL_POLICY,{planner:proposer(plan(w)),selector:selector()});await s.step();await s.step();s.cancel();s.cancel();assert.equal(s.book.list()[0].executions.length,1);assert.equal(s.book.list()[0].executions[0].status,'interrupted');assert.equal(s.book.list()[0].successes,0);});
test('v021 shorter vs more remaining energy is a Pareto tradeoff, not automatic retirement',()=>{const s=start(),long=plan(s),short=compileActions(s,[{kind:'deposit',amount:1}]),book=new SkillBook();book.trial(s,long,'test');book.complete(long.id,true,'measured',outcome(long,s));book.trial(s,short,'test');book.complete(short.id,true,'measured',outcome(short,s));assert.deepEqual(book.list().map(x=>x.status),['verified','verified']);});
test('v021 strictly dominated same-condition program can retire',()=>{const s=start(),long=compileActions(s,[{kind:'wait'},{kind:'deposit',amount:1}]),short=compileActions(s,[{kind:'deposit',amount:1}]),book=new SkillBook();book.trial(s,long,'test');book.complete(long.id,true,'measured',outcome(long,s));book.trial(s,short,'test');book.complete(short.id,true,'measured',outcome(short,s));assert.equal(book.list().find(x=>x.id===long.id).status,'retired');});
test('v021 missing outcome vectors do not justify retirement',()=>{const s=start(),a=plan(s),b=compileActions(s,[{kind:'deposit',amount:1}]),book=new SkillBook();book.trial(s,a,'fixture');book.complete(a.id,true,'legacy');book.trial(s,b,'fixture');book.complete(b.id,true,'legacy');assert.equal(book.list()[0].status,'verified');});
test('v021 different objective versions cannot dominate',()=>{const a=outcome(plan(start()),start()).outcome;assert.equal(dominates({...a,steps:0}, {...a,objectiveVersion:'other'}),false);});
test('v021 trusted validators feed one bounded correction back through root budget',async()=>{const w=start(),p=plan(w);let calls=0,feedback;const planner={async propose(ctx){calls++;if(calls===1)throw new ProposalRejected({failedStep:2,reason:'missing final action'},{provider:'mock',model:'test',inputTokens:1,outputTokens:2});feedback=ctx.repairFeedback;return proposer(p).propose(ctx);}};const s=await runSessionToEnd(new GameSession(w,'program',undefined,'',INITIAL_POLICY,{planner,selector:selector()}));assert.equal(s.lastResult.outcome,'succeeded');assert.equal(calls,2);assert.equal(s.engine.counters.repairs,2);assert.equal(feedback.rejection.failedStep,2);assert.equal(s.export().rejectedUsage[0].outputTokens,2);});
test('v021 persistent invalid proposals stop after three counted attempts',async()=>{let calls=0;const planner={async propose(){calls++;throw new ProposalRejected({reason:'bad'});}};const s=new GameSession(start(),'program',undefined,'',INITIAL_POLICY,{planner,selector:selector()});await s.step();assert.equal(calls,3);assert.equal(s.engine.counters.repairs,3);assert.equal(s.world.snapshot().turn,0);assert.equal(s.lastResult.kind,'fault');});
test('v021 network failures are not hidden proposal retries',async()=>{let calls=0;const planner={async propose(){calls++;throw new Error('network_failure');}};const s=new GameSession(start(),'program',undefined,'',INITIAL_POLICY,{planner,selector:selector()});await s.step();assert.equal(calls,1);assert.equal(s.lastResult.kind,'fault');});
test('v021 world editing during rejected generation discards stale correction context',async()=>{let calls=0;let s;const planner={async propose(){calls++;s.world.edit('wall',{x:0,y:0});throw new ProposalRejected({reason:'bad'});}};s=new GameSession(start(),'program',undefined,'',INITIAL_POLICY,{planner,selector:selector()});await s.step();assert.equal(calls,1);assert.equal(s.lastResult.kind,'stale');});
test('v021 ProgramPlanner reports failed step and legal actions to root retry logic',async()=>{const w=start(),p=plan(w);p.steps[0].action={kind:'move',x:16,y:10};const stats=emptyStats(),planner=new ProgramPlanner(new SkillBook(),stats,()=>{},async()=>({output:{body:{program:p}},usage:{provider:'mock',model:'mock',inputTokens:7,outputTokens:9}}));let err;try{await planner.propose({goal:GOAL,snapshot:{state:w,revision:'1'},policy:INITIAL_POLICY,recent:[]},'test',signal());}catch(e){err=e;}assert.ok(err instanceof ProposalRejected);assert.equal(err.feedback.failedStep,1);assert.ok(err.feedback.legalCandidates.length);assert.equal(err.usage.outputTokens,9);assert.equal(stats.providerG,1);});
test('v021 measurements roundtrip and malformed evidence is discarded',async()=>{const s=await session(),m=new Map(),storage={getItem:k=>m.get(k)??null,setItem:(k,v)=>m.set(k,v),removeItem:k=>m.delete(k)};storage.setItem('tuanzi-gs.skills.v2',JSON.stringify(s.book.export()));const b=new SkillBook(storage);assert.equal(b.list()[0].executions[0].exactReplay,true);const raw=s.book.export();raw.items[0].executions=[{exactReplay:true,outcome:{steps:-1}}];storage.setItem('tuanzi-gs.skills.v2',JSON.stringify(raw));assert.deepEqual(new SkillBook(storage).list()[0].executions,[]);});
