import test from 'node:test';
import assert from 'node:assert/strict';
import {createWorld,GameWorld,applyAction,reachableBerries} from '../dist/src/game/world.js';
import {TuanziDomain} from '../dist/src/game/domain.js';
import {GOAL,INITIAL_POLICY,CAPABILITIES} from '../dist/src/game/types.js';
import {legalPrimitives,searchProgram,simulate} from '../dist/src/planning/search.js';
import {compileActions,verifyProgram,parseProgram,parseAction,actionKey,stateFingerprint,exactWorldKey} from '../dist/src/planning/programs.js';
import {inspectProgram} from '../dist/vendor/gs-engine-ts/src/program.js';
import {SkillBook} from '../dist/src/planning/book.js';
import {GameSession,runSessionToEnd,comparePrograms} from '../dist/src/runtime/session.js';
import {deterministicJudgment} from '../dist/src/planning/controller.js';
const signal=()=>new AbortController().signal;
const world=createWorld('guarded');let program;
test.before(async()=>{const result=await searchProgram(world,signal(),{heuristic:'explore'});assert.equal(result.report.status,'solved');program=compileActions(world,result.actions);});
function context(s,policy=INITIAL_POLICY,recent=[]){return {goal:GOAL,snapshot:{state:structuredClone(s),revision:String(s.revision),observedAt:0},policy:structuredClone(policy),recent};}
function store(){const m=new Map();return {getItem:k=>m.get(k)??null,setItem:(k,v)=>m.set(k,v),removeItem:k=>m.delete(k)};}

test('a primitive search produces a finite program, not a lure mode',()=>{assert.equal(program.schema,'gs/program/v1');assert.ok(program.steps.length>0&&program.steps.length<=180);assert.ok(program.steps.some(x=>x.action.kind==='drop'));assert.ok(!('mode' in program));assert.ok(!JSON.stringify(program).includes('lureSite'));});
test('generated program passes fixed simulator/root verification',()=>{const v=verifyProgram(world,program);assert.equal(v.ok,true);assert.equal(v.final.delivered,5);assert.equal(v.final.attacks,0);assert.equal(v.final.turn,72);assert.equal(v.final.energy,46);assert.deepEqual(world,createWorld('guarded'));});
test('program DSL is roundtrip serializable data',()=>assert.deepEqual(parseProgram(JSON.parse(JSON.stringify(program))),program));
test('DSL rejects arbitrary code or arbitrary nested instructions',()=>{assert.throws(()=>parseProgram({...program,code:'eval("1")'}));assert.throws(()=>parseProgram({...program,steps:[{expect:program.steps[0].expect,action:{kind:'eval',code:'1'}}]}));});
test('DSL rejects a model-authored verifier, permissions, or unbounded loop',()=>{for(const key of ['verifier','permissions','while','children'])assert.throws(()=>parseProgram({...program,[key]:true}));});
test('DSL rejects empty, overlong, fractional, and malformed fields',()=>{assert.throws(()=>parseProgram({...program,steps:[]}));assert.throws(()=>parseProgram({...program,steps:Array(181).fill(program.steps[0])}));assert.throws(()=>parseProgram({...program,startTurn:0.5}));assert.throws(()=>parseProgram({...program,steps:[{...program.steps[0],expect:'trusted'}]}));});
test('runtime action parser rejects out-of-bounds/unauthorized JSON',()=>{for(const a of [{kind:'move',x:1.5,y:1},{kind:'move',x:100,y:0},{kind:'teleport',x:0,y:0},{kind:'eat',goal:'override'},{kind:'deposit',amount:4},{kind:'pickup',berryId:''}])assert.throws(()=>parseAction(a));});
test('compiler grounds each raw action against actual legal primitives',()=>assert.throws(()=>compileActions(world,[{kind:'move',x:16,y:10}]),/illegal/));
test('partial surviving trajectories are not certified as task success',()=>{assert.equal(verifyProgram(world,{...program,steps:program.steps.slice(0,5)}).ok,false);assert.throws(()=>compileActions(world,program.steps.slice(0,5).map(x=>x.action)),/root_goal/);});
test('precondition checksum cannot bypass actual legality',()=>{const bad=structuredClone(program);bad.steps[0].action={kind:'move',x:16,y:10,objective:'safe',targetId:'cell',distance:1};assert.equal(verifyProgram(world,bad).ok,false);});
test('shadow simulation does not mutate the real world',()=>{const w=new GameWorld(world),before=w.snapshot();verifyProgram(w.snapshot(),program);assert.deepEqual(w.snapshot(),before);});
test('program cannot consume more than remaining root budget',()=>{const w=structuredClone(world);w.maxTurns=5;assert.equal(verifyProgram(w,program).ok,false);});
test('fingerprint ignores incidental revisions but covers physical edits and budget',()=>{const w=structuredClone(world);w.revision=99;assert.equal(stateFingerprint(w),stateFingerprint(world));w.energy--;assert.notEqual(stateFingerprint(w),stateFingerprint(world));const b=structuredClone(world);b.walls.push({x:1,y:3});assert.notEqual(stateFingerprint(b),stateFingerprint(world));});
test('program cursor resolves a step only after checking current state',()=>{assert.equal(inspectProgram(program,world.turn,stateFingerprint(world)).kind,'ready');assert.equal(inspectProgram(program,world.turn,'s-0000000000000000').kind,'invalid');assert.equal(inspectProgram(program,world.turn+181,stateFingerprint(world)).kind,'invalid');});
test('search cancellation propagates without returning a fake program',async()=>{const c=new AbortController();c.abort();await assert.rejects(searchProgram(world,c.signal));});
test('search budget exhaustion is not called impossibility',async()=>{const r=await searchProgram(world,signal(),{maxExpanded:1,maxDepth:1});assert.equal(r.report.status,'budget');assert.deepEqual(r.actions,[]);assert.equal(r.report.expanded,1);});
test('same inputs and settings give the same program actions',async()=>{const a=await searchProgram(world,signal(),{heuristic:'explore'});assert.deepEqual(a.actions,program.steps.map(x=>x.action));});
test('primitive pool allows drop before any mode switch',()=>{assert.ok(legalPrimitives(world).some(a=>a.kind==='drop'));});
test('new search and full-rule baseline expose identical candidates and permissions',async()=>{const a=new GameSession(world,'program'),b=new GameSession(world,'rules-full');assert.deepEqual(a.domain.enumerate(context(world,a.engine.currentPolicy)),b.domain.enumerate(context(world,b.engine.currentPolicy)));assert.deepEqual(a.engine.currentPolicy.body.enabled,[...CAPABILITIES]);});
test('ordinary tasks still avoid fresh program search',async()=>{for(const id of ['meadow','detour']){const s=await runSessionToEnd(new GameSession(createWorld(id),'program'));assert.deepEqual(s.lastResult,{kind:'done',outcome:'succeeded'});assert.equal(s.planning.searchRuns,0);assert.equal(s.planning.providerG+s.planning.providerS,0);}});
test('program mode really executes synthesized actions and records no provider calls',async()=>{const s=await runSessionToEnd(new GameSession(world,'program'));assert.deepEqual(s.lastResult,{kind:'done',outcome:'succeeded'});assert.equal(s.world.snapshot().turn,72);assert.equal(s.planning.searchRuns,1);assert.equal(s.planning.providerG+s.planning.providerS,0);assert.ok(s.events.some(e=>e.type==='program_synthesized'));assert.ok(s.events.some(e=>e.type==='skill_promoted'));assert.equal(s.book.list()[0].status,'verified');});
test('program commit is a separate step and does not execute old candidates',async()=>{const s=new GameSession(world,'program');await s.step();assert.equal(s.lastResult.kind,'policy_updated');assert.equal(s.world.snapshot().turn,0);assert.equal(s.book.list()[0].status,'trial');assert.equal(s.book.find(world),null);});
test('skill requires actual success before reuse; warm execution does no new search',async()=>{const book=new SkillBook();const cold=await runSessionToEnd(new GameSession(world,'program',undefined,'',INITIAL_POLICY,{book}));const warm=await runSessionToEnd(new GameSession(world,'program',undefined,'',INITIAL_POLICY,{book}));assert.equal(cold.planning.searchRuns,1);assert.equal(warm.planning.searchRuns,0);assert.equal(warm.planning.skillHits,1);assert.equal(warm.planning.expanded,0);assert.deepEqual(warm.world.snapshot(),cold.world.snapshot());assert.equal(book.list()[0].successes,2);});
test('persistent skill book reloads and revalidates exact conditions',()=>{const storage=store(),a=new SkillBook(storage);a.trial(world,program,'test');a.complete(program.id,true,'actual test');const b=new SkillBook(storage);assert.equal(b.find(world)?.id,program.id);assert.equal(b.lookupChecks,1);});
test('changed resources, layout, or rules do not match old skills',()=>{const b=new SkillBook();b.trial(world,program,'test');b.complete(program.id,true,'actual');for(const w of [createWorld('remix'),{...structuredClone(world),energy:97},{...structuredClone(world),maxTurns:170}])assert.equal(b.find(w),null);});
test('failed skill is quarantined, not silently reused',()=>{const b=new SkillBook();b.trial(world,program,'test');b.complete(program.id,true,'success');b.complete(program.id,false,'failure');assert.equal(b.list()[0].status,'quarantined');assert.equal(b.find(world),null);});
test('bad localStorage bytes cannot create an executable skill',()=>{const storage=store();storage.setItem('tuanzi-gs.skills.v2','{"format":"gs-skill-book/v2","items":[{"program":{"code":"x"}}]}');const b=new SkillBook(storage);assert.deepEqual(b.list(),[]);});
test('storage failures fall back to in-memory operation without claiming persistence',()=>{const b=new SkillBook({getItem(){throw Error('denied')},setItem(){throw Error('quota')},removeItem(){}});b.trial(world,program,'test');assert.equal(b.list().length,1);assert.ok(b.persistenceError);});
test('editing after program commit prevents old action and does not promote it',async()=>{const s=new GameSession(world,'program');await s.step();const id=s.engine.currentPolicy.body.program.id;s.edit('wall',{x:0,y:0});const prior=s.world.snapshot().turn;await s.step();assert.equal(s.world.snapshot().turn,prior);assert.ok(s.events.some(e=>e.type==='health_alert'&&e.data.reason==='program_precondition_changed'));const record=s.book.list().find(x=>x.id===id);assert.equal(record.successes,0);assert.ok(record.invalidations>=1);});
test('mid-program restoration cannot certify an unobserved prefix',async()=>{const s=new GameSession(world,'program');await s.step();await s.step();const book=new SkillBook();const restored=await runSessionToEnd(new GameSession(s.world.snapshot(),'program',undefined,'',s.engine.currentPolicy,{book}));assert.deepEqual(restored.lastResult,{kind:'done',outcome:'succeeded'});assert.deepEqual(book.list(),[]);});
test('new mirrored layout synthesizes a fresh valid program, not a coordinate replay',async()=>{const b=new SkillBook();b.trial(world,program,'test');b.complete(program.id,true,'actual');const s=await runSessionToEnd(new GameSession(createWorld('remix'),'program',undefined,'',INITIAL_POLICY,{book:b}));assert.deepEqual(s.lastResult,{kind:'done',outcome:'succeeded'});assert.equal(s.planning.skillHits,0);assert.equal(s.planning.searchRuns,1);assert.notEqual(s.engine.currentPolicy.body.program.id,program.id);});
test('four-way comparison includes complete rules and explicitly trained warm reuse',async()=>{const before=structuredClone(world);const rows=await comparePrograms(world);assert.deepEqual(world,before);assert.equal(rows.length,4);assert.ok(rows.every(r=>r.outcome==='任务完成'));assert.deepEqual(rows.map(r=>r.turns),[76,76,72,72]);assert.deepEqual(rows.map(r=>r.trace.planning.searchRuns),[0,0,1,0]);assert.equal(rows[3].trace.planning.skillHits,1);assert.ok(rows.every(r=>r.externalCalls===0));});
test('repeated A-B movement is diagnosed even when individual moves report progress',async()=>{
  const w=createWorld('meadow');w.terrain.fill('grass');w.walls=[];w.guards=[];w.player={x:3,y:7};w.home={x:1,y:7};w.berries=[{x:1,y:6,id:'left'},{x:8,y:7,id:'right'},{x:8,y:6,id:'a'},{x:8,y:5,id:'b'},{x:8,y:4,id:'c'}];
  const selector={async evaluate(ctx,cs){const next=ctx.snapshot.state.player.x===3?4:3;const c=cs.find(c=>c.action.kind==='move'&&c.action.x===next&&c.action.y===7);return {output:deterministicJudgment(cs,c?.id??null)};}};
  const s=await runSessionToEnd(new GameSession(w,'rules-full',undefined,'',INITIAL_POLICY,{selector}));
  assert.ok(s.world.snapshot().turn<=6);assert.ok(s.events.some(e=>e.type==='health_alert'&&e.data.reason==='state_cycle_detected'));assert.equal(s.world.snapshot().delivered,0);
});
test('legitimate waiting while guard state changes is not flagged as an identical cycle',()=>{
  let w=createWorld('guarded');w.guards[0].eating=12;const recent=[];const domain=new TuanziDomain(new GameWorld(w));
  for(let i=0;i<6;i++){const before=context(w).snapshot;const a={kind:'wait'};w=simulate(w,a);w.revision++;recent.push({cycle:i,policyVersion:1,before,after:context(w).snapshot,candidate:{id:'wait',action:a,description:'wait',capability:'game.wait'},receipt:{status:'applied',detail:''},feedback:{progress:true,actionSucceeded:true,metrics:{},facts:[]}});}
  assert.equal(domain.assess(context(w,INITIAL_POLICY,recent)),null);
});
test('events use a single monotonic sequence across kernel and learning records',async()=>{const s=await runSessionToEnd(new GameSession(world,'program'));assert.deepEqual(s.events.map(e=>e.seq),s.events.map((_,i)=>i+1));});
test('clearing memory during a paused trial does not fabricate a later saved record',async()=>{const s=new GameSession(world,'program');await s.step();s.book.clear();await runSessionToEnd(s);assert.equal(s.lastResult.outcome,'succeeded');assert.deepEqual(s.book.list(),[]);assert.ok(!s.events.some(e=>e.type==='skill_promoted'));assert.ok(s.events.some(e=>e.type==='skill_record_removed'));});
test('changed active preconditions go to repair rather than structural-policy fault',async()=>{const s=new GameSession(world,'program');await s.step();s.edit('wall',{x:0,y:0});const result=await s.step();assert.ok(result.kind!=='fault');assert.ok(s.events.some(e=>e.type==='health_alert'));});
