import {subproblem,analysis} from './fixtures/adaptive-v054.mjs';
import test from 'node:test';import assert from 'node:assert/strict';
import {AutonomousSession} from '../dist/src/adaptive/session.js';import {tiny,program,proposal,generator,backend,chooseDeposit} from './fixtures/adaptive-v05.mjs';
const run=(g,extra={},b=backend(chooseDeposit),w=tiny())=>new AutonomousSession(w,{backend:b,generator:g,strategy:'direct',orderSeed:441,...extra});
test('052 two output repairs do not spend the single effective revision quota',async()=>{const p=proposal(),g=generator((i,n)=>n===1?{actionFrame:p.proposals[0]}:n===2?{proposals:[{actionFrame:p.proposals[0]}]}:p),s=run(g,{maxRevisions:1,maxFormatRepairs:2,maxGCalls:3});await s.step();assert.equal(s.lastResult.outcome,'succeeded');const a=s.diagnostics().outputAccounting;assert.equal(a.formatRepairs,2);assert.equal(a.invalidOutputs,2);assert.equal(a.validBatches,1);assert.equal(a.revisionAttempts,1);assert.equal(a.committedRevisions,1);assert.equal(s.diagnostics().gCalls,3);assert.equal(s.diagnostics().metaCalls,0);assert.equal(s.world.snapshot().turn,1);});
test('052 output repair does not receive whole world or full selector history',async()=>{const p=proposal(),g=generator((i,n)=>n===1?{actionFrame:p.proposals[0]}:p),s=run(g);await s.step();const r=g.calls[1];assert.equal(r.schema,'gs/output-repair-request/v1');assert.equal(r.evidence,undefined);assert.equal(r.frame.context,undefined);assert.ok(r.diagnostics.issues.length);assert.deepEqual(r.preserveFrom,{actionFrame:p.proposals[0]});});
test('052 malformed output with zero correction budget stops with distinct reason and no meta S',async()=>{const s=run(generator(()=>({bad:1})),{maxFormatRepairs:0});await s.step();assert.equal(s.lastResult.reason,'output_format_repair_exhausted');assert.equal(s.diagnostics().metaCalls,0);assert.equal(s.diagnostics().outputAccounting.revisionAttempts,0);assert.equal(s.world.snapshot().turn,0);});
test('052 endless malformed output is bounded separately from revision attempts',async()=>{const s=run(generator(()=>({bad:1})),{maxFormatRepairs:2,maxRevisions:6,maxGCalls:12});await s.step();assert.equal(s.diagnostics().gCalls,3);assert.equal(s.lastResult.reason,'output_format_repair_exhausted');assert.equal(s.diagnostics().outputAccounting.invalidOutputs,3);assert.equal(s.diagnostics().outputAccounting.revisionAttempts,0);});
test('052 root G budget includes correction requests; no free retries',async()=>{const s=run(generator(()=>({bad:1})),{maxFormatRepairs:4,maxGCalls:2});await s.step();assert.equal(s.diagnostics().gCalls,2);assert.ok(s.lastResult.reason.includes('budget'));assert.equal(s.world.snapshot().turn,0);});
test('052 network error is not routed into format retry',async()=>{const g=generator(()=>{throw Error('HTTP 502');}),s=run(g);await s.step();assert.equal(g.calls.length,1);assert.equal(s.lastResult.kind,'fault');assert.equal(s.diagnostics().outputAccounting.formatRepairs,0);});
test('052 cancellation during correction propagates and prevents physical writes',async()=>{let entered,unblock;const ready=new Promise(r=>entered=r),gate=new Promise(r=>unblock=r);const g=generator(async(i,n)=>{if(n===1)return {bad:1};entered();await gate;return proposal();}),s=run(g);const step=s.step();await ready;s.cancel();unblock();await step;assert.equal(s.world.snapshot().turn,0);assert.equal(s.diagnostics().outputAccounting.committedRevisions,0);});
test('052 changed world invalidates format-corrected proposal',async()=>{let entered,unblock;const ready=new Promise(r=>entered=r),gate=new Promise(r=>unblock=r);const g=generator(async(i,n)=>{if(n===1)return {bad:1};entered();await gate;return proposal();}),s=run(g);const step=s.step();await ready;s.edit('wall',{x:0,y:0});unblock();await step;assert.equal(s.lastResult.kind,'stale');assert.equal(s.diagnostics().outputAccounting.committedRevisions,0);});
test('052 local stage patch reaches S without resetting already spent stage actions',async()=>{const g=generator(i=>i.cause==='initial_environment_review'?proposal(i.evidence.currentProgram):({proposals:[{kind:'stage-update',expectedPolicyVersion:i.evidence.policyVersion,stageIndex:i.evidence.currentStage,changes:{question:'修订后完成当前任务',kinds:['deposit','wait'],groups:['self']}}]}));const b=backend(f=>f.kind==='reframe'?f.options[0].id:f.question.includes('修订后')?chooseDeposit(f):'wait');const s=run(g,{},b);for(let i=0;i<7&&!s.finished;i++)await s.step();assert.equal(s.lastResult.outcome,'succeeded');const commit=s.events.find(e=>e.type==='adaptation_committed'&&e.data.patch.kind==='stage-update');assert.equal(commit.data.after.context.stage.usedActions,6);assert.equal(commit.data.after.context.stage.maxActions,24);assert.equal(s.export().program.stages.length,1);assert.equal(s.export().program.title,'未形成策略');});
test('052 stage-update cannot silently reset spent budget by decreasing maxActions',async()=>{const g=generator(i=>i.cause==='initial_environment_review'?proposal(i.evidence.currentProgram):({proposals:[{kind:'stage-update',expectedPolicyVersion:i.evidence.policyVersion,stageIndex:i.evidence.currentStage,changes:{question:'重新描述但不重置计时',maxActions:2}}]}));const s=run(g,{},backend(f=>f.kind==='reframe'?f.options[0].id:'wait'));for(let i=0;i<6;i++)await s.step();await s.step();assert.equal(s.world.snapshot().turn,6);assert.equal(s.lastResult.kind,'policy_updated');});
test('052 full strategy rewrite during format repair is rejected and original anchor remains',async()=>{const p=proposal(),changed=proposal(program('另一个策略'));const g=generator((i,n)=>n===1?{actionFrame:p.proposals[0]}:n===2?changed:p),s=run(g,{maxFormatRepairs:2});await s.step();assert.equal(s.lastResult.outcome,'succeeded');assert.deepEqual(g.calls[2].preserveFrom,{actionFrame:p.proposals[0]});assert.ok(s.events.some(e=>e.type==='adaptation_rejected'&&e.data.reason==='repair_intent_changed'));});
test('052 valid single-action interface goes to action S, no silent fallback',async()=>{const s=run(generator(()=>proposal()),{maxDepth:1,maxFormatRepairs:2},backend(()=>null));await s.step();assert.equal(s.world.snapshot().turn,0);assert.equal(s.lastResult.reason,'adaptation_budget_exhausted');assert.equal(s.diagnostics().metaCalls,0);});
test('054 format correction also operates inside explicit child G/S',async()=>{const a=analysis();const b=backend(f=>f.kind==='analysis'?f.options[0].id:chooseDeposit(f));const g=generator(i=>i.schema==='gs/output-repair-request/v1'?a:i.frame.kind==='analysis'?{actionFrame:a.proposals[0]}:i.cause==='subproblem_completed'?proposal():subproblem());const s=run(g,{maxFormatRepairs:1,maxDepth:2,maxGCalls:5},b);await s.step();assert.equal(s.lastResult.outcome,'succeeded');assert.ok(g.calls.some(x=>x.schema==='gs/output-repair-request/v1'&&x.depth===1&&x.frame.kind==='analysis'));assert.equal(s.diagnostics().outputAccounting.formatRepairs,1);assert.equal(s.world.snapshot().turn,1);});

test('052 exhausted shared resolve generation budget has its own stop reason',async()=>{const {AdaptiveGS}=await import('../dist/vendor/gs-engine-ts/src/adaptive.js');let generated=0;const engine=new AdaptiveGS({select:async()=>({choice:null,detail:{}}),generate:async()=>{generated++;return {};},parse:()=>[{id:'test',description:'test fixture',value:{}}],apply:f=>f,evidence:()=>({}),check:()=>{},event:()=>{}},{maxGenerations:1,maxDepth:2,maxRevisions:3});const r=await engine.resolve({kind:'action',question:'test',revision:'1',context:{},options:[{id:'a',description:'a',value:{}}]},new AbortController().signal);assert.equal(generated,1);assert.equal(r.reason,'adaptation_generation_budget_exhausted');});
