/** Full production broker -> local mock SSE -> authoritative run -> HTTP event subscribers. */
import test from 'node:test';import assert from 'node:assert/strict';import http from 'node:http';import {spawn} from 'node:child_process';import {once} from 'node:events';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import {proposal} from './fixtures/adaptive-v05.mjs';import {generationHistory} from '../dist/src/lab/generation.js';
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
test('051 production broker streams G over real HTTP before completion; one G attempt and no credentials in export',async()=>{
 let release;const gate=new Promise(r=>release=r);const calls=[];const upstream=http.createServer(async(req,res)=>{let raw='';for await(const c of req)raw+=c;const body=JSON.parse(raw);calls.push(body);const isG=body.messages[0].content.startsWith('You are G');
 if(isG){assert.equal(body.stream,true);res.writeHead(200,{'content-type':'text/event-stream'});res.flushHeaders();res.write('data: '+JSON.stringify({model:'loopback-fixture-G',choices:[{index:0,delta:{reasoning_content:'本机流式传输检查，不是外部模型。'},finish_reason:null}]})+'\n\n');await gate;res.end('data: '+JSON.stringify({model:'loopback-fixture-G',choices:[{index:0,delta:{content:JSON.stringify(proposal())},finish_reason:'stop'}]})+'\n\ndata: [DONE]\n\n');}
 else {const inp=JSON.parse(body.messages[1].content),answers={};for(const [id,q]of Object.entries(inp.questions))answers[id]={type:'choice',choice:'none',confidence:1,probabilities:Object.fromEntries(Object.keys(q.criteria).map(k=>[k,k==='none'?1:0]))};res.writeHead(200,{'content-type':'application/json'});res.end(JSON.stringify({model:'loopback-fixture-S',choices:[{message:{content:JSON.stringify({answers})}}]}));}});
 await new Promise(r=>upstream.listen(0,'127.0.0.1',r));const dummy=http.createServer();await new Promise(r=>dummy.listen(0,'127.0.0.1',r));const port=dummy.address().port;await new Promise(r=>dummy.close(r));
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'gs-server-stream-')),base=`http://127.0.0.1:${port}`,secret='LOOPBACK_ONLY_SECRET';const child=spawn(process.execPath,['server.mjs'],{cwd:process.cwd(),env:{...process.env,PORT:String(port),TYPESAFE_API_KEY:'',LLM_URL:`http://127.0.0.1:${upstream.address().port}/chat`,LLM_API_KEY:secret,LLM_MODEL:'loopback-model',LLM_STREAM:'true',LLM_STREAM_INCLUDE_USAGE:'false',LLM_THINKING:'',LLM_REASONING_EFFORT:'',MAX_SERVER_CALLS:'6',GS_LAB_OUTPUT_DIR:dir},stdio:'ignore'});
 try{let token;for(let i=0;i<100;i++){try{const r=await fetch(base+'/api/status');if(r.ok){const j=await r.json();token=j.token;assert.equal(j.generationStreaming,true);break;}}catch{}await sleep(30);}assert.ok(token);
 const api=async(p,data)=>{const r=await fetch(base+p,{method:data?'POST':'GET',headers:{'x-gs-token':token,'content-type':'application/json'},...(data?{body:JSON.stringify(data)}:{})});assert.ok(r.ok,`HTTP ${r.status}`);return r.json();};
 const actor={id:'agent:stream-server',kind:'agent',label:'Loopback-only streaming test'},run=await api('/api/lab/runs',{requestId:'stream-server-test',actor,config:{kind:'game',controller:'adaptive',strategy:'direct',backend:'llm',generator:'llm',allowLive:true,maxRequests:6,maxGCalls:1,maxDepth:1,deadlineMs:15000}});
 let done=false;const step=api(`/api/lab/runs/${run.runId}/commands`,{actor,commandId:'first-step',expectedControlVersion:0,action:'step'}).then(r=>{done=true;return r;});
 let gs;for(let i=0;i<150;i++){const p=await api(`/api/lab/runs/${run.runId}/events?after=0&limit=1000`);gs=generationHistory(p.events);if(gs[0]?.reasoning)break;await sleep(20);}assert.ok(gs[0]?.reasoning.includes('本机流式'));assert.equal(done,false);assert.equal((await api(`/api/lab/runs/${run.runId}`)).physicalActions,0);assert.equal(calls.filter(c=>c.stream===true).length,1);
 release();await step;const ex=await api(`/api/lab/runs/${run.runId}/export`);assert.equal(generationHistory(ex.events)[0].status,'complete');assert.ok(!JSON.stringify(ex).includes(secret));assert.equal(ex.state.physicalActions,0);assert.equal(calls.filter(c=>c.stream===true).length,1);assert.equal(ex.trace.notes.referenceResultRead,false);
 }finally{release();child.kill();if(child.exitCode===null)await Promise.race([once(child,'exit'),sleep(2000)]);upstream.closeAllConnections();await new Promise(r=>upstream.close(r));fs.rmSync(dir,{recursive:true,force:true});}
});
