import {GenerationPanel} from './generation-panel.js';
/** v0.5 observation client. No GSEngine, strategy mutation, simulation or model calls. */
import {WorldRenderer} from '../ui/renderer.js';
import type {LabView,LabEvent,Actor,Command,LabConfig} from './types.js';
import {layout} from './viewer-layout.js';
import {STATUS,SCENARIOS,TASKS,STRATEGIES,CONTRACTS,PHASES,terminal,rec,list,esc,titleOf,goalOf,duration,actualSource,sourceLabel,reasonText,statusCopy,refereeCopy,actionsFor,flowOf,keyEvents,decisionsFrom,replayStates,isView,unwrap} from './presentation.js';
const $=<T extends HTMLElement=HTMLElement>(id:string):T=>{const el=document.getElementById(id);if(!el)throw Error(`Missing viewer element: ${id}`);return el as T;};
const val=(id:string)=>$<HTMLInputElement>(id).value;
const checked=(id:string)=>$<HTMLInputElement>(id).checked;
const hide=(id:string,hidden:boolean)=>$(id).classList.toggle('hidden',hidden);
const text=(id:string,v:unknown)=>{$(id).textContent=String(v??'');};
const html=(id:string,v:string)=>{if($(id).innerHTML!==v)$(id).innerHTML=v;};
function uid(){if(typeof crypto.randomUUID==='function')return crypto.randomUUID();const b=crypto.getRandomValues(new Uint8Array(16));return [...b].map(x=>x.toString(16).padStart(2,'0')).join('');}
let actorId:string;try{actorId=sessionStorage.getItem('gs-lab-viewer-id')??`human:${uid()}`;sessionStorage.setItem('gs-lab-viewer-id',actorId);}catch{actorId=`human:${uid()}`;}
const actor:Actor={id:actorId,kind:'human',label:'网页操作员'};
let token='',cap:any=null,state:LabView|null=null,events:LabEvent[]=[],cursor=0,streamAbort:AbortController|null=null,generation=0;
let connected=false,pending=false,listing=true,replaying=false,imported=false,frames:LabView[]=[],frameIndex=0,report:any=null,tab='overview',decisionIndex=-1;
let runs:LabView[]=[],checkpoints:any[]=[],lastSync='',historyComplete=true,selectedId:string|null=null;
let paintTimer:ReturnType<typeof setTimeout>|undefined;
const rawRefs=new Map<string,{title:string;value:unknown}>();let refCount=0;
$('lab-app').innerHTML=layout;
const renderer=new WorldRenderer($<HTMLCanvasElement>('world'));
const generationPanel=new GenerationPanel(()=>openDialog('generation-dialog'),toast);
let generationPaint:ReturnType<typeof setTimeout>|undefined;
function paintGeneration(){const s=current();if(!s||listing)return;generationPanel.update(s.runId,events,replaying?s.lastSeq:cursor,{replay:replaying||imported,connected});if(!replaying&&!imported&&connected&&s.startedAt&&!s.endedAt){text('elapsed',duration(Math.max(s.elapsedMs,Date.now()-Date.parse(s.startedAt))));$('elapsed').title='观察端时钟估计；导出与评估仍以服务端记录为准。';}}
function queueGeneration(){if(generationPaint!==undefined)return;generationPaint=setTimeout(()=>{generationPaint=undefined;paintGeneration();},60);}
const current=()=>replaying?frames[frameIndex]??state:state;
function badge(s:LabView){return `<span class="badge ${terminal(s.status)?s.status==='succeeded'?'success':'warning':['running','stepping'].includes(s.status)?'active':''}">${esc(STATUS[s.status]??s.status)}</span>`;}
function factsGrid(rows:[string,unknown][]){return `<dl class="facts-grid">${rows.map(([k,v])=>`<div><dt>${esc(k)}</dt><dd>${esc(v??'未记录')}</dd></div>`).join('')}</dl>`;}
function rawButton(title:string,value:unknown){const id=`raw-${++refCount}`;rawRefs.set(id,{title,value});return `<button class="text-button" data-evidence="${id}">${esc(title)} ↗</button>`;}
let toastTimer:ReturnType<typeof setTimeout>;function toast(message:string){text('toast',message);hide('toast',false);clearTimeout(toastTimer);toastTimer=setTimeout(()=>hide('toast',true),6500);}
const dialogTriggers=new Map<string,HTMLElement>();
function openDialog(id:string){const d=$<HTMLDialogElement>(id);if(d.open)return;dialogTriggers.set(id,document.activeElement as HTMLElement);d.showModal();const target=d.querySelector<HTMLElement>('input:not([type="radio"]):not([type="checkbox"]),select,button');target?.focus();}
function closeDialog(id:string){$<HTMLDialogElement>(id).close();}
for(const d of document.querySelectorAll<HTMLDialogElement>('dialog'))d.addEventListener('close',()=>{const trigger=dialogTriggers.get(d.id);if(trigger?.isConnected&&trigger.getClientRects().length)trigger.focus();});
document.addEventListener('click',e=>{const target=e.target as Element;const close=target.closest<HTMLElement>('[data-close]');if(close){closeDialog(close.dataset.close!);return;}
 const raw=target.closest<HTMLElement>('[data-evidence]');if(raw){const entry=rawRefs.get(raw.dataset.evidence!);if(entry){text('evidence-title',entry.title);text('evidence-json',JSON.stringify(entry.value,null,2));openDialog('evidence-dialog');}}
 const run=target.closest<HTMLElement>('[data-run]');if(run)void openRun(run.dataset.run!).catch(error=>toast(String(error)));
 const step=target.closest<HTMLElement>('[data-seq]');if(step){const ev=events.find(x=>x.seq===Number(step.dataset.seq));if(ev){text('evidence-title',`事件 #${ev.seq}`);text('evidence-json',JSON.stringify(ev,null,2));openDialog('evidence-dialog');}}
});
async function api(path:string,body?:unknown){const r=await fetch(path,{method:body===undefined?'GET':'POST',headers:{'x-gs-token':token,...(body===undefined?{}:{'content-type':'application/json'})},...(body===undefined?{}:{body:JSON.stringify(body)})});const data=await r.json();if(!r.ok)throw Error(`${rec(data.error).code??r.status}: ${rec(data.error).message??data.error}`);return data;}
const path=(id=state?.runId)=>`/api/lab/runs/${encodeURIComponent(id??'')}`;
function setConnection(ok:boolean,label:string){connected=ok;text('connection',label);$('connection-dot').classList.toggle('offline',!ok);if(!listing)queuePaint();}
function queuePaint(){if(paintTimer!==undefined)return;paintTimer=setTimeout(()=>{paintTimer=undefined;if(!listing)render();},60);}
function setTab(next:string,updateUrl=true){if(!['overview','decision','diagnostics','config'].includes(next))next='overview';tab=next;
 for(const b of document.querySelectorAll<HTMLButtonElement>('[data-tab]')){const on=b.dataset.tab===tab;b.setAttribute('aria-selected',String(on));b.tabIndex=on?0:-1;hide('panel-'+b.dataset.tab!,!on);}
 if(!listing)render();if(updateUrl&&!imported&&state)history.replaceState(null,'',`/lab?run=${encodeURIComponent(state.runId)}${tab==='overview'?'':`&tab=${tab}`}`);
}
for(const b of document.querySelectorAll<HTMLButtonElement>('[data-tab]')){b.onclick=()=>setTab(b.dataset.tab!);b.onkeydown=e=>{const tabs=[...document.querySelectorAll<HTMLButtonElement>('[data-tab]')];let i=tabs.indexOf(b);if(e.key==='ArrowRight')i=(i+1)%tabs.length;else if(e.key==='ArrowLeft')i=(i-1+tabs.length)%tabs.length;else if(e.key==='Home')i=0;else if(e.key==='End')i=tabs.length-1;else return;e.preventDefault();tabs[i]!.focus();setTab(tabs[i]!.dataset.tab!);};}
function showList(push=true){if($<HTMLDialogElement>('generation-dialog').open)closeDialog('generation-dialog');generation++;streamAbort?.abort();streamAbort=null;listing=true;replaying=false;imported=false;selectedId=null;hide('list-page',false);hide('run-page',true);if(push)history.pushState(null,'','/lab');void refreshRuns().catch(e=>toast(String(e)));}
$('brand-home').onclick=e=>{e.preventDefault();showList();};$('home').onclick=()=>showList();$('back-list').onclick=()=>showList();
function renderList(){const q=val('run-search').trim().toLowerCase(),filter=val('status-filter');const filtered=runs.filter(r=>(`${titleOf(r.config)} ${r.owner.label} ${r.runId} ${r.config.strategy}`.toLowerCase().includes(q))&&(filter==='all'||filter==='active'&&!terminal(r.status)||filter==='succeeded'&&r.status==='succeeded'||filter==='attention'&&['blocked','failed','stopped','fault'].includes(r.status)||filter==='ended'&&terminal(r.status)));
 text('list-count',`${filtered.length} 场实验`);
 html('run-list',filtered.length?filtered.map(r=>`<button class="run-row" data-run="${esc(r.runId)}"><span class="run-name"><span class="run-icon">${r.config.kind==='game'?'◈':'⌘'}</span><span><strong>${esc(titleOf(r.config))}</strong><small>${r.config.kind==='game'?'完整任务':'判断组合'} · ${esc(STRATEGIES[r.config.strategy])}<span class="run-id-small">${esc(r.runId.slice(0,15))}…</span></small></span></span><span>${badge(r)}</span><span class="row-model">${esc(({rule:r.config.controller==='adaptive'?'离线动作轮换夹具':'程序化参考',jev:'Jev',llm:'LLM'} as Record<string,string>)[r.config.backend])}${r.config.generator==='llm'?' + LLM 生成':''}<small>${esc(r.config.backend==='rule'&&r.config.generator==='local'?'无实网配置':'实际用量见实验详情')}</small></span><span class="row-owner">${esc(r.owner.label||r.owner.id)}<small>${esc(new Date(r.createdAt).toLocaleString('zh-CN',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}))}</small></span><span class="row-arrow">↗</span></button>`).join(''):`<div class="empty-state"><span class="empty-symbol">◎</span><h2>${q||filter!=='all'?'没有匹配的实验':'从一场实验开始'}</h2><p>${q||filter!=='all'?'调整筛选，或创建新的实验。':'点击右上角「新建实验」，也可以让外部 Agent 从 CLI 创建。'}</p><button class="primary" id="empty-create">＋ 新建实验</button></div>`);
 document.getElementById('empty-create')?.addEventListener('click',()=>beginCreate());
}
// The DOM helper is intentionally strict elsewhere; the empty state is optional.
async function refreshRuns(){if(!token)return;const data=await api('/api/lab/runs');runs=list(data.runs).reverse() as LabView[];renderList();}
$('run-search').oninput=renderList;$('status-filter').onchange=renderList;$('refresh').onclick=()=>void refreshRuns().catch(e=>toast(String(e)));
async function historyUntil(id:string,limitSeq:number){const all:LabEvent[]=[];let after=0;historyComplete=true;while(after<limitSeq){const data=await api(`${path(id)}/events?after=${after}&limit=1000`);const page=list(data.events) as LabEvent[];if(!page.length)break;for(const e of page)if(e.seq<=limitSeq)all.push(e);const next=Number(data.nextCursor??page.at(-1)!.seq);if(next<=after)break;after=next;if(!data.hasMore)break;if(all.length>40000){historyComplete=false;break;}}return all;}
async function openRun(id:string,push=true){if($<HTMLDialogElement>('generation-dialog').open)closeDialog('generation-dialog');const g=++generation;streamAbort?.abort();pending=false;const next=await api(path(id));if(g!==generation)return;if(!isView(next))throw Error('服务端未返回有效的实验快照');state=next;selectedId=id;listing=false;imported=false;replaying=false;report=null;frames=[];decisionIndex=-1;cursor=next.lastSeq;events=await historyUntil(id,cursor);if(g!==generation)return;
 hide('list-page',true);hide('run-page',false);hide('replay-bar',true);lastSync=new Date().toISOString();if(push)history.pushState(null,'',`/lab?run=${encodeURIComponent(id)}`);setTab('overview',false);streamAbort=new AbortController();void stream(id,g,streamAbort.signal);void refreshRuns().catch(()=>{});$('title').setAttribute('tabindex','-1');$('title').focus({preventScroll:true});}
async function stream(id:string,g:number,signal:AbortSignal){while(!signal.aborted&&g===generation){try{const response=await fetch(`${path(id)}/stream?after=${cursor}`,{headers:{'x-gs-token':token},signal});if(!response.ok||!response.body)throw Error('事件流未连接');if(signal.aborted||g!==generation)return;setConnection(true,'实时已连接');const reader=response.body.getReader(),decoder=new TextDecoder();let buffer='';
 try{while(!signal.aborted){const r=await reader.read();if(r.done)break;buffer+=decoder.decode(r.value,{stream:true});if(buffer.length>16*1024*1024)throw Error('事件超过界面接收上限');let i;while((i=buffer.indexOf('\n\n'))>=0){const piece=buffer.slice(0,i);buffer=buffer.slice(i+2);const raw=piece.split('\n').filter(l=>l.startsWith('data: ')).map(l=>l.slice(6)).join('\n');if(!raw)continue;const e=JSON.parse(raw) as LabEvent;if(signal.aborted||g!==generation)return;if(e.runId!==id||e.seq<=cursor)continue;cursor=e.seq;events.push(e);if(events.length>40000){events=events.slice(-40000);historyComplete=false;}lastSync=e.at;
 if(e.type==='state'&&isView(e.data)){// Never let a late HTTP command response regress an SSE snapshot.
  if(!state||e.data.lastSeq>=state.lastSeq)state=e.data;
 }if(unwrap(e).type==='g_stream')queueGeneration();else queuePaint();}}
 }finally{try{await reader.cancel();}catch{/* already closed */}}
 if(!signal.aborted)setConnection(false,'连接中断，正在续读');
 }catch(e){if(signal.aborted||g!==generation)return;setConnection(false,'连接中断，正在续读');}
 if(!signal.aborted)await new Promise(resolve=>setTimeout(resolve,1000));}}
function render(){const s=current();if(!s)return;paintGeneration();$('run-page').dataset.runId=s.runId;rawRefs.clear();refCount=0;
 text('title',titleOf(s.config));text('crumb-title',titleOf(s.config));text('goal',goalOf(s));text('run-status',(replaying?'历史 · ':'')+(imported?'归档 · ':'')+(STATUS[s.status]??s.status));$('run-status').className=`badge ${s.status==='succeeded'?'success':terminal(s.status)?'warning':['running','stepping'].includes(s.status)?'active':''}`;
 text('owner',`${s.owner.kind==='agent'?'Agent 主持':'人工主持'} · ${s.owner.label||s.owner.id}`);text('source-caption',actualSource(s));
 html('run-tags',`<span>${s.config.kind==='game'?'完整任务实验':'判断组合实验'}</span><span>${s.config.controller==='adaptive'?'自主闭环 · 无参考解':'历史参考 / 固定判断基准'}</span><span>${esc(STRATEGIES[s.config.strategy])}</span><span>配置：${esc(s.config.backend==='rule'?'程序规则':s.config.backend.toUpperCase())}${s.config.generator==='llm'?' + LLM 生成':''}</span><span>${s.owner.id===actor.id?'你拥有控制权':'当前仅观察'}</span>${s.interventions.length?`<span class="tag-warning">${s.interventions.length} 条环境干预</span>`:''}`);
 hide('stale-banner',connected||imported||replaying);text('stale-banner',`连接已中断，下面是最后确认的快照（${lastSync?new Date(lastSync).toLocaleTimeString('zh-CN'):'时间未记录'}）。世界可能仍在服务端运行；重连后从事件序号继续。`);
 hide('diagnostic-dot',!['blocked','failed','fault','stopped'].includes(s.status));
 const a=actionsFor(state??s,actor.id,{replay:replaying,imported,connected,pending});
 for(const id of ['start','step','pause','takeover']){hide(id,!a.visible.includes(id as Command['action']));$<HTMLButtonElement>(id).disabled=!a.enabled[id];}
 text('start',s.status==='paused'?'继续运行':'开始运行');
 for(const id of ['cancel','checkpoint','edit'])$<HTMLButtonElement>(id).disabled=!(a.enabled[id==='edit'?(val('edit-when')==='scheduled'?'schedule':'intervene'):id]);
 hide('cancel',!a.own||a.done||replaying||imported);hide('intervene-open',!a.own||a.done||replaying||imported);
 $<HTMLButtonElement>('intervene-open').disabled=!a.quiet||!connected||pending;
 $<HTMLButtonElement>('fork-open').disabled=imported||replaying||!connected||pending;
 $<HTMLButtonElement>('fork').disabled=imported||!connected||pending;
 $<HTMLButtonElement>('config-copy').disabled=!connected||!cap;$<HTMLButtonElement>('clone-config').disabled=!connected||!cap;
 $<HTMLButtonElement>('replay').disabled=pending||(!imported&&!connected);text('replay',replaying?'选择回放时刻':'回放');
 text('operation-note',imported?'当前是离线归档。只读查看和导出，不向服务端发出写入。':replaying?'回放期间所有实验写操作不可用。返回实时后再操作。':!a.own?'当前由其他操作员控制。接管会暂停后续调度并留下记录。':'所有操作由服务端校验版本、权限和执行边界。');
 text('progress',`${s.world.delivered} / ${s.world.target}`);text('progress-note',terminal(s.status)?(s.status==='succeeded'?'根验收通过':'尚未获得根任务成功'):'局部成功不等于整局完成');
 text('energy',`${s.world.energy} / ${s.world.maxEnergy}`);text('bag-note',`背包 ${s.world.bag} / ${s.world.capacity} · 已执行 ${s.physicalActions} 步`);text('external',s.externalRequests);const simulated=actualSource(s).includes('测试替身');text('external-label',simulated?'提供商路径计数 · 测试替身':'实际外部请求');text('request-note',simulated?'原始账本计数，不是实网性能证据':`${s.requests} 次判断 / 生成请求（含本地）`);text('elapsed',duration(!replaying&&!imported&&connected&&s.startedAt&&!s.endedAt?Math.max(s.elapsedMs,Date.now()-Date.parse(s.startedAt)):s.elapsedMs));$('elapsed').title=!replaying&&!imported&&connected&&s.startedAt&&!s.endedAt?'观察端时钟估计；导出与评估仍以服务端记录为准。':'服务端记录的运行时长';text('elapsed-note',`整局上限 ${duration(s.config.deadlineMs)}`);
 const st=statusCopy(s);const showStatus=terminal(s.status)||['pausing','cancelling'].includes(s.status);$('stop-detail').className=`status-summary ${st.tone}${showStatus?'':' hidden'}`;text('status-title',st.title);text('status-body',st.body);text('status-reason',s.reason??'');hide('status-reason',!s.reason);text('status-detail',s.status==='succeeded'?'回看任务过程 →':'查看原因与证据 →');
 renderer.setState(s.world,replaying);text('world-mode',replaying?'所选时刻 · 只读':'服务端唯一世界');text('world-label',`物理回合 ${s.world.turn} · 背包 ${s.world.bag}/${s.world.capacity}`);text('sequence-label',`事件 #${s.lastSeq} / 世界 v${s.worldRevision}`);
 const retry=rec(s.transportRetry),hasRetry=retry.state==='waiting'||Number(retry.attempt)>1||retry.state==='failed'||retry.state==='aborted';hide('retry-card',!hasRetry);text('retry-title',retry.state==='waiting'?'Jev 访问暂时失败 · 等待重试':retry.state==='attempting'?'正在重新访问 Jev':retry.state==='recovered'?'Jev 访问已恢复':retry.state==='aborted'?'重试已中断':'Jev 访问未恢复');text('retry-detail',`尝试 ${retry.attempt??0} / ${retry.maxAttempts??0} · ${retry.state==='waiting'?`退避 ${retry.delayMs} ms · `:''}${retry.providerStatus?`HTTP ${retry.providerStatus} · `:''}世界不推进；每次请求单独计账。${retry.reason??''}`);
 const f=flowOf(s);text('root-goal',goalOf(s));text('current-skill',f.skill);text('current-phase',f.phase);text('immediate-task',f.immediate);text('process-status-note',f.detail);
 const latest=events.filter(e=>e.seq<=s.lastSeq).at(-1);const name=latest?unwrap(latest).type:'';
 const working=s.busy?rec(s.diagnostics).phase==='initializing'?'G 正在研判初始环境':rec(s.diagnostics).phase==='format-repairing'?'正在修正输出结构':rec(s.diagnostics).phase==='adapting'?'G 正在调整判断条件':['skill_generation_started','repair_requested'].includes(name)?'正在生成或验证技能':'正在推进决策量子':STATUS[s.status]??s.status;
 text('process-status-title',working);$('process-pulse').classList.toggle('working',s.busy&&!replaying);text('process-level',s.config.controller==='adaptive'&&s.config.kind==='game'?`G/S 层级 ${rec(s.diagnostics).depth??0}`:rec(s.activeSkill).spec?'子 G/S 活跃':s.config.kind==='judgment'?'固定任务':'父层 / 已返回');
 const keys=keyEvents(events,s.lastSeq);html('activity',keys.slice(-5).reverse().map(e=>`<button class="timeline-item ${e.tone}" data-seq="${e.seq}"><span class="timeline-dot"></span><span><b>${esc(e.title)}</b><small>${esc(e.detail)}</small></span><time>#${e.seq}</time><span aria-hidden="true">↗</span></button>`).join('')||'<div class="empty-note">尚未开始。首个决策之后，这里会出现可追溯的关键过程。</div>');
 if(tab==='decision')renderDecisions(s);if(tab==='diagnostics')renderDiagnostics(s);if(tab==='config')renderConfig(s);
 if(replaying){text('replay-position',`${frameIndex+1} / ${frames.length}`);text('replay-caption',`状态 #${s.lastSeq} · ${s.world.turn} 回合 · 所有面板与指标均来自此时刻`);hide('live',imported);$<HTMLButtonElement>('replay-prev').disabled=frameIndex===0;$<HTMLButtonElement>('replay-next').disabled=frameIndex>=frames.length-1;}
}
function renderDecisions(s:LabView){const ds=decisionsFrom(events,s);const selected=decisionIndex>=0?Math.min(decisionIndex,ds.length-1):ds.length-1;html('decision-select',ds.map((d,i)=>`<option value="${i}" ${i===selected?'selected':''}>${i+1} · ${rec(d.packet).level==='parent'?'父层技能选择':rec(d.packet).level==='child'?'子层动作判断':'任务判断'} · ${d.status==='abstained'?'不执行':d.status==='error'?'请求错误':d.status==='unreported'?'已记录输入':d.choice?'已选出候选':'返回'} · ${esc(sourceLabel(d.source))}</option>`).join('')||'<option>尚无判断记录</option>');
 const d=ds[selected];if(!d){html('decision-content','<div class="empty-state small-empty"><h3>尚未发生判断</h3><p>开始实验后，问题、候选与返回结果会在这里呈现。</p></div>');}
 else {const p=rec(d.packet),judgment=rec(d.judgment),cs=list(p.candidates),prob=rec(judgment.probabilities),chosen=d.choice;const context=rec(p.taskContext??rec(p.projection).taskContext);
 const result=d.status==='error'?'判断请求失败':d.status==='abstained'?'返回「不执行」':chosen?'已选择候选':'返回值未在此记录中提供';
 html('decision-content',`<div class="decision-summary"><span class="subtle-tag">${esc(sourceLabel(d.source))}</span><h3>${esc(p.goal??'当前任务判断')}</h3><p>${esc(result)}${d.latencyMs!==undefined?' · '+esc(duration(d.latencyMs)):''}</p></div>${factsGrid([['问题版本',p.questionVersion],['状态 / 策略版本',`${p.snapshotRevision??'—'} / ${p.policyVersion??'—'}`],['独立问题',d.questions],['实际外部请求',d.externalRequests]])}
 ${context.immediateObjective?`<div class="callout"><b>当前即时任务</b><p>${esc(rec(context.immediateObjective).description)}</p></div>`:''}
 <div class="section-heading"><h3>本次候选</h3><span class="muted">${cs.length} 个 · 保持记录中的顺序</span></div><div class="candidate-table">${cs.map(c=>`<div class="candidate-row ${chosen===c.id?'chosen':''}"><span class="candidate-marker">${chosen===c.id?'✓':'·'}</span><div><b>${esc(c.description??c.id)}</b><small class="mono">${esc(c.id)}</small></div><span>${typeof prob[c.id]==='number'?prob[c.id].toFixed(3):'未报告'}</span>${rawButton('候选事实与执行数据',c)}</div>`).join('')}</div><p class="field-help">数值为原始判断分布或确定性路由标记，不是任务成功率；“未报告”不补算为零。</p><div class="evidence-actions">${rawButton('本次完整判断',d)}${rawButton('本次输入事实',p)}</div>
 <details class="evidence-details"><summary>父子技能与局部结果</summary>${factsGrid([['当前技能',rec(rec(s.activeSkill).spec).title??'无活跃子技能'],['最近局部结果',rec(s.lastSkillResult).localSucceeded===true?'局部成功':rec(s.lastSkillResult).localSucceeded===false?'未获局部成功':'尚未记录']])}${rawButton('当前技能与最近实际结果',{active:s.activeSkill,last:s.lastSkillResult})}</details>`);}
 const keys=keyEvents(events,s.lastSeq);html('full-timeline',`${!historyComplete?'<p class="callout warning">界面缓存不是完整历史；请导出报告获取全部事件。</p>':''}${keys.map(e=>`<button class="timeline-item ${e.tone}" data-seq="${e.seq}"><span class="mono">#${e.seq}</span><span><b>${esc(e.title)}</b><small>${esc(e.detail)}</small></span><span>↗</span></button>`).join('')}${rawButton('全部原始事件（当前时刻以前）',events.filter(e=>e.seq<=s.lastSeq))}`);
}
$('retry-inspect').onclick=()=>{text('evidence-title','Jev 传输重试（不包含语义重问）');text('evidence-json',JSON.stringify(events.filter(e=>e.seq<=(current()?.lastSeq??0)&&['s_retry','lab_request_finished'].includes(unwrap(e).type)),null,2));openDialog('evidence-dialog');};
$('decision-select').onchange=()=>{decisionIndex=Number(val('decision-select'));render();};
function renderDiagnostics(s:LabView){if(s.config.controller==='adaptive'&&s.config.kind==='game'){renderAdaptiveDiagnostics(s);return;}const d=rec(s.diagnostics),f=rec(d.latestFailure),rep=rec(rec(d.budgets).repairs),st=statusCopy(s);const has=!!s.reason||Object.keys(f).length>0;
 html('diagnostics-content',`<div class="diagnostic-verdict ${has?'warning':''}"><span class="overline">${has?'当前诊断':'暂无阻塞证据'}</span><h3>${esc(has?st.title:'尚未记录需要处理的问题')}</h3><p>${esc(has?st.body:'这不等于无缺陷；后续的失败、修复和干预会在这里记录。')}</p>${s.reason?`<code>${esc(s.reason)}</code>`:''}</div><div class="config-columns"><section class="surface"><h3>预算与执行</h3>${factsGrid([['物理动作',`${s.physicalActions} / ${s.config.maxActions}`],['请求数',`${s.requests} / ${s.config.maxRequests}`],['修复次数',rep.limit===undefined?'本控制器未报告':`${rep.used} / ${rep.limit}`],['墙钟 / 上限',`${duration(s.elapsedMs)} / ${duration(s.config.deadlineMs)}`],['引擎推进耗时',duration(s.engineWorkMs)],['环境干预',s.interventions.length]])}</section><section class="surface"><h3>问题定位</h3>${factsGrid([['最近失败',f.reason??'未记录'],['子技能实际动作',rec(f.outcome).steps],['问题组织',STRATEGIES[s.config.strategy]],['请求调度',s.config.strategy==='serial'?'逐题串行':'合批接口（直接选择可能仅一题）'],['原始状态',s.status],['控制版本',s.controlVersion]])}</section></div><div class="evidence-actions">${rawButton('完整修复诊断',s.diagnostics??{note:'此控制器未提供技能恢复日志'})}${rawButton('最近一次判断',s.lastDecision)}${rawButton('环境干预记录',s.interventions)}${rawButton('运行时原始返回',s.outcome)}</div><p class="field-help">受阻的运行不能透明继续；更改条件应建立新分支。查看与导出不会自动请求模型。</p>`);
}
function refereePanel(s:LabView){const summary=refereeCopy(s.referee);if(!summary)return '';const r=rec(s.referee);return `<section class="surface" id="deadlock-referee"><h3>${esc(summary.title)}</h3><p class="callout ${summary.tone}">${esc(summary.body)}</p>${factsGrid([['判定世界版本',r.worldRevision],['裁判规则',r.policy],['判据',r.reason],['信息边界','仅观察者；不进入 G/S 输入、动作候选或自主记忆']])}${rawButton('查看裁判证明与事实（仅观察者）',s.referee)}</section>`;}
function renderAdaptiveDiagnostics(s:LabView){const d=rec(s.diagnostics),b=rec(d.budgets),a=rec(d.outputAccounting),v=rec(rec(d.latestValidation).diagnostics),issues=Array.isArray(v.issues)?v.issues:[],changes=Array.isArray(d.adaptations)?d.adaptations:[];
 html('diagnostics-content',`<div class="diagnostic-verdict"><span class="overline">自主调整 · 参考解隔离</span><h3>${esc(d.phase==='initializing'?'G 正在了解初始环境 · 尚未执行物理动作':d.phase==='format-repairing'?'正在修正 G 输出格式 · 尚未形成有效修订':d.phase==='adapting'?'G 正在重构 S 的决策条件':s.reason??'允许局部判断不完整，由实际反馈驱动调整')}</h3><p>G 只读取公开规则、允许观测及这次运行自己的输入、选择与实际反馈。不读取示例解、参考评分、参考成功轨迹或优化站位。</p></div>${refereePanel(s)}<div class="config-columns"><section class="surface"><h3>闭环计量</h3>${factsGrid([['开局 G 状态',({pending:'待启动',reviewing:'研判／装载中',ready:'初始条件已就绪',failed:'未完成', 'skipped-terminal':'起点已终局，跳过'} as Record<string,string>)[rec(d.initialization).status]??'旧记录未提供'],['开局研判轮数',rec(d.initialization).reviewCount??'—'],['S 判断',d.sCalls??0],['其中子问题判断',d.metaCalls??0],['G 总请求（含纠错）',`${d.gCalls??0} / ${b.gLimit??s.config.maxGCalls}`],['输出格式纠错',a.formatRepairs??0],['无效结构返回',a.invalidOutputs??0],['合法提案批次',a.validBatches??0],['有效修订尝试',a.revisionAttempts??0],['已应用调整',changes.length],['当前 / 子问题最大深度',`${d.depth??0} / ${b.depthLimit??s.config.maxDepth}`],['真实动作',s.physicalActions]])}</section><section class="surface"><h3>信息边界</h3>${factsGrid([['参考解读取','禁止'],['参考模拟准入','未使用'],['自动战术绑定','未使用'],['调整方式',d.controlMode??'历史记录'],['候选生命周期',d.candidatePolicy??'历史记录'],['G 陈述','未验证假设'],['S 弃权','进入有界调整；不强制执行'],['当前阶段',d.phase??'尚未开始']])}</section></div>${issues.length?`<section class="surface" id="output-validation"><h3>最近协议／条件诊断 · 不提供正确路径</h3><p>错误指向 JSON 路径。后续纠错可能已通过，实际生效见上方计数与事件。</p>${issues.map((i:any)=>`<div class="callout warning"><code>${esc(i.path||'/')}</code><small>${esc(i.code??'')}</small><p>${esc(i.code==='fixed_scope_excludes_goal'?'固定候选白名单排除了尚未到达的目标格。请由 G 修改条件；程序不会插入正确路线。':i.code==='candidate_scope_expired'?'快照候选已过期，需要由 G 重新设定；不会自动扩大范围。':i.message)}</p>${i.expected!==undefined?`<small>允许 / 预期：${esc(JSON.stringify(i.expected))}</small>`:''}</div>`).join('')}</section>`:''}<div class="evidence-actions">${rawButton('Jev 最近传输与重试',s.transportRetry??null)}${rawButton('完整调整证据',d)}${rawButton('当前决策程序',d.program??null)}${rawButton('最近实际问题',d.latestIssue??null)}${rawButton('只读子问题返回记录',d.subproblems??[])}${rawButton('S 实际看到的输入和回答',s.lastDecision)}</div>${list(d.subproblems).length?`<section class="surface" id="subproblem-results"><h3>子问题已返回原层</h3><p>深度边界只终止该分支。下列结果是模型判断或未解决记录，不是世界事实。</p>${list(d.subproblems).slice(-4).map((x:any)=>`<details><summary>${esc(rec(x.result).status==='answered'?'候选判断已返回':'未解决，已返回')} · 深度 ${Number(x.depth??0)} → ${Number(x.parentDepth??0)}</summary><p>${esc(rec(x.result).question??'')}</p><p>${esc(rec(x.result).reason??'父层 G 使用该结果继续调整；不自动执行动作。')}</p>${rawButton('查看返回证据',x)}</details>`).join('')}</section>`:''}<section class="surface"><h3>已提交的调整</h3>${changes.length?changes.map((x:any,i:number)=>`<details><summary>${i+1} · 层级 ${Number(x.depth??0)} · ${esc(rec(rec(x.patch).program).title??rec(x.patch).question??'调整')}</summary><p>只提交判断条件，世界动作仍须 S 选择。</p>${rawButton('前后上下文与选项',x)}</details>`).join(''):'<p>暂无已提交调整。生成提案不等于有效，根任务由实际交付与存活验收。</p>'}</section>`);}
function renderConfig(s:LabView){const c=s.config;html('config-content',`<div class="config-columns"><section class="surface"><h3>研究内容</h3>${factsGrid([['实验范围',c.kind==='game'?'完整任务':'判断组合'],[c.kind==='game'?'地图':'固定任务',titleOf(c)],['根目标',goalOf(s)],['控制器',c.kind==='game'?({adaptive:'自主 G/S · 参考解隔离',hierarchy:'旧父子技能 · 离线参考',program:'完整序列搜索',rules:'完整预置规则'}[c.controller]):'固定任务 G/S'],['判断组织',STRATEGIES[c.strategy]],['经验使用',c.experience]])}</section><section class="surface"><h3>来源与资源</h3>${factsGrid([['配置的判断来源',c.backend],['G 调整来源',c.kind==='game'?c.generator:'不适用'],['实际请求记录',actualSource(s)],['请求授权',c.allowLive?'本局已明确授权':'未授权真实模型'],['请求 / 问题上限',`${c.maxRequests} / ${c.maxQuestions}`],['整局截止',duration(c.deadlineMs)],['G 单次上限',duration(c.gTimeoutMs??120000)],['顺序种子',c.orderSeed],['合成延迟',`${c.delayMs} ms / 请求`]])}</section></div>${c.kind==='game'?'<p class="field-help">兼容配置中的 task 字段不改变主游戏目标；此处只显示实际生效的地图与根任务。</p>':''}
 <section class="surface lineage"><h3>运行身份与可复现性</h3>${factsGrid([['运行 ID',s.runId],['控制者',`${s.owner.kind} · ${s.owner.id}`],['创建于',s.createdAt],['界面版本','0.5.6'],['运行时协议版本',s.version],['资源初始可见',c.kind==='judgment'?(c.maskResources?'需要读取':'可见'):'主世界既定可见信息']])}<div class="evidence-actions">${rawButton('完整原始配置',c)}${rawButton('分支与经验来源',s.lineage)}${rawButton('受控干预脚本',c.interventions)}</div></section><p class="field-help">v0.5 自主路径不读取参考解；旧控制器仅作离线对照。判断重构不等于任务成功，实际世界结果独立验收。</p>`);}
$('status-detail').onclick=()=>setTab(state?.status==='succeeded'?'decision':'diagnostics');$('inspect-current').onclick=()=>setTab('decision');$('all-process').onclick=()=>setTab('decision');
async function cmd(action:Command['action'],extras:Partial<Command>={}){if(!state||imported||replaying||pending||!connected)return;const id=state.runId,g=generation;pending=true;render();try{const result=await api(path(id)+'/commands',{commandId:uid(),expectedControlVersion:state.controlVersion,actor,action,...extras});if(g!==generation||state?.runId!==id)return;
 if(!state||result.state.lastSeq>=state.lastSeq)state=result.state;render();if(result.checkpointId){await refreshCheckpoints();$<HTMLSelectElement>('checkpoint-list').value=result.checkpointId;checkpointSummary();toast('检查点已保存。');}void refreshRuns().catch(()=>{});return result;
 }catch(error){if(g===generation){toast(String(error));try{const latest=await api(path(id));if(g===generation&&isView(latest)&&latest.lastSeq>=(state?.lastSeq??0))state=latest;}catch{setConnection(false,'服务连接不可用');}}return null;}finally{if(g===generation){pending=false;render();}}}
$('step').onclick=()=>void cmd('step');$('start').onclick=()=>void cmd('start');$('pause').onclick=()=>void cmd('pause');
let confirmed:(()=>void)|undefined;
function confirm(title:string,body:string,action:()=>void){text('confirm-title',title);text('confirm-body',body);confirmed=action;openDialog('confirm-dialog');}
$('confirm-action').onclick=()=>{closeDialog('confirm-dialog');confirmed?.();confirmed=undefined;};
$('takeover').onclick=()=>confirm('接管并暂停这场实验？','当前量子可能完成，之后由你控制。旧 Agent 的新写入会被拒绝；接管会记录到实验轨迹。',()=>void cmd('takeover'));
$('cancel').onclick=()=>{closeDialog('more-dialog');confirm('取消本次实验？','取消后不能继续本次运行。已执行的动作不会回滚，报告与原始证据仍可导出。',()=>void cmd('cancel'));};
$('more-open').onclick=()=>{render();openDialog('more-dialog');};
$('copy-id').onclick=async()=>{if(!state)return;try{await navigator.clipboard.writeText(state.runId);toast('运行 ID 已复制。');}catch{text('evidence-title','运行 ID');text('evidence-json',state.runId);openDialog('evidence-dialog');}};
function errorIn(id:string,e:unknown){text(id,e instanceof Error?e.message:String(e));hide(id,false);}
function beginCreate(c?:LabConfig){$<HTMLFormElement>('create-form').reset();hide('create-error',true);const base=rec(c??cap?.defaults);const kind=c?.kind??'game';for(const radio of document.querySelectorAll<HTMLInputElement>('input[name="scope"]'))radio.checked=radio.value===kind;
 for(const [id,key]of [['scenario','scenario'],['task','task'],['strategy','strategy'],['controller','controller'],['backend','backend'],['generator','generator'],['experience','experience'],['seed','orderSeed'],['delay','delayMs'],['requests','maxRequests'],['deadline','deadlineMs'],['max-questions','maxQuestions'],['max-actions','maxActions'],['max-steps','maxSteps'],['max-search','maxSearchNodes'],['jev-retries','jevMaxRetries'],['jev-attempt-ms','jevAttemptTimeoutMs'],['jev-backoff','jevRetryBaseMs'],['jev-backoff-max','jevRetryMaxMs']]){if(base[key!]!==undefined)$<HTMLInputElement>(id!).value=String(base[key!]);}
 $<HTMLInputElement>('allow-live').checked=false;$<HTMLInputElement>('mask').checked=kind==='judgment'&&!!c?.maskResources;$<HTMLTextAreaElement>('interventions').value=c?.interventions.length?JSON.stringify(c.interventions,null,2):'';
 $<HTMLSelectElement>('preset').value=c?(c.backend==='rule'&&c.generator==='local'?'offline':c.backend==='jev'&&c.generator==='local'?'jev':c.backend==='jev'&&c.generator==='llm'?'live':'custom'):'offline';
 if(!c){$<HTMLSelectElement>('controller').value='adaptive';$<HTMLSelectElement>('backend').value='rule';$<HTMLSelectElement>('generator').value='local';$<HTMLSelectElement>('strategy').value='direct';}
 $<HTMLInputElement>('max-g').value=String(c?.maxGCalls??12);$<HTMLInputElement>('g-timeout-ms').value=String(c?.gTimeoutMs??600000);$<HTMLInputElement>('max-depth').value=String(c?.maxDepth??2);$<HTMLInputElement>('max-revisions').value=String(c?.maxRevisions??3);$<HTMLInputElement>('max-format-repairs').value=String(c?.maxFormatRepairs??2);$<HTMLDetailsElement>('advanced-config').open=false;updateCreate(false);openDialog('create-dialog');}
const scope=()=>document.querySelector<HTMLInputElement>('input[name="scope"]:checked')?.value??'game';
function updateCreate(fromPreset=false){const game=scope()==='game',preset=val('preset');if(fromPreset&&preset!=='custom'){$<HTMLSelectElement>('backend').value=preset==='offline'?'rule':'jev';$<HTMLSelectElement>('generator').value=preset==='live'&&game?'llm':'local';$<HTMLSelectElement>('controller').value='adaptive';$<HTMLInputElement>('allow-live').checked=false;if(preset!=='offline'&&Number(val('requests'))===512)$<HTMLInputElement>('requests').value='80';}
 $<HTMLInputElement>('deadline').max=game?'3600000':'120000';
 hide('game-fields',!game);hide('task-field',game);hide('controller-field',!game);hide('generator-field',!game);hide('mask-field',game);
 if(!game)$<HTMLSelectElement>('generator').value='local';
 const reference=game&&val('controller')!=='adaptive';
 const localOption=$<HTMLSelectElement>('backend').querySelector('option[value="rule"]');if(localOption)localOption.textContent=game&&!reference?'离线动作轮换夹具（非求解器）':'程序化参考';
if(reference){$<HTMLSelectElement>('backend').value='rule';$<HTMLSelectElement>('generator').value='local';$<HTMLInputElement>('delay').value='0';}
 $<HTMLSelectElement>('backend').disabled=reference;$<HTMLSelectElement>('generator').disabled=reference;
 const live=val('backend')!=='rule'||(game&&val('generator')==='llm');hide('live-permission',!live);$<HTMLInputElement>('allow-live').required=live;
 if(val('backend')!=='rule')$<HTMLInputElement>('delay').value='0';$<HTMLInputElement>('delay').disabled=val('backend')!=='rule'||reference;
 for(const id of ['backend','generator','preset']){const select=$<HTMLSelectElement>(id);for(const opt of select.options){if(id==='preset')opt.disabled=opt.value==='jev'&&!cap?.backends?.jev?.ready||opt.value==='live'&&(!game||!cap?.backends?.jev?.ready||!cap?.backends?.llm?.ready);else opt.disabled=opt.value!=='rule'&&opt.value!=='local'&&!cap?.backends?.[opt.value]?.ready;}}
 const ready=(!live)||((val('backend')==='rule'||cap?.backends?.[val('backend')]?.ready)&&(val('generator')!=='llm'||cap?.backends?.llm?.ready));$<HTMLButtonElement>('create').disabled=!token||!ready;
 text('live-readiness',ready?'使用服务端现有密钥。授权只适用于这一次新实验，不沿用原实验的支付许可。':'所需模型尚未在服务端配置；请检查 .env，不能静默退回规则。');
 text('strategy-help',({direct:'一个整体选择问题。保留“不执行”，不强制从坏选项里选一个。',batch:'独立的适用性与优先级问题合并请求；合批不等于计算免费。',serial:'与合批使用相同问题，但逐题发出请求，可能增加等待与调用数。',dependent:'第二轮选择依赖第一轮实际返回的适用性判断。'} as Record<string,string>)[val('strategy')]);
 text('create-summary',`${game?'完整任务 · '+(SCENARIOS[val('scenario')]??val('scenario')):'判断组合 · '+(TASKS[val('task')]?.title??val('task'))} / ${STRATEGIES[val('strategy')]} / ${live?'真实模型配置':game&&val('controller')==='adaptive'?'离线机制夹具（非求解器）':'程序化参考'}。创建后先保持就绪；原实验不会改变。`);}
$('new-run').onclick=()=>beginCreate();$('config-copy').onclick=()=>state&&beginCreate(state.config);$('clone-config').onclick=()=>{closeDialog('more-dialog');if(state)beginCreate(state.config);};
$('preset').onchange=()=>updateCreate(true);for(const el of document.querySelectorAll<HTMLInputElement>('input[name="scope"]'))el.onchange=()=>updateCreate(true);
for(const id of ['controller','backend','generator','strategy','scenario','task','max-g','max-depth','max-revisions','max-format-repairs'])$(id).onchange=()=>{if(['controller','backend','generator'].includes(id))$<HTMLSelectElement>('preset').value='custom';updateCreate(false);};
$('create-form').addEventListener('invalid',e=>{const el=e.target as HTMLElement;el.closest('details')?.setAttribute('open','');},true);
$('create-form').onsubmit=async e=>{e.preventDefault();hide('create-error',true);try{const game=scope()==='game';const interventions=val('interventions').trim()?JSON.parse(val('interventions')):[];if(!Array.isArray(interventions))throw Error('干预脚本必须是 JSON 数组。');const c={kind:scope(),task:val('task'),scenario:val('scenario'),controller:val('controller'),strategy:val('strategy'),backend:val('backend'),generator:game?val('generator'):'local',experience:val('experience'),orderSeed:Number(val('seed')),delayMs:Number(val('delay')),maxRequests:Number(val('requests')),maxQuestions:Number(val('max-questions')),maxActions:Number(val('max-actions')),maxSteps:Number(val('max-steps')),maxSearchNodes:Number(val('max-search')),deadlineMs:Number(val('deadline')),maskResources:!game&&checked('mask'),allowLive:checked('allow-live'),interventions};
 $<HTMLButtonElement>('create').disabled=true;const created=await api('/api/lab/runs',{requestId:uid(),actor,config:{...c,maxGCalls:Number(val('max-g')),gTimeoutMs:Number(val('g-timeout-ms')),maxDepth:Number(val('max-depth')),maxRevisions:Number(val('max-revisions')),maxFormatRepairs:Number(val('max-format-repairs')),jevMaxRetries:Number(val('jev-retries')),jevAttemptTimeoutMs:Number(val('jev-attempt-ms')),jevRetryBaseMs:Number(val('jev-backoff')),jevRetryMaxMs:Number(val('jev-backoff-max'))}});closeDialog('create-dialog');await openRun(created.runId);toast('实验已创建，尚未开始。');}catch(error){errorIn('create-error',error);}finally{updateCreate(false);}};
async function refreshCheckpoints(){if(!state||imported)return;const id=state.runId,data=await api(path(id)+'/checkpoints');if(state?.runId!==id||imported)return;checkpoints=list(data.checkpoints);html('checkpoint-list',checkpoints.map(c=>`<option value="${esc(c.id)}">${esc(c.id==='initial'?'初始局面':c.label+' · 回合 '+c.turn)}</option>`).join(''));checkpointSummary();}
function checkpointSummary(){const cp=checkpoints.find(c=>c.id===val('checkpoint-list'));text('checkpoint-summary',cp?`${cp.id==='initial'?'初始快照':cp.label} · 物理回合 ${cp.turn??'—'} · 世界版本 ${cp.worldRevision??'—'}。新实验重置控制器阶段与请求计数，不重置剩余物理世界预算。`:'读取检查点…');}
$('checkpoint-list').onchange=checkpointSummary;
$('fork-open').onclick=async()=>{if(!state)return;closeDialog('more-dialog');$<HTMLInputElement>('inherit').checked=false;$<HTMLInputElement>('fork-allow-live').checked=false;$<HTMLSelectElement>('fork-strategy').value=state.config.strategy;$<HTMLInputElement>('fork-requests').value=String(state.config.maxRequests);hide('fork-live',state.config.backend==='rule'&&state.config.generator==='local');hide('fork-error',true);try{await refreshCheckpoints();openDialog('fork-dialog');}catch(error){toast(String(error));}};
$('checkpoint').onclick=()=>void cmd('checkpoint',{label:`网页检查点 · ${state?.decisionSteps??0}`});
$('fork').onclick=async()=>{if(!state||imported||replaying||pending)return;hide('fork-error',true);const c=state.config,live=c.backend!=='rule'||c.generator==='llm';if(live&&!checked('fork-allow-live')){errorIn('fork-error','请为新分支重新授权真实请求，原授权不会自动继承。');return;}
 try{$<HTMLButtonElement>('fork').disabled=true;const r=await api(path()+'/forks',{requestId:uid(),actor,checkpointId:val('checkpoint-list'),memory:checked('inherit')?'inherit':'none',config:{strategy:val('fork-strategy'),...(live?{allowLive:true,maxRequests:Number(val('fork-requests'))}:{})}});closeDialog('fork-dialog');await openRun(r.runId);toast('已创建新分支；原实验未改变。');}catch(error){errorIn('fork-error',error);}finally{render();}};
$('intervene-open').onclick=()=>{closeDialog('more-dialog');hide('edit-error',true);openDialog('intervene-dialog');render();};
$('edit-when').onchange=()=>{hide('after-field',val('edit-when')!=='scheduled');text('edit',val('edit-when')==='scheduled'?'登记未来干预':'记录并应用');render();};
$('edit').onclick=async()=>{if(!state)return;const x=Number(val('point-x')),y=Number(val('point-y'));if(!Number.isInteger(x)||x<0||x>16||!Number.isInteger(y)||y<0||y>10){errorIn('edit-error','坐标必须在 X 0–16、Y 0–10 范围内。');return;}const scheduled=val('edit-when')==='scheduled';const extras={tool:val('tool') as NonNullable<Command['tool']>,point:{x,y},...(scheduled?{afterAction:Number(val('after-action'))}:{expectedWorldRevision:state.worldRevision})};const r=await cmd(scheduled?'schedule':'intervene',extras);if(r){closeDialog('intervene-dialog');toast('操作已记录，请以事件中的实际结果为准。');}};
function loadReplay(data:unknown){const r=rec(data);if(r.schema!=='gs/lab-export/v1'||!isView(r.state)||!Array.isArray(r.events))throw Error('请选择完整的 gs/lab-export/v1 报告。');frames=replayStates(r);if(!frames.length)throw Error('报告中没有可回放的完整状态；不能把终局指标套用到初始世界。');report=r;replaying=true;frameIndex=0;decisionIndex=-1;$<HTMLInputElement>('replay-slider').max=String(frames.length-1);$<HTMLInputElement>('replay-slider').value='0';hide('replay-bar',false);setTab('overview',false);render();}
$('replay').onclick=async()=>{try{if(replaying){$('replay-slider').focus();return;}const data=imported?report:await api(path()+'/export');loadReplay(data);}catch(error){toast(String(error));}};
function moveReplay(i:number){frameIndex=Math.max(0,Math.min(frames.length-1,i));$<HTMLInputElement>('replay-slider').value=String(frameIndex);decisionIndex=-1;render();}
$('replay-slider').oninput=()=>moveReplay(Number(val('replay-slider')));$('replay-prev').onclick=()=>moveReplay(frameIndex-1);$('replay-next').onclick=()=>moveReplay(frameIndex+1);
$('live').onclick=()=>{if(imported)return;replaying=false;decisionIndex=-1;hide('replay-bar',true);render();};
function download(data:unknown,name:string){const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),2000);}
$('export').onclick=async()=>{try{download(imported?report:await api(path()+'/export'),`${state?.runId??'experiment'}.json`);closeDialog('more-dialog');}catch(error){toast(String(error));}};
$('import-open').onclick=()=>$('import').click();
$('import').onchange=async()=>{try{const file=$<HTMLInputElement>('import').files?.[0];if(!file)return;if(file.size>64*1024*1024)throw Error('报告超过 64 MiB，请先缩小报告。');const data=JSON.parse(await file.text());if(data.schema!=='gs/lab-export/v1'||!isView(data.state)||!Array.isArray(data.events)||data.events.length>40000)throw Error('报告结构不兼容或事件数量过大，未加载。');
 const valid=data.events.every((e:any)=>Number.isSafeInteger(e.seq)&&e.runId===data.state.runId&&typeof e.type==='string');if(!valid)throw Error('报告事件身份或序号无效。');
 const safeFrames=replayStates(data);if(!safeFrames.length)throw Error('报告没有完整状态快照。');generation++;streamAbort?.abort();imported=true;listing=false;state=structuredClone(data.state);state!.readOnly=true;events=data.events;cursor=state!.lastSeq;hide('list-page',true);hide('run-page',false);loadReplay(data);history.pushState(null,'','/lab#archive');setConnection(false,'离线报告 · 只读');
 }catch(error){toast(String(error));}finally{$<HTMLInputElement>('import').value='';}};
for(const id of ['help-open','cli-help','limits-open'])$(id).onclick=()=>openDialog('help-dialog');
window.addEventListener('popstate',()=>{const query=new URL(location.href).searchParams,run=query.get('run');if(run){void openRun(run,false).then(()=>setTab(query.get('tab')??'overview',false)).catch(e=>toast(String(e)));}else showList(false);});
Object.defineProperty(window,'gsLabViewer',{value:{snapshot:()=>structuredClone(state),cursor:()=>cursor,readOnlyReplay:()=>replaying,displayedSnapshot:()=>structuredClone(current()),view:()=>({tab,listing,imported,replaying,connected,frameIndex}),generation:()=>generationPanel.snapshot()},writable:false});
async function boot(){try{const r=await fetch('/api/status'),b=await r.json();token=b.token;if(typeof token!=='string')throw Error('服务没有返回本地访问令牌');cap=await api('/api/lab/capabilities');setConnection(true,'本地服务已连接');await refreshRuns();const query=new URL(location.href).searchParams,run=query.get('run');if(run){await openRun(run,false);setTab(query.get('tab')??'overview',false);}setInterval(()=>void refreshRuns().catch(()=>{if(listing)setConnection(false,'未连接本地服务');}),5000);
 }catch(error){setConnection(false,'未连接本地服务');html('run-list','<div class="empty-state"><span class="empty-symbol">◎</span><h2>连接你的实验服务</h2><p>请在完整项目中运行 npm start，再打开 http://127.0.0.1:4173/lab。<br>你也可以导入已导出的报告，只读查看完整过程。</p></div>');$<HTMLButtonElement>('new-run').disabled=true;toast(String(error));}}
setInterval(()=>{if(!listing)paintGeneration();},500);
void boot();
