"""Actual bundled standalone bytes; Storage fixture tests serialization separately.
No real provider requests. Local server routes are covered by Node HTTP tests."""
import json,os,pathlib,sys
from playwright.sync_api import sync_playwright
ROOT=pathlib.Path(__file__).resolve().parent.parent;REPORT=ROOT/'reports/v052/regression-3';HTML=(ROOT/'play.html').read_text()
checks=[];errors=[];requests=[]
def check(name,ok):
 print(name,bool(ok),flush=True);checks.append({'name':name,'pass':bool(ok)});(REPORT/'browser-v03-progress.json').write_text(json.dumps(checks,ensure_ascii=False,indent=2))
 if not ok:raise AssertionError(name)
def mount(browser,viewport={'width':1440,'height':1150},data=None):
 p=browser.new_page(viewport=viewport,device_scale_factor=1);p.on('pageerror',lambda e:errors.append(str(e)));p.on('request',lambda r:requests.append(r.url))
 p.evaluate('''(data)=>{const m=new Map(Object.entries(data));Object.defineProperty(window,'localStorage',{value:{getItem:k=>m.get(k)??null,setItem:(k,v)=>m.set(k,v),removeItem:k=>m.delete(k)}});window.storageDump=()=>Object.fromEntries(m);}''',data or {})
 p.set_content(HTML,wait_until='load');p.wait_for_function('!!window.tuanziLab');return p
def close_result(p):
 if p.locator('#result-close').is_visible():p.locator('#result-close').click()
try:
 with sync_playwright() as api:
  browser=api.chromium.launch(executable_path=os.environ.get('CHROMIUM_PATH','/usr/bin/chromium'),headless=True,args=['--no-sandbox'])
  p=mount(browser)
  check('default-is-v03-offline-hierarchy','父子 G/S' in p.locator('#mode-label').inner_text() and p.locator('#count-api').inner_text()=='0')
  check('hierarchy-budget-panel-visible',p.locator('#hierarchy-panel').is_visible() and '0 / 180' in p.locator('#root-budget').inner_text())
  p.locator('#btn-step').click();p.wait_for_function('window.tuanziLab.exportTrace().policy.version===2',timeout=60000)
  t=p.evaluate('window.tuanziLab.exportTrace()')
  check('new-local-skill-generated-without-physical-action',t['finalWorld']['turn']==0 and t['planning']['searchRuns']==1)
  check('schema-is-skill-not-linear-plan',t['hierarchy']['catalogue']['records'][0]['spec']['schema']=='gs/skill/v1')
  check('trial-not-promoted-by-local-simulation',t['hierarchy']['catalogue']['records'][0]['successes']==0)
  p.locator('#btn-program').click();check('real-skill-json-dialog', 'place-resource' in p.locator('#program-json').inner_text() and '"x":' not in p.locator('#program-json').inner_text());p.locator('[data-close="program-dialog"]').click()
  p.locator('#btn-step').click();p.wait_for_function('window.tuanziLab.snapshot().turn===1')
  check('child-has-world-lease','子层' in p.locator('#hierarchy-status').inner_text() and '创造采集' in p.locator('#child-title').inner_text())
  p.screenshot(path=str(REPORT/'desktop-v03.png'),full_page=True)
  p.evaluate('''async()=>{for(let i=0;i<35&&!window.tuanziLab.hierarchy().summaries.length;i++)await window.tuanziLab.step();}''')
  h=p.evaluate('window.tuanziLab.hierarchy()')
  check('local-success-before-root-goal',h['summaries'][0]['localSucceeded'] and not h['summaries'][0]['rootSucceeded'] and p.evaluate('window.tuanziLab.snapshot().delivered')==0)
  check('local-result-returns-control-to-parent','父层' in p.locator('#hierarchy-status').inner_text() and '局部成功' in p.locator('#local-results').inner_text())
  check('actual-local-result-enters-experience',len(h['experience']['records'])==1 and h['catalogue']['records'][0]['successes']==1)
  p.locator('#btn-book').click();check('catalogue-shows-provenance-and-local-evidence','grammar-search' in p.locator('#book-records').inner_text() and '局部实测成功 1' in p.locator('#book-records').inner_text());p.locator('[data-close="book-dialog"]').click()
  cold=p.evaluate('window.tuanziLab.runOfflineToEnd()');close_result(p)
  check('full-root-task-completes-after-multiple-children',cold['result']=={'kind':'done','outcome':'succeeded'} and len(cold['hierarchy']['summaries'])>1)
  check('root-physical-budget-count-is-not-meta-actions',cold['hierarchy']['budget']['used']['actions']==cold['finalWorld']['turn'])
  p.locator('#btn-reset').click();p.locator('#btn-step').click();p.wait_for_function('window.tuanziLab.snapshot().turn===1')
  warm=p.evaluate('window.tuanziLab.exportTrace()');check('warm-rebind-has-zero-new-generation',warm['planning']['searchRuns']==0 and warm['planning']['skillHits']==1)
  p.locator('[data-scenario="remix"]').click();mirror=p.evaluate('window.tuanziLab.runOfflineToEnd()');close_result(p)
  check('mirror-uses-same-skill-version-not-old-coordinates',mirror['result']=={'kind':'done','outcome':'succeeded'} and mirror['planning']['searchRuns']==0 and mirror['hierarchy']['summaries'][0]['skillId']==cold['hierarchy']['summaries'][0]['skillId'])
  p.locator('#btn-replay').click();p.locator('#replay-range').fill('15');p.locator('#replay-range').dispatch_event('input');check('hierarchical-replay-is-read-only',p.evaluate('window.tuanziLab.snapshot().delivered')==5 and '15 /' in p.locator('#replay-position').inner_text());p.locator('[data-close="replay-dialog"]').click()
  p.locator('[data-scenario="guarded"]').click();p.locator('#btn-step').click();p.wait_for_function('window.tuanziLab.snapshot().turn===1')
  p.locator('#btn-snapshot').click();snap=p.evaluate('window.tuanziLab.snapshot()');p.locator('#btn-step').click();p.wait_for_function('window.tuanziLab.snapshot().turn===2');p.locator('#btn-restore').click();check('snapshot-starts-new-child-boundary-not-fake-resume',p.evaluate('window.tuanziLab.snapshot()')==snap and p.evaluate('window.tuanziLab.hierarchy().summaries.length')==0)
  p.locator('[data-scenario="guarded"]').click();p.locator('#btn-step').click();p.wait_for_function('window.tuanziLab.snapshot().turn===1');p.evaluate('window.tuanziLab.edit("wall",{x:0,y:0})')
  p.evaluate('''async()=>{for(let i=0;i<40&&!window.tuanziLab.hierarchy().summaries.length;i++)await window.tuanziLab.step();}''')
  h=p.evaluate('window.tuanziLab.hierarchy()');check('irrelevant-edit-rebinds-without-new-G',h['summaries'][0]['localSucceeded'] and p.evaluate('window.tuanziLab.exportTrace().planning.searchRuns')==0)
  check('edited-trial-is-not-attributed-as-unassisted',h['summaries'][0]['status']=='external_change')
  p.locator('#btn-connect').click();check('unconfigured-new-live-modes-disabled',p.locator('#run-mode option[value="reactive-jev"]').is_disabled() and p.locator('#run-mode option[value="reactive-live"]').is_disabled())
  p.locator('#run-mode').select_option('reactive-record');p.locator('#apply-mode').click();check('record-only-mode-visible','只记录' in p.locator('#experience-state').inner_text())
  p.locator('#btn-connect').click();p.locator('#run-mode').select_option('reactive-off');p.locator('#apply-mode').click();check('experience-off-mode-visible','关闭' in p.locator('#experience-state').inner_text())
  p.evaluate('window.tuanziLab.setMode("reactive")');p.locator('[data-scenario="guarded"]').click();p.locator('#btn-compare').click();p.wait_for_selector('[data-replay-row="3"]',timeout=120000)
  check('four-way-comparison-includes-strong-rules-and-linear-plan',p.locator('.comparison-card').count()==4 and 'v0.2.1' in p.locator('#compare-results').inner_text())
  check('comparison-shows-all-outcomes-without-invented-performance-win',p.locator('.comparison-outcome').all_inner_texts()==['任务完成']*4 and '85' in p.locator('#compare-results').inner_text())
  p.screenshot(path=str(REPORT/'comparison-v03.png'),full_page=True);p.locator('[data-close="compare-dialog"]').first.click()
  saved=p.evaluate('window.storageDump()');p.close()
  reload=mount(browser,data=saved);reload.locator('#btn-step').click();reload.wait_for_function('window.tuanziLab.snapshot().turn===1',timeout=60000)
  check('serialized-fixture-restores-skill-and-experience-not-browser-reload-claim',reload.evaluate('window.tuanziLab.exportTrace().planning.searchRuns')==0 and len(reload.evaluate('window.tuanziLab.hierarchy().experience.records'))>0);reload.close()
  mobile=mount(browser,{'width':390,'height':844});check('mobile-no-horizontal-overflow',mobile.evaluate('document.documentElement.scrollWidth<=innerWidth+1'))
  mobile.locator('#btn-step').click();mobile.wait_for_function('window.tuanziLab.exportTrace().policy.version===2',timeout=60000);mobile.locator('#btn-step').click();mobile.wait_for_function('window.tuanziLab.snapshot().turn===1')
  check('mobile-hierarchy-and-phase-render','子层' in mobile.locator('#hierarchy-status').inner_text() and 'place-resource' in mobile.locator('#program-steps').inner_text())
  mobile.screenshot(path=str(REPORT/'mobile-v03.png'),full_page=True)
  mobile.locator('#btn-book').click();check('mobile-dialog-bounded',mobile.locator('#book-dialog').bounding_box()['width']<=390);mobile.locator('[data-close="book-dialog"]').click()
  mobile.evaluate('window.tuanziLab.loadScenario("meadow")');mobile.locator('#speed').select_option('120');mobile.locator('#btn-play').click();mobile.wait_for_function('window.tuanziLab.snapshot().turn>=3');mobile.locator('#btn-play').click();mobile.wait_for_timeout(300);turn=mobile.evaluate('window.tuanziLab.snapshot().turn');mobile.wait_for_timeout(300);check('pause-stops-actions-and-energy',mobile.evaluate('window.tuanziLab.snapshot().turn')==turn)
  check('no-uncaught-browser-errors',not errors);check('offline-sends-no-external-requests',not any(u.startswith(('http:','https:')) for u in requests));browser.close()
except Exception as e:checks.append({'name':'unexpected-test-exception','pass':False,'error':str(e)});print(str(e),flush=True)
finally:
 report={'mode':'Chromium standalone bytes via set_content','storage':'Injected Storage serialization fixture; not actual navigation/reload proof','realProviders':'NOT_RUN','checks':checks,'errors':errors,'requests':requests};(REPORT/'browser-v03.json').write_text(json.dumps(report,ensure_ascii=False,indent=2));print(json.dumps({'pass':sum(x['pass'] for x in checks),'total':len(checks),'failed':[x for x in checks if not x['pass']]},ensure_ascii=False));sys.exit(0 if all(x['pass'] for x in checks) else 1)
