/** Local operator bridge; never exposed to the tested G/S providers. */
import fs from 'node:fs/promises';
import path from 'node:path';
import crypto from 'node:crypto';
export const fault=(code,message)=>Object.assign(Error(message),{code});
export const id=x=>{if(typeof x!=='string'||!/^[-a-zA-Z0-9_.:]{1,100}$/.test(x))throw fault('INVALID_ID','Invalid identifier');return x;};
export function loopback(raw){const u=new URL(raw);if(u.protocol!=='http:'||!['127.0.0.1','localhost','[::1]'].includes(u.hostname)||u.username||u.password||u.search||u.hash||u.pathname!=='/')throw fault('LOCAL_ONLY','Use a loopback HTTP origin, without credentials or path');return u.origin;}
export function redact(value){
 if(typeof value==='string')return value.replace(/\bBearer\s+[^\s"'\\]+/gi,'Bearer [REDACTED]').replace(/\bsk-[A-Za-z0-9_-]{12,}/g,'[REDACTED]').replace(/((?:TYPESAFE|LLM)_API_KEY\s*[:=]\s*["']?)([A-Za-z0-9_.-]{12,})/g,'$1[REDACTED]');
 if(Array.isArray(value))return value.map(redact);
 if(value&&typeof value==='object')return Object.fromEntries(Object.entries(value).map(([k,v])=>[k,/(?:authorization|api[_-]?key|access[_-]?token|password|secret|^token$)/i.test(k)?'[REDACTED]':redact(v)]));
 return value;
}
export function pointer(value,p=''){if(p==='')return value;if(!p.startsWith('/')||p.length>1024)throw fault('INVALID_POINTER','Use an RFC6901 JSON pointer');let current=value;for(const part of p.slice(1).split('/')){if(/~(?![01])/u.test(part))throw fault('INVALID_POINTER','Invalid escape');const key=part.replaceAll('~1','/').replaceAll('~0','~');if(['__proto__','prototype','constructor'].includes(key)||!current||typeof current!=='object'||!Object.hasOwn(current,key))throw fault('POINTER_NOT_FOUND','Pointer not found');current=current[key];}return current;}
export function chunk(value,{pointer:p='',offset=0,limit=24000,expectedHash}={}){const text=JSON.stringify(redact(pointer(value,p)),null,2),sha256=crypto.createHash('sha256').update(text).digest('hex');if(expectedHash&&expectedHash!==sha256)throw fault('CONTENT_CHANGED','The snapshot changed; restart paging or use an immutable archive');return {pointer:p,offset,totalChars:text.length,text:text.slice(offset,offset+limit),nextOffset:offset+limit<text.length?offset+limit:null,sha256,encoding:'JSON text; offsets are UTF-16 code units',redacted:true};}
const OP_DOCS=new Set(['AGENTS.md','package.json','docs/MCP-v0.5.5.md','docs/RETRY-v0.5.5.md','docs/AGENT-v0.5.5.md','docs/API-v0.5.5.md','docs/DESIGN-v0.5.4.md','docs/OUTPUT-CONTRACT-v0.5.2.md']);
function sensitive(rel){return rel.split('/').some(p=>p.startsWith('.')||p==='node_modules'||p==='credentials'||p==='secrets')||/\.(pem|key|p12|pfx|crt|db|sqlite)$/i.test(rel)||/(^|\/)(id_rsa|id_ed25519|credentials)(\.|$)/i.test(rel);}
function allowed(rel,profile){if(sensitive(rel)||! /\.(md|txt|ts|js|mjs|json|css|html|py|diff)$/.test(rel))return false;if(profile==='audit')return true;return OP_DOCS.has(rel)||rel.startsWith('src/adaptive/')||rel.startsWith('src/lab/')||rel.startsWith('vendor/gs-engine-ts/src/')||['server/adaptive.mjs','server/judgment.mjs','server.mjs'].includes(rel)||rel.startsWith('server/mcp/')||rel.startsWith('schemas/');}
export class ProjectAccess{
 constructor(root,profile='operator',exportDir){this.root=path.resolve(root);this.profile=profile;this.exportDir=path.resolve(exportDir??path.join(this.root,'.gs-lab/exports'));}
 async safeFile(rel,archive=false){
  if(typeof rel!=='string'||!rel||rel.includes('\\')||rel.includes('\0')||path.isAbsolute(rel)||rel.split('/').some(p=>p==='..'||p==='.'||p===''))throw fault('PATH_FORBIDDEN','Use a canonical relative file path');
  if(archive?!/^run-[-\w]+\.json$/.test(rel):!allowed(rel,this.profile))throw fault('PATH_FORBIDDEN','File is outside this profile or is sensitive');
  const base=archive?this.exportDir:this.root,realBase=await fs.realpath(base).catch(()=>{throw fault('NOT_FOUND','Directory is unavailable');});
  let target=base;for(const part of rel.split('/')){target=path.join(target,part);const st=await fs.lstat(target).catch(()=>{throw fault('NOT_FOUND','File is unavailable');});if(st.isSymbolicLink())throw fault('PATH_FORBIDDEN','Symlinks are not exposed');}
  const real=await fs.realpath(target);if(!real.startsWith(realBase+path.sep))throw fault('PATH_FORBIDDEN','Outside root');const st=await fs.stat(real);if(!st.isFile()||st.size>(archive?256:4)*1024*1024)throw fault('FILE_LIMIT','File is not regular or exceeds the documented size cap');return {real,st};
 }
 async list({prefix='',offset=0,limit=100}={}){if(prefix.includes('..')||prefix.includes('\\')||prefix.startsWith('/'))throw fault('PATH_FORBIDDEN','Invalid prefix');const all=[];let scanned=0;const visit=async(dir,rel='')=>{for(const e of (await fs.readdir(dir,{withFileTypes:true})).sort((a,b)=>a.name.localeCompare(b.name))){if(++scanned>20000)throw fault('FILE_LIMIT','Project index exceeds 20000 entries');const r=rel?rel+'/'+e.name:e.name;if(e.isSymbolicLink()||sensitive(r))continue;if(e.isDirectory())await visit(path.join(dir,e.name),r);else if(allowed(r,this.profile)&&r.startsWith(prefix))all.push({path:r,scope:this.profile==='audit'?'audit-only; may contain reference answers':'operator-readable'});}};await visit(this.root);return {files:all.slice(offset,offset+limit),total:all.length,nextOffset:offset+limit<all.length?offset+limit:null,profile:this.profile,excludes:['secrets','hidden paths','symlinks','unsupported binaries'],complete:true};}
 async read({path:rel,offset=0,limit=24000,expectedHash}={}){const {real}=await this.safeFile(rel);const text=redact(await fs.readFile(real,'utf8')),sha256=crypto.createHash('sha256').update(text).digest('hex');if(expectedHash&&sha256!==expectedHash)throw fault('CONTENT_CHANGED','File changed while paging');return {path:rel,offset,text:text.slice(offset,offset+limit),totalChars:text.length,nextOffset:offset+limit<text.length?offset+limit:null,sha256,profile:this.profile,redacted:true};}
 async search({query,prefix='',offset=0,limit=50}){if(!query||query.length>200)throw fault('INVALID_QUERY','Literal query length 1..200');const {files}=await this.list({prefix,limit:20000});const hits=[];for(const f of files){let safe;try{safe=await this.safeFile(f.path);}catch(e){if(e.code==='FILE_LIMIT')continue;throw e;}const {real,st}=safe;if(st.size>512*1024)continue;const lines=redact(await fs.readFile(real,'utf8')).split('\n');for(let i=0;i<lines.length;i++)if(lines[i].toLowerCase().includes(query.toLowerCase()))hits.push({path:f.path,line:i+1,text:lines[i].slice(0,800)});if(hits.length>10000)throw fault('SEARCH_LIMIT','Narrow query or prefix');}return {matches:hits.slice(offset,offset+limit),total:hits.length,nextOffset:offset+limit<hits.length?offset+limit:null,scope:'literal text; files above 512KiB excluded, use paged file reads'};}
 async archive(name){const {real}=await this.safeFile(name,true);let data;try{data=JSON.parse(await fs.readFile(real,'utf8'));}catch{throw fault('INVALID_ARCHIVE','Not valid JSON');}if(data.schema!=='gs/lab-export/v1')throw fault('INVALID_ARCHIVE','Not a G/S export');this.checkLane(data.state??data);return data;}
 checkLane(state){if(this.profile==='operator'&&(state?.config?.kind!=='game'||state?.config?.controller!=='adaptive'))throw fault('REFERENCE_LANE_HIDDEN','Reference/judgment records are audit-only and must not guide autonomous runs');}
 async archives({offset=0,limit=100}={}){let entries;try{entries=await fs.readdir(this.exportDir,{withFileTypes:true});}catch(e){if(e.code==='ENOENT')return {archives:[],total:0,nextOffset:null};throw e;}const out=[];for(const e of entries){if(!e.isFile()||!/^run-[-\w]+\.json$/.test(e.name))continue;try{const data=await this.archive(e.name);out.push({name:e.name,runId:data.state.runId,status:data.state.status,version:data.version,readOnly:true});}catch{/* Excluded, oversized, invalid or reference records are not promoted. */}}out.sort((a,b)=>a.name.localeCompare(b.name));return {archives:out.slice(offset,offset+limit),total:out.length,nextOffset:offset+limit<out.length?offset+limit:null,profile:this.profile};}
}
export class LabClient{
 constructor(base,fetcher=fetch){this.base=loopback(base);this.fetcher=fetcher;this.token=null;}
 async fetchJson(route,method='GET',body,signal){const response=await this.fetcher(this.base+route,{method,redirect:'error',signal:signal??AbortSignal.timeout(15000),headers:{...(this.token?{'x-gs-token':this.token}:{}),...(body?{'content-type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})});
  const chunks=[];let bytes=0;for await(const part of response.body){bytes+=part.length;if(bytes>256*1024*1024)throw fault('RESPONSE_LIMIT','Response exceeds 256MiB');chunks.push(part);}const data=JSON.parse(Buffer.concat(chunks).toString('utf8'));if(!response.ok)throw fault(data.error?.code??'HTTP_ERROR',data.error?.message??String(data.error));return data;
 }
 async request(route,{method='GET',body,signal}={}){if(!this.token){const status=await this.fetchJson('/api/status','GET',undefined,signal);if(typeof status.token!=='string')throw fault('BOOTSTRAP_FAILED','Lab token missing');this.token=status.token;}try{return await this.fetchJson(route,method,body,signal);}catch(e){if(e.code==='UNAUTHORIZED')this.token=null;throw e;}}
}
